A entregar:
- Algoritmo escrito en lenguaje natural
- codigo python
- resultado del codigo python

In [292]:
import pandas as pd

# NIVEL 1:

## EJERCICIO 1: SELECCIÓN DE PERSONAL

In [251]:
inputs_test = [ 
    "Laura Serra", "608112233", 6, 3, 3, 3, 
    "Clara Gómez", "655221199", 3, 3, 3, 2, 
    "Sergio López", "644112211", 3, 2, 2, 2, 
    "Candidat Error", "611000000", 5, 7, 3, 2, # Català = 7 → NO VÀLID 
    "Marta Ruiz", "699887766", 2, 3, 2, 1, 
    "Marc Vidal", "612443322", 6, 3, 3, 3, 
    "Júlia Romero", "677998877", 5, 3, 3, 2, 
    "Pol Navarro", "699554433", 4, 3, 2, 2, 
    "David Ferrer", "677665544", 2, 1, 1, 1, 
    "Anna Paredes", "633221144", 1, 2, 1, 0,  
    "Anibal Paredes", "644272727", 1, 2, 1, 0,  
    "Núria Casals", "600112200", 8, 2, 3, 3 # 11è candidat     
]

Lenguaje natural:
Por cada candidato se obtiene el nombre completo, número de contacto, años de experiencia, conocimientos de catalana (0-3), dominio de excel (0-3) y titulo academico (0-3). Según la puntuación tendrá una categoria asignada: >= 12 prioridad alta; 12 >= 8 candiadto adecuado; 8 > no prioritario.

A partir de los datos aportados se obtienen 6 datos por cada candidato. Teniendo en cuenta que es una estructura fija se crea un diccionario a partir de los nombres con un subdiccionario por cada candidato. 

Para mantener el orden de llegada (un diccionario no es indexado) se añade la variable orden. De esa forma, al llegar a 10 candidatos rompe (condición + break)

In [252]:

def obtenir_dades(formularios):
    info_candidatos = {}
    orden = 0
    for i in range(0, len(formularios),6):
        orden += 1
        if orden > 10:
            break
        nombre = formularios[i]
        info_candidatos[nombre] =  {
        "contacto" : formularios[i+1],
        "experiencia" : formularios[i+2],
        "nv_catalan" : formularios[i+3],
        "nv_excel" : formularios[i+4],
        "nv_academico" : formularios[i+5],
        "orden_llegada" : orden}

    return info_candidatos

Para validar los datos, se comprueba:
- Que el nombre sean todo letras y una longitud mayor a 2 (hay nombres con 2 letras)
- Las categorias nv_catalan, nv_excel y nv_academico cualquier valor fuera del rango 0-3 estará descalificado. 
- El numero de contacto tenga una lontigud de 9 y empiece por 6 o 7.

Por defecto todos los usuarios son aptos, pero si no cumplen una de las condiciones de arriba serán no aptos y en función de si son aptos/no_aptos se les agrega a una lista y se borra de la candidatura

In [253]:
def validad_dades(formularios):
    clean_candidatos = {"aptos":[],"no_aptos":[]}
    
    for nombre, categoria in formularios.items():
        apto = True
        
        if not nombre.replace(" ", "").isalpha() or len(nombre.strip()) < 2:
            apto = False

        if categoria["nv_catalan"] not in [0,1,2,3] or categoria["nv_excel"] not in [0,1,2,3] or categoria["nv_academico"] not in [0,1,2,3]:
            apto = False

        if len(categoria["contacto"]) != 9 and not categoria["contacto"].startswith(("6","7")):
            apto = False

        if apto:
            clean_candidatos["aptos"].append(nombre)
        else:
            clean_candidatos["no_aptos"].append(nombre)

    for nombre in clean_candidatos["no_aptos"]:
        del formularios[nombre]

    return formularios

Una vez filtrados los usuarios aptos, se calcula la puntuación teniendo en cuenta la experiencia y los puntos en las catgorias nv_catalan, nv_excel y nv_academico:

puntuación = años de experiencia * 1.5 + puntuación categorias

Primero se calcula la experiencia y luego las categorias. Finalmente se juntan

In [254]:
def calcular_puntuacion(formularios):
    for nombre in formularios.keys():
        p_experiencia = formularios[nombre]["experiencia"]*1.5
        p_categorias = formularios[nombre]["nv_catalan"]+formularios[nombre]["nv_excel"]+formularios[nombre]["nv_academico"]
        formularios[nombre]["puntuacion"] = p_experiencia + p_categorias
    return formularios

Con la puntuación se crean una serie de condiciones:

- si supera o iguala los 12p es prioritat alta; 
- mayor o igual a 8 es candidat adequat; 
- sino es no prioritari. 

El orden de las condiciones va en orden decreciente en los puntos. En el caso que tenga 13p no saltará la primera condición. Si pusieramos la condicion "puntuacion >=8" la primera se quedaría ahí, porque cumple la condición, pero le corresponderia la prioridad alta.

In [255]:
def classificar_candidat(formularios):
    for nombre in formularios.keys():
        if formularios[nombre]["puntuacion"] >= 12:
            formularios[nombre]["prioridad"] = "Prioritat Alta"
        elif formularios[nombre]["puntuacion"] >= 8:
            formularios[nombre]["prioridad"] = "Candidat adequat"
        else:
            formularios[nombre]["prioridad"] = "No prioritari"
    return formularios

Mostrar los candidatos individualmente. Se imprime el nombre y demás información en diferentes lineas. Cada usuario se separa por "------------------" para que se aprecie mejor la información. También se ha añadido información complementaria para facilitar la lectura.

In [256]:
def mostrar_individual(formularios):
    for nombre, categorias in formularios.items():
        print(f'Candidato nº {categorias["orden_llegada"]}')
        print(f"Nombre: {nombre}")
        print(f"Telefono: {categorias["contacto"]}")
        print(f"Años de experiencia: {categorias["experiencia"]}")
        print(f"Nivel de catalán: {categorias["nv_catalan"]}")
        print(f"Nivel de excel: {categorias["nv_excel"]}")
        print(f"Nivel academico: {categorias["nv_academico"]}")
        print(f"Puntuación: {categorias["puntuacion"]}")
        print(f"Prioridad: {categorias["prioridad"]}")
        print("-" * 30)

Para mostrar el informe final se ha obtenido de los formularios el nombre y las categorias (nv_catalan, experiencia...).

Se añaden los elementos imprescindibles del informe a una lista para mejorar la ordenación (un diccionario no se puede ordenar tan facilmente).

Al ordenar, el campo "prioritat" es de tipo texto, por lo que se ordena alfabeticamente. En este caso el orden seria: Candidat adequat; No prioritari; Prioritat alta (o viceversa). Para ordenarlo de la manera que queremos, se substituye por un 2-1-3 respectivamente.

sort() ordena por el primer campo que encuentra en la lista. Al ser una lista de listas, coge del candidato X el valor de prioritat. En caso de empate, obtiene el segundo valor del candidato X -> puntuación.

En sort() se ha definido "reverse=True" para que se ordene la prioridad y la puntuación de mayor a menor. Si no se ponia saldria de menor a mayor.

In [257]:
def mostrar_informe(formularios):
    listado = []
    orden_prioritario = {"Prioritat Alta":3,
                         "Candidat adequat":2,
                         "No prioritari":1}
    for nombre, categorias in formularios.items():
        listado.append([
            orden_prioritario[categorias["prioridad"]],
            categorias["puntuacion"],
            nombre,
            categorias["contacto"]])
    listado.sort(reverse=True)
    orden_prioritario = {3:"Prioritat Alta",
                        2:"Candidat adequat",
                        1:"No prioritari"}
    print("INFORME FINAL:")
    for prioridad, puntuacion, nombre, contacto in listado:
        print(f"Nombre del candidato: {nombre}. Contacto: {contacto}. Prioridad: {orden_prioritario[prioridad]}. Puntuación final: {puntuacion}.")

Todas las funciones juntas. Cada función va modificando los datos y se los pasa a la siguiente, excepto mostrar_individual y mostrar_informe que obtienen los datos ya arreglados de la funcion classificar_candidat.

In [258]:
def main_seleccio(formularios_candidatos):
    datos = obtenir_dades(formularios_candidatos)
    datos_validados = validad_dades(datos)
    puntos_candidatos = calcular_puntuacion(datos_validados)
    candidatos_clasificados = classificar_candidat(puntos_candidatos)
    mostrar_individual(candidatos_clasificados)
    mostrar_informe(candidatos_clasificados)
    

main_seleccio(inputs_test)

Candidato nº 1
Nombre: Laura Serra
Telefono: 608112233
Años de experiencia: 6
Nivel de catalán: 3
Nivel de excel: 3
Nivel academico: 3
Puntuación: 18.0
Prioridad: Prioritat Alta
------------------------------
Candidato nº 2
Nombre: Clara Gómez
Telefono: 655221199
Años de experiencia: 3
Nivel de catalán: 3
Nivel de excel: 3
Nivel academico: 2
Puntuación: 12.5
Prioridad: Prioritat Alta
------------------------------
Candidato nº 3
Nombre: Sergio López
Telefono: 644112211
Años de experiencia: 3
Nivel de catalán: 2
Nivel de excel: 2
Nivel academico: 2
Puntuación: 10.5
Prioridad: Candidat adequat
------------------------------
Candidato nº 5
Nombre: Marta Ruiz
Telefono: 699887766
Años de experiencia: 2
Nivel de catalán: 3
Nivel de excel: 2
Nivel academico: 1
Puntuación: 9.0
Prioridad: Candidat adequat
------------------------------
Candidato nº 6
Nombre: Marc Vidal
Telefono: 612443322
Años de experiencia: 6
Nivel de catalán: 3
Nivel de excel: 3
Nivel academico: 3
Puntuación: 18.0
Prioridad: Prioritat Alta
------------------------------
Candidato nº 7
Nombre: Júlia Romero
Telefono: 677998877
Años de experiencia: 5
Nivel de catalán: 3
Nivel de excel: 3
Nivel academico: 2
Puntuación: 15.5
Prioridad: Prioritat Alta
------------------------------
Candidato nº 8
Nombre: Pol Navarro
Telefono: 699554433
Años de experiencia: 4
Nivel de catalán: 3
Nivel de excel: 2
Nivel academico: 2
Puntuación: 13.0
Prioridad: Prioritat Alta
------------------------------
Candidato nº 9
Nombre: David Ferrer
Telefono: 677665544
Años de experiencia: 2
Nivel de catalán: 1
Nivel de excel: 1
Nivel academico: 1
Puntuación: 6.0
Prioridad: No prioritari
------------------------------
Candidato nº 10
Nombre: Anna Paredes
Telefono: 633221144
Años de experiencia: 1
Nivel de catalán: 2
Nivel de excel: 1
Nivel academico: 0
Puntuación: 4.5
Prioridad: No prioritari
------------------------------
INFORME FINAL:
Nombre del candidato: Marc Vidal. Contacto: 612443322. Prioridad: Prioritat Alta. Puntuación final: 18.0.
Nombre del candidato: Laura Serra. Contacto: 608112233. Prioridad: Prioritat Alta. Puntuación final: 18.0.
Nombre del candidato: Júlia Romero. Contacto: 677998877. Prioridad: Prioritat Alta. Puntuación final: 15.5.
Nombre del candidato: Pol Navarro. Contacto: 699554433. Prioridad: Prioritat Alta. Puntuación final: 13.0.
Nombre del candidato: Clara Gómez. Contacto: 655221199. Prioridad: Prioritat Alta. Puntuación final: 12.5.
Nombre del candidato: Sergio López. Contacto: 644112211. Prioridad: Candidat adequat. Puntuación final: 10.5.
Nombre del candidato: Marta Ruiz. Contacto: 699887766. Prioridad: Candidat adequat. Puntuación final: 9.0.
Nombre del candidato: David Ferrer. Contacto: 677665544. Prioridad: No prioritari. Puntuación final: 6.0.
Nombre del candidato: Anna Paredes. Contacto: 633221144. Prioridad: No prioritari. Puntuación final: 4.5.

## EJERCICIO 2: SEGMENTACIÓN POR RIESGO DE CESTA DE LA COMPRA

In [259]:
clients = [ 
    {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4}, 
    {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3}, 
    {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2}, 
    {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2}, 
    {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4}, 
    {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1}, 
    {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3}, 
    {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0}, 
    {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1}, 
    {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4} 
]

In [260]:
# import pandas as pd
# datos_clientes = pd.DataFrame(clients)
# datos_clientes
# def obtenir_segment_i_factor(data):
#     f_comportament = { 0:0.1, 1:0.25, 2:0.5, 3:0.75, 4:0.9 }
#     data['factor_comportament'] = data['codi_comportament'].map(f_comportament)
#     return data
# def obtenir_factor_edat(data):
#     f_edat = { '18-25':1.20, '26-40':1.00, '41-60':0.85, '60+':0.70 }
#     data['factor_edat'] = data['grup_edat'].map(f_edat)
#     return data
# def calcular_risc(data):
#     data["risc_final"] = data["factor_edat"] * data["factor_comportament"]
#     return data

La función coge los datos aportados. Se evita el uso de if/else a partir de la coincidencia de la clave del diccionario "f_comportament" y el valor de la llave "codi_comportament" del diccionario que solicita la función ("data_clients"). Por cada cliente ejecuta esa asignación a partir de la coincidencia. 

Lo mismo para missatge.

Devuelve el diccionario con la nueva key:value.

In [261]:
def obtenir_segment_i_factor(data_clients):
    f_comportament = { 0:0.1, 1:0.25, 2:0.5, 3:0.75, 4:0.9 }

    missatge_client = {
    0 : 'Navega però no afegeix productes',
    1 : 'Afegeix productes però no arriba al checkout',
    2 : 'Arriba al checkout però no paga',
    3 : 'Cistella de compra abandonat fa menys de 24 h',
    4 : 'Cistella de compra abandonat fa més de 24 h'}

    for client in data_clients:
        data_clients[client]['factor_comportament'] = f_comportament[data_clients[client]["codi_comportament"]]
        data_clients[client]['missatge'] = missatge_client[data_clients[client]["codi_comportament"]]
    return data_clients

Lo mismo que la función "obtenir_segment_i_factor" pero cambiando al diccionario "f_edat" y la llave "grup_edat"

In [262]:
def obtenir_factor_edat(data_clients):
    f_edat = { '18-25':1.20, '26-40':1.00, '41-60':0.85, '60+':0.70 }
    for client in data_clients:
        data_clients[client]['factor_edat'] = f_edat[data_clients[client]["grup_edat"]]
    return data_clients

Multiplica los valores de la llaves "factor_comporament" y "factor_edat" y crea una nueva llave. Todo es a partir de un for que itera sobre el diccinario.

In [263]:
def calcular_risc(data_clients):
    for client in data_clients:
        data_clients[client]['risc_final'] = data_clients[client]['factor_comportament'] * data_clients[client]['factor_edat'] 
    return data_clients

La ultima funcion para crear un dataframe

In [264]:
def mostrar_resultado(informe_final):
    informe_final_df = pd.DataFrame(informe_final)
    return informe_final_df.T

Se juntan todas las funciones antes creadas.

In [265]:
def main_marketing(data_clients):
    procesar_clients = {}

    for client in data_clients:
        procesar_clients[client['id_client']] = client
    
    clients_factor = obtenir_segment_i_factor(procesar_clients)

    clients_fedat = obtenir_factor_edat(clients_factor)

    clientes_final = calcular_risc(clients_fedat)

    return mostrar_resultado(clientes_final)

main_marketing(clients)

,id_client,nom,edat,grup_edat,codi_comportament,factor_comportament,missatge,factor_edat,risc_final
1,1,Laura Serra,23,18-25,4,0.9,Cistella de compra abandonat fa més de 24 h,1.2,1.08
2,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24 h,1.0,0.75
3,3,Ana López,29,26-40,2,0.5,Arriba al checkout però no paga,1.0,0.5
4,4,Joan Riera,19,18-25,2,0.5,Arriba al checkout però no paga,1.2,0.6
5,5,Mónica Pérez,47,41-60,4,0.9,Cistella de compra abandonat fa més de 24 h,0.85,0.765
6,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,0.85,0.2125
7,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonat fa menys de 24 h,0.7,0.525
8,8,Eva Martín,38,26-40,0,0.1,Navega però no afegeix productes,1.0,0.1
9,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,1.2,0.3
10,10,Núria Costa,33,26-40,4,0.9,Cistella de compra abandonat fa més de 24 h,1.0,0.9

In [266]:
dataframe_clientes = main_marketing(clients)

In [267]:
# "1. Quins clients s'han de contactar primer en una campanya de retargeting?"
dataframe_clientes.sort_values(ascending=False, by="risc_final").head(4)

,id_client,nom,edat,grup_edat,codi_comportament,factor_comportament,missatge,factor_edat,risc_final
1,1,Laura Serra,23,18-25,4,0.9,Cistella de compra abandonat fa més de 24 h,1.2,1.08
10,10,Núria Costa,33,26-40,4,0.9,Cistella de compra abandonat fa més de 24 h,1.0,0.9
5,5,Mónica Pérez,47,41-60,4,0.9,Cistella de compra abandonat fa més de 24 h,0.85,0.765
2,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24 h,1.0,0.75

In [268]:
# "2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?"
dataframe_clientes.sort_values(by=["missatge","risc_final"])

,id_client,nom,edat,grup_edat,codi_comportament,factor_comportament,missatge,factor_edat,risc_final
6,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,0.85,0.2125
9,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,1.2,0.3
3,3,Ana López,29,26-40,2,0.5,Arriba al checkout però no paga,1.0,0.5
4,4,Joan Riera,19,18-25,2,0.5,Arriba al checkout però no paga,1.2,0.6
7,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonat fa menys de 24 h,0.7,0.525
2,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24 h,1.0,0.75
5,5,Mónica Pérez,47,41-60,4,0.9,Cistella de compra abandonat fa més de 24 h,0.85,0.765
10,10,Núria Costa,33,26-40,4,0.9,Cistella de compra abandonat fa més de 24 h,1.0,0.9
1,1,Laura Serra,23,18-25,4,0.9,Cistella de compra abandonat fa més de 24 h,1.2,1.08
8,8,Eva Martín,38,26-40,0,0.1,Navega però no afegeix productes,1.0,0.1

Comparando el comportamiento y grupos de edad, a menor edad mayor es el riesgo final sin importar el comportamiento.

In [269]:
# "3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?"
dataframe_clientes.sort_values(ascending=True, by="risc_final").head(3)

,id_client,nom,edat,grup_edat,codi_comportament,factor_comportament,missatge,factor_edat,risc_final
8,8,Eva Martín,38,26-40,0,0.1,Navega però no afegeix productes,1.0,0.1
6,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,0.85,0.2125
9,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,1.2,0.3

Los usuarios que presentan poco interes presupuestario son los 3 usuarios que menor riesgo tienen ya que hay diferencia en riesgo final respecto al resto de usuarios.

In [270]:
# "4. Quin client seria el més rendible de recuperar?"
nombre_cliente = dataframe_clientes['nom'].sort_index().head(1).iloc[0]
print(f"El usuario más rendible para recuperar es {nombre_cliente}")

El usuario más rendible para recuperar es Laura Serra

# NIVEL 2:

## EJERCICIO 1: GESTIÓN DE RIESGOS Y PRIORIZACIÓN DE CLIENTES
Nota: salida de un DataFrame o diccionario. No especifica cual ni el nombre de funciones.

In [271]:
# Datos de pacientes
pacients = [ 
    "Maria|45|tos, Fiebre Alta, dolor_pecho", 
    "Luis|33|dolor_cabeza,faTiga", 
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos", 
    "Jordi|52|fatiga , tos", 
    "Anna|29|fiebre alta,dolor_cabeza" 
]

In [272]:
# Datos centro médico (nivel de riesgo)
nivells_risc = { 
    "fiebre_alta": 3, 
    "dificultad_respirar": 5, 
    "dolor_pecho": 4, 
    "tos": 1, 
    "fatiga": 1, 
    "dolor_cabeza": 1 
}

La funcion "pacientes_separados_i_normalizados" recibe la lista de pacientes (la que nos han dado). 

Dentro, crea una lista nueva de la cual se irán añadiendo los pacientes y sintomas separados y normalizados.

El primer for coge de la lista_pacientes y por cada paciente separa por "|" y los añade a la nueva lista creada.

El segundo for, con los datos de la nueva lista creada, se asigna a la lista "sintomas" la posicion 2 de cada paciente (que son los sintomas), pero separado por ",". De tal manera, obtengo todos los sintomas y puedo iterar al ser una lista, pero todavía sin normalizarlos.

Para normalizarlos, creo "lista_sintomas" que con el tercer for recibe con append el sintoma normalizado sin espacios, con la primera letra en mayuscula y eliminando los "_". Asigno a la posicion 2 de cada paciente el valor de la lista_sintomas y devuelto el resultado.

In [273]:
def pacientes_separados_i_normalizados(lista_pacientes):
    nueva_lista_pacientes = []
    for paciente in lista_pacientes:
        nueva_lista_pacientes.append(paciente.split("|"))

    for paciente in nueva_lista_pacientes:

        sintomas = paciente[2].split(",")

        lista_sintomas = []

        for sintoma in sintomas:
            lista_sintomas.append(sintoma.strip().capitalize().replace("_", " "))

        paciente[2] = ", ".join(lista_sintomas)

    return nueva_lista_pacientes

Para poder comparar los sintomas de los pacientes vs los riesgos que ha dado la clinica, también se deben normalizar. Se ha aprovechado el codigo de la funcion "pacientes_separados_i_normalizados" para que tengan el mismo aspecto.

In [274]:
def normalizar_riesgo(niveles_riesgo):
    riesgos_normalizados = {}
    for sintoma_riesgo, riesgo in niveles_riesgo.items():
        riesgos_normalizados[sintoma_riesgo.replace("_", " ").capitalize()] = riesgo
    return riesgos_normalizados

La funcion "obtener_riesgo" recibe la lista de pacientes y niveles de riesgo.

Primero creo un diccionario de riesgos (dict_riesgos) para almacenar el paciente y sus niveles de riesgo.

Un for para iterar sobre la lista de pacientes y poder separar los sintomas por ,

El segundo for sobre los sintomas para comparar si el sintoma del paciente está dentro de los niveles de riesgo y obtener su valor. Este valor se agrega a la lista "riesgos_paciente" y se agrega al diccionario final.

In [275]:
def obtener_riesgo(lista_pacientes, niveles_riesgo):
    dict_riesgos = {}

    for paciente in lista_pacientes:
        riesgos_paciente = []

        sintomas = paciente[2].split(",")

        for sintoma_paciente in sintomas:
            sintoma = sintoma_paciente.lstrip()
            if sintoma in niveles_riesgo:
                riesgos_paciente.append(niveles_riesgo[sintoma])

        dict_riesgos[paciente[0]] = riesgos_paciente
            
    return dict_riesgos

Ahora que tengo la lista de pacientes normalizados y una lista con el paciente y los riesgos que tiene, sumo estos riesgos y se los asigno a cada paciente.

In [276]:
def sumar_riesgo(lista_paciente, lista_riesgos):

    for paciente in lista_paciente:

        if paciente[0] in lista_riesgos.keys():

            riesgo_total = sum(lista_riesgos[paciente[0]])
            paciente.append(riesgo_total)

    return lista_paciente

"ordenar_pacientes" como dice su nombre ordena los pacientes por la puntuación de riesgo total que han obtenido. Se realiza esta función con la libreria pandas. Primero se crea un dataframe a partir de lista_pacientes, se renombran las columnas y se ordena por "risc_final"

In [277]:
def ordenar_pacientes(lista_pacientes):
    pacientes_ordenados_df = pd.DataFrame(lista_pacientes)
    pacientes_ordenados_df = pacientes_ordenados_df.rename(columns={
        0: "Nom_pacient", 
        1: "Edat",
        2: "Sintomes",
        3: "Risc_final"}).sort_values(ascending=False, by="Risc_final")
    return pacientes_ordenados_df

main_pacientes se alimenta de todas las funciones y muestra el resultado

In [278]:
def main_pacientes(pacientes, nivel_riesgo):
    lista_pacientes = pacientes_separados_i_normalizados(pacientes)
    niveles_riesgo = normalizar_riesgo(nivel_riesgo)
    lista_riesgos = obtener_riesgo(lista_pacientes,niveles_riesgo)
    riesgo_sumado = sumar_riesgo(lista_pacientes,lista_riesgos)
    return ordenar_pacientes(riesgo_sumado)

In [279]:
main_pacientes(pacients, nivells_risc)

  Nom_pacient Edat                               Sintomes  Risc_final
2        Sara   67  Fiebre alta, Dificultad respirar, Tos           9
0       Maria   45          Tos, Fiebre alta, Dolor pecho           8
4        Anna   29              Fiebre alta, Dolor cabeza           4
1        Luis   33                   Dolor cabeza, Fatiga           2
3       Jordi   52                            Fatiga, Tos           2

## EJERCICIO 2: CLASIFICACIÓN DE CLIENTES DE SEGUROS

Empresa quiere calcular el riesgo de los clientes, precio de poliza estimado y probabilidad de fraude utilizando codigo de comportamiento.

Precio final formula: preu_final = preu_base * ( 1 + edat / 100 ) 

Objetivos:
    - Clasificar cada cliente utilizando niveles seguro sin if/else
    - Añadir: categoria, precio base y probabilidad de fraude
    - Calcular el precio final de poliza con la formula dada
    - Crear DataFrame o diccionario con toda la información
    - Ordenarlo por probabilidad de fraude desdencente y por precio final

Resultado final:

    - Dataframe o diccionario con:
        Nombre, edat, categoria, preu_base, preu_final, probabilitat_frau

    - Apartado de analisis donde se indique:
        Cliente con más probabilidad de fraude
        Quien tiene el preu_final mas alto
        Quien es prioritario de revisar manualmente

In [287]:
clients = [ 
    {"nom": "Ana", "edat": 42, "codi": 0}, 
    {"nom": "Carlos", "edat": 30, "codi": 2}, 
    {"nom": "Isabel", "edat": 55, "codi": 3}, 
    {"nom": "Jorge", "edat": 40, "codi": 1}, 
    {"nom": "Marta", "edat": 28, "codi": 0} 
]

In [ ]:
nivells_seguro = { 
    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01}, 
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05}, 
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15}, 
    3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30} 
}

unificar_cliente_seguro añade toda la información de "nivells_seguro" a "clients" a partir de la coincidencia del valor de "codi" de "clients" y la llave de "nivells_seguro"

In [289]:
def unificar_cliente_seguro(clientes, info_seguro):
    for client in clientes:
        client['categoria'] = info_seguro[client['codi']]["categoria"]
        client['preu_base'] = info_seguro[client['codi']]["preu_base"]
        client['fraude'] = info_seguro[client['codi']]["fraude"]

    return clientes

calcular_precio_final aplica la formula de preu_final por cada cliente

In [283]:
def calcular_precio_final(clientes):
    for client in clientes:
        client["preu_final"] = round(client["preu_base"] * (1 + client["edat"] / 100),ndigits=2)
    return clientes

funcion para crear el dataframe final

In [304]:
def dataframe_final(clientes_datos):
    clientes_datos_df = pd.DataFrame(clientes_datos)
    clientes_datos_df.sort_values(ascending=False, by=["fraude","preu_final"])   
    return clientes_datos_df

Unificadas todas las funciones

In [305]:
def main_seguros(clientes, info_seguro):
    unificados = unificar_cliente_seguro(clientes,info_seguro)

    riesgo_calculado = calcular_precio_final(unificados)

    return dataframe_final(riesgo_calculado)

In [307]:
clientes_seguros_df = main_seguros(clients, nivells_seguro)
clientes_seguros_df

      nom  edat  codi    categoria  preu_base  fraude  preu_final
0     Ana    42     0    Baix risc        120    0.01       170.4
1  Carlos    30     2     Risc alt        350    0.15       455.0
2  Isabel    55     3  Risc crític        500    0.30       775.0
3   Jorge    40     1   Risc mitjà        200    0.05       280.0
4   Marta    28     0    Baix risc        120    0.01       153.6

DATAFRAME DENTRO DE UNA FUNCION Y MAIN

#### Apartado de analisis donde se indique:
Cliente con más probabilidad de fraude:

In [322]:
nombre_cliente = clientes_seguros_df.sort_values(ascending=False, by='fraude').head(1).iloc[0]
nombre_cliente

nom                Isabel
edat                   55
codi                    3
categoria     Risc crític
preu_base             500
fraude                0.3
preu_final          775.0
Name: 2, dtype: object

Quien tiene el preu_final mas alto:

In [323]:
mayor_precio = clientes_seguros_df.sort_values(ascending=False, by='preu_final')
mayor_precio.head(1)

      nom  edat  codi    categoria  preu_base  fraude  preu_final
2  Isabel    55     3  Risc crític        500     0.3       775.0

Quien es prioritario de revisar manualmente: 
    Isabel. Proponerle un tipo de descuento u oferta para que contrate la poliza.

# NIVEL 3:
## EJERCICIO 1: GENERADOR DE CONTRASEÑAS SEGURAS

Crear una función principal y secundarias para:
Generar contraseñas de longitud variable
Decidir si se incluyen: mayúsculas, minúsculas, números y signos especiales (como mínimo uno de cada de los seleccionados)
Contraseñas aleatorias
Devolver la contraseña generada

La función principal debe tener por defecto:
majuscules=True
minuscules=True
numeros=True
signes=False

Importar las librerias:
random : aplica aleatoriedad
string : ofrece las listas de caracteres necesarios y no escribirlos a mano

In [465]:
import random
import string

Obtengo los caracteres si mayusculas, minusculas, numeros y signos son TRUE. El TRUE/FALSE lo defino en el main.
Todos los caracteres se almacenan en la variable caracteres que será devuelta al completar la funcion y serán utilizados para generar la contraseña.

In [466]:
def obtener_caracteres(mayusculas, minusculas, numeros, signos):
    caracteres = ""

    if mayusculas:
        caracteres += string.ascii_uppercase
    if minusculas:
        caracteres += string.ascii_lowercase
    if numeros:
        caracteres += string.digits
    if signos:
        caracteres += string.punctuation

    return caracteres

Obtengo los caracteres si mayusculas, minusculas, numeros, signos son TRUE. El TRUE/FALSE lo defino en el main.
Con random.choice escogo un valor aleatorio de cada categoria y se la agrego a la lista contraseña. Esta funcion genera los caracteres obligatorios y minimos que debe tener la contraseña según el TRUE/FALSE

In [467]:
def generar_obligatorios(mayusculas, minusculas, numeros, signos):
    contraseña = []

    if mayusculas:
        contraseña.append(random.choice(string.ascii_uppercase))
    if minusculas:
        contraseña.append(random.choice(string.ascii_lowercase))
    if numeros:
        contraseña.append(random.choice(string.digits))
    if signos:
        contraseña.append(random.choice(string.punctuation))

    return contraseña

Aqui añado elementos a la contraseña (que ya tenia los caracteres mínimos obligatorios) mientras su longitud sea inferior a la indicada por el usuario.

In [468]:
def completar_contraseña(contraseña, longitud, caracteres):
    while len(contraseña) < longitud:
        contraseña.append(random.choice(caracteres))

    return contraseña

Para que no tenga un orden de mayuscula, minuscula, numero y signo como viene predefinido, mezclo los caracteres seleccionados en la contraseña para que tenga mayor seguridad.

In [469]:
def mezclar_contraseña(contraseña):
    random.shuffle(contraseña)
    return "".join(contraseña)

Teniendo en cuenta si mayusculas, minusculas, numeros y signos estan "activos" para generar la contraseña generará un número (tipos_activos). El número lo compara con la longitud deseada. Si por ejemplo quieres los 4 tipos de caracteres pero indicas longitud 3 dará error.

In [470]:
def validar_longitud(longitud, mayusculas, minusculas, numeros, signos):
    tipos_activos = sum([mayusculas, minusculas, numeros, signos])

    if longitud <= tipos_activos:
        return False

    return True

Este main es diferente al resto porque me ha sido más facil ir construyendo las funciones a partir que hacia el main.

Con la llamada del usuario se necesita la entrada de longitud. Los tipos de caracteres vienen predefinidos.

Primero valido la longitud. Si cumple la condicion pasa, sino muestra error.
Con "obtener_caracteres" le agrego todos caracteres posibles a la variable caracteres (Valga la redundancia)
La funcion generar_obligatorios genera una contraseña con los minimos indispensables. Es una provisional si la longitud es mayor que el número de tipos activados.
Esta contraseña provisional se completa con la funcion "completar_contraseña"
Finalmente se mezcla para dar mayor seguridad y se devuelve la contraseña en un mensaje.

In [1]:
def main_comtraseña(longitud, mayusculas=True, minusculas=True, numeros=True, signos=False):

    if not validar_longitud(longitud, mayusculas, minusculas, numeros,signos):
        return "Longitud insuficiente para los tipos seleccionados"

    caracteres = obtener_caracteres(mayusculas, minusculas, numeros, signos)

    contraseña = generar_obligatorios(mayusculas, minusculas, numeros, signos)

    contraseña = completar_contraseña(contraseña, longitud, caracteres)

    contraseña = mezclar_contraseña(contraseña)

    return f"Tu contraseña es: '{contraseña}'"

In [497]:
main_comtraseña(34)

"Tu contraseña es: 'sK72N01vZAhJhYzwur5clhzyNH9p2NxXfB'"

## EJERCICIO 2: PROCESAMIENTO AUTOMÁTICO DE DATOS DEPORTIVOS

Responder:
- Equipo más goleador
- Equipo más goleado
- Número de goles por equipo
- Clasificación general ordenada.

Salida: 
DataFrame o diccionario + preguntas a responder.

Primero genero una funcion para leer archivos txt. A partir de una ruta del archivo lo lee ('r') con un encoding de UTF8

In [4]:
def leer_archivo_txt(ruta_archivo):
    with open(ruta_archivo, 'r', encoding='UTF8') as archivo_data:
        data_liga = archivo_data.read()
        return data_liga

La función "estructurar_datos" obtiene los datos y crea un diccionario.

Con el for itero sobre el archivo de entrada.

Primero separo el archivo en lineas con un split('\n'). A partir de separarlo por lineas, estas las separo por tabuladores (split('\t')). Esto da una lista de 3 valores: equipo_local, resultado y equipo_visitante.

El resultado lo vuelvo a dividir con un split por '-'. Así separo los goles de cada equipo y ayuda a comparar y saber quien ha ganado, perdido o empatado.

Cada valor se agrega al diccionario que he creado 'dicc_liga' y suma +1 al id para volver a empezar

In [7]:
def estructurar_partidos(datos_liga):
    id = 0
    dicc_liga = {}
    for partido in datos_liga.strip().split('\n'):
        equipo_local, resultado, equipo_visitante = partido.split('\t')
        goles_local, goles_visitante = resultado.split('-')

        dicc_liga[f'partido_{id}'] = { 
            'equipo_local' : equipo_local,
            'goles_local' : goles_local,
            'equipo_visitante' : equipo_visitante,
            'goles_visitante' : goles_visitante}

        id += 1

    return dicc_liga
# estructurar_partidos(data_liga)

El siguiente paso es obtener una lista de los equipos. De tal forma, se puede crear un diccionario con el nombre del equipo como key y dentro un diccionario con nº goles a favor y en contra, victorias, derrotas empates y calcular los puntos.

Aprovechamos que las llaves en los diccionarios de python no se pueden repetir.

Se asume que todos los equipos han sido local y visitante, pero por si acaso, se vuelve a asignar el nombre del equipo visitante al diccionario. Antes solamente se han realizado de los equipos locales.

In [8]:
def obtener_equipos(datos_partidos):
    equipos_liga = {}

    for partido_id in datos_partidos.keys():
        
        equipos_liga[datos_partidos[partido_id]['equipo_local']] = {
            
            'goles_favor' : 0,
            'goles_contra' : 0,
            'partidos_ganados' : 0,
            'partidos_empatados' : 0,
            'partidos_perdidos' : 0,
            'puntos' : 0
            }
        equipos_liga[datos_partidos[partido_id]['equipo_visitante']] = {
            
            'goles_favor' : 0,
            'goles_contra' : 0,
            'partidos_ganados' : 0,
            'partidos_empatados' : 0,
            'partidos_perdidos' : 0,
            'puntos' : 0
            }

    return equipos_liga

# obtener_equipos(estructurar_partidos(data_liga))

Siguiente paso: calcular goles. Con el diccionario de equipos se buscan los goles en el resultado de la funcion estructurar_partidos.

Si el equipo es local se suman a goles_favor los goles del local y los goles del visitante se suman a goles_contra. Si es visitante al reves.

In [9]:
def obtener_goles(equipos, partidos_liga):

    for stats in partidos_liga.values():

        # Ponemos como numeros los goles para sumarlos.
        goles_local = int(stats['goles_local'])
        goles_visitante = int(stats['goles_visitante'])

        # Sumamos los goles dependiendo si es local o visitante
        equipos[stats['equipo_local']]['goles_favor'] += goles_local
        equipos[stats['equipo_visitante']]['goles_contra'] += goles_visitante

    return equipos

Ahora calcular las victorias y puntos.

Con condiciones if/else comparamos goles del local vs visitante. Según el resultado se le añaden puntos y partidos ganados, perdidos o empatados.

In [10]:
def calcular_puntos(equipos, partidos_liga):
    for stats in partidos_liga.values():

            # Ponemos como numeros los goles para compararlos.
            goles_local = int(stats['goles_local'])
            goles_visitante = int(stats['goles_visitante'])

            if goles_local > goles_visitante:
                equipos[stats['equipo_local']]['partidos_ganados'] += 1
                equipos[stats['equipo_local']]['puntos'] += 3
                equipos[stats['equipo_visitante']]['partidos_perdidos'] += 1

            elif goles_local < goles_visitante:
                equipos[stats['equipo_local']]['partidos_perdidos'] += 1
                equipos[stats['equipo_visitante']]['puntos'] += 3
                equipos[stats['equipo_visitante']]['partidos_ganados'] += 1

            else:
                equipos[stats['equipo_local']]['partidos_empatados'] += 1
                equipos[stats['equipo_visitante']]['partidos_empatados'] += 1
                equipos[stats['equipo_local']]['puntos'] += 1
                equipos[stats['equipo_visitante']]['puntos'] += 1

    return equipos

In [13]:
def crear_dataframe(data_final):
    tabla_liga = pd.DataFrame(data_final).T

    return tabla_liga

Funcion de todo junto y devuelve diccionario final

In [14]:
def main_clasificacion(datos_liga):
    archivo_data = leer_archivo_txt(datos_liga)
    partidos = estructurar_partidos(archivo_data)
    equipos = obtener_equipos(partidos)
    goles_partidos = obtener_goles(equipos, partidos)
    liga_completa = calcular_puntos(goles_partidos, partidos)
    return crear_dataframe(liga_completa)

Con pandas creo un dataframe. Para que la tabla salga igual que la que pide el ejercicio, uso df.T que transpone las columnas a filas y viceversa.

In [20]:
tabla_final = main_clasificacion('historic partits.txt')
tabla_final

,goles_favor,goles_contra,partidos_ganados,partidos_empatados,partidos_perdidos,puntos
Manlleu,48,58,16,9,18,57
Granollers,64,58,21,4,24,67
Vilafranca,80,77,20,12,25,72
Terrassa,75,72,20,14,23,74
Olot,71,61,18,10,26,64
Cornellà,74,73,25,7,22,82
Prat,73,33,16,8,21,56
Cerdanyola,60,57,17,5,28,56
Sant Andreu,68,55,17,11,25,62
FC Barcelona,78,47,22,7,15,73
Badalona,58,76,18,14,16,68
Sabadell,87,54,26,7,15,85
Europa,49,44,12,5,16,41
Llagostera,77,82,29,7,20,94
Figueres,62,99,23,10,23,79
RCD Espanyol,57,74,23,11,21,80
Reus Deportiu,58,61,20,8,16,68
Nàstic de Tarragona,66,64,20,8,27,68
Lleida Esportiu,42,87,23,6,23,75
Girona FC,76,63,31,3,13,96

##### Equipo más goleador:

In [25]:
# Máximo equipo goleador con codigo:
equipo_mas_goleador = tabla_final['goles_favor'].idxmax()

print(f"El equipo más goleado es: {equipo_mas_goleador}")

# Top3 con DataFrame:
ranking_goleadores = tabla_final.sort_values(ascending=False,by=['goles_favor'])
ranking_goleadores.head(3)

El equipo más goleado es: Sabadell

,goles_favor,goles_contra,partidos_ganados,partidos_empatados,partidos_perdidos,puntos
Sabadell,87,54,26,7,15,85
Vilafranca,80,77,20,12,25,72
FC Barcelona,78,47,22,7,15,73

##### Equipo más goleado:

In [26]:
# Equipo más goleado con codigo:
equipo_mas_goleado = tabla_final['goles_contra'].idxmax()

print(f"El equipo más goleado es: {equipo_mas_goleado}")

# Top3 con DataFrame:
ranking_goleados = tabla_final.sort_values(ascending=False,by=['goles_contra'])
ranking_goleados.head(3)

El equipo más goleado es: Figueres

,goles_favor,goles_contra,partidos_ganados,partidos_empatados,partidos_perdidos,puntos
Figueres,62,99,23,10,23,79
Lleida Esportiu,42,87,23,6,23,75
Llagostera,77,82,29,7,20,94

##### Número de goles por equipo:

In [35]:
tabla_final['goles_favor']

Manlleu                48
Granollers             64
Vilafranca             80
Terrassa               75
Olot                   71
Cornellà               74
Prat                   73
Cerdanyola             60
Sant Andreu            68
FC Barcelona           78
Badalona               58
Sabadell               87
Europa                 49
Llagostera             77
Figueres               62
RCD Espanyol           57
Reus Deportiu          58
Nàstic de Tarragona    66
Lleida Esportiu        42
Girona FC              76
Name: goles_favor, dtype: int64

##### Clasificación ordenada:

In [40]:
clasificacion = tabla_final.sort_values(ascending=False,by=['puntos','partidos_ganados','goles_favor','partidos_empatados','goles_contra','partidos_perdidos'])
clasificacion

,goles_favor,goles_contra,partidos_ganados,partidos_empatados,partidos_perdidos,puntos
Girona FC,76,63,31,3,13,96
Llagostera,77,82,29,7,20,94
Sabadell,87,54,26,7,15,85
Cornellà,74,73,25,7,22,82
RCD Espanyol,57,74,23,11,21,80
Figueres,62,99,23,10,23,79
Lleida Esportiu,42,87,23,6,23,75
Terrassa,75,72,20,14,23,74
FC Barcelona,78,47,22,7,15,73
Vilafranca,80,77,20,12,25,72
Nàstic de Tarragona,66,64,20,8,27,68
Reus Deportiu,58,61,20,8,16,68
Badalona,58,76,18,14,16,68
Granollers,64,58,21,4,24,67
Olot,71,61,18,10,26,64
Sant Andreu,68,55,17,11,25,62
Manlleu,48,58,16,9,18,57
Cerdanyola,60,57,17,5,28,56
Prat,73,33,16,8,21,56
Europa,49,44,12,5,16,41

In [42]:
top_2 = list(clasificacion.sort_values('puntos', ascending=False).index[:2])

print(f"""
Equip més golejador: {equipo_mas_goleador} 
Equip més golejat: {equipo_mas_goleado}

Classificació final: 
1. {top_2[0]} 
2. {top_2[1]}""")

Equip més golejador: Sabadell
Equip més golejat: Figueres

Classificació final:
1. Girona FC
2. Llagostera