# NIVEL 1: 'EDA' ESTRUCTURADO Y LIMPIEZA DE DATOS

## EJERCICIO 1: EXPLORACIÓN INICIAL DEL DATASET

#### OBJETIVOS:
Con "sprint8_complex.xlsx" responder a las preguntas:

- Cuantas filas y columnas tiene el dataset
- Tipos de datos tiene cada columna
- Hay duplicados?
- Datos coherentes a simple vista?
- Posibles problemas o inconvenientes evidentes

Para responderlas hay que:

- Analizar la dimension del dataset
- Monstrar una muestra representativa de filas
- Revisar los tipos de variables
- Detectar duplicados
- Coherencia de datos
- Identificar y describir posibles problemas iniciales (sin solucionarlos)

Primero de todo instalo openpyxl para poder abrir el archivo xlsx. Pandas tiene la función de abrir un arhivo xlsx, pero necesita las instrucciones de openyxl para hacerlo.

pip install openpyxl

Importación de librerias necesarias para el analisis, limpieza y gestión del dataset

In [47]:
import pandas as pd
import datetime as dt

In [48]:
dataset_s8 = pd.read_excel('sprint8_complex.xlsx')
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Dades de l'enquesta de treballadors 2025  1008 non-null   object
 1   Unnamed: 1                                1007 non-null   str
 2   Unnamed: 2                                1007 non-null   str
 3   Unnamed: 3                                1007 non-null   str
 4   Unnamed: 4                                1007 non-null   str
 5   Unnamed: 5                                1007 non-null   str
 6   Unnamed: 6                                1007 non-null   str
 7   Unnamed: 7                                1007 non-null   str
 8   Unnamed: 8                                1007 non-null   str
 9   Unnamed: 9                                967 non-null    str
 10  Unnamed: 10                               1007 non-null   str
 11  Unnamed: 11                               420 non-null    str
 12  Unnamed: 12                               586 non-null    str
 13  Unnamed: 13                               1006 non-null   str
 14  Unnamed: 14                               1006 non-null   str
 15  Unnamed: 15                               710 non-null    object
 16  Unnamed: 16                               659 non-null    str
 17  Unnamed: 17                               316 non-null    object
 18  Unnamed: 18                               262 non-null    str
 19  Unnamed: 19                               937 non-null    str
dtypes: object(3), str(17)
memory usage: 255.9+ KB

##### Muestra del dataset (20 primeros)

In [49]:
dataset_s8.head(20)

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,6,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,7,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,10,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,11,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,12,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,13,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,14,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,15,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,16,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

##### Número de filas y columnas

In [50]:
print(f"Hay {dataset_s8.shape[0]} filas y {dataset_s8.shape[1]} columnas")

Hay 1010 filas y 20 columnas

##### Tipo de datos y cantidad

In [51]:
dataset_s8.dtypes.value_counts()

str       17
object     3
Name: count, dtype: int64

Hay 17 columnas de tipo str y 3 tipo object

##### Duplicados

El número de duplicados será 0 al tener en cuenta la primera columna. Se ha generado aleatoriamente un número, por lo que no contará como duplicado aún habiendo realmente duplicados.

In [52]:
dataset_s8.duplicated().sum()

np.int64(0)

En cambio, si quitamos la primera columna, si existen 6 filas repetidas. Por lo que aprovechamos para eliminarla, ya que funciona como un indice, pero ya hay un indice en la tabla.

In [53]:
dataset_s8.iloc[:,1:].duplicated().sum()

np.int64(6)

In [54]:
dataset_s8 = dataset_s8.drop(["Dades de l'enquesta de treballadors 2025"], axis=True)

In [55]:
dataset_s8.head(20)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

##### Datos coherentes a simple vista?

Viendo la muestra, se detectan que hay columnas que se pueden juntar (Fills, No_Fills y Nombre_fills). Por el resto, está "bien" estructurado y solamente hay que pulir datos.

##### Futuros problemas

Existen columnas que se pueden juntar (fills, no_fills y nombre_fills)
Codificación de las variables es erronea y las palabras con acentos o signos especiales se ven afectadas.
Estandarización: el salario mensual hay usuarios que lo han puesto en numeros y otros en texto. La columna "dona" deberia ser genero y las variables H/M, pero hay "Dona".
En varias columnas hay números decimales cuando podrían ser enteros (n hijos)

## EJERCICIO 2: VALIDACIÓN BÀSICA DE DATOS Y DECISIONES DE ELIMINACIÓN 

Aspectos a validar:

- ¿Existen identificadores únicos (DNI) para cada persona?
- ¿Qué vas a hacer con las filas duplicadas o registros repetidos?
- ¿Existen valores obligatorios que faltan o información incoherente?
- ¿Detectos formatos incorrectos, errores de codificación o valores imposibles?

Concretamente, tendrás que:

- Corregir posibles problemas de codificación y acentuación en los nombres de las columnas y en los valores de texto, si procede.
- Detectar y eliminar filas duplicadas exactas, indicando cuántos registros se han eliminado.
- Comprobar la unicidad del DNI. En caso de detectar DNIs duplicados, deberás analizar la coherencia de la información asociada y descartar o anular los registros que no sean fiables, justificando claramente la decisión tomada.
- Identificar los campos clave que no deberían contener valores nulos, detectar registros con información insuficiente y eliminar únicamente aquellas filas completamente vacías o con información irrecuperable o no sustituible, explicando por qué no es posible ni razonable imputarlas.

##### DNI como identificadores

Para validar si existen DNIs y demás, es útil renombrar las columnas por su nombre correcto. En el dataframe se encuentran en la fila 3 (indice 2).

In [56]:
dataset_s8.columns = dataset_s8.iloc[2]
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8

Borro las 3 primeras filas porque no tienen datos

In [57]:
dataset_s8 = dataset_s8.drop(dataset_s8.index[0:3])
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Si existen DNIs como identificadores. Ahora compruebo si son únicos o repetidos y los muestro.

In [58]:
dni_duplicado = dataset_s8[dataset_s8.duplicated(['DNI'])]
dni_duplicado.sort_values(by='DNI')

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
607,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 â‚¬",True,False,Grup A,Analista,1,True,50.0,NaN,14.2
757,Oriol,GÃ³mez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 â‚¬,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
761,Oriol,GÃ³mez,16618423V,Espanya,MÃ laga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
762,Oriol,GÃ³mez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 â‚¬",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
695,Alexia,PÃ©rez DÃ­az,49529438G,Espanya,MÃ laga,12.0,10.0,1981.0,Dona,1663â‚¬,NaN,True,Grup C,Cap de projecte,NaN,True,80000,10.7,16.9
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
145,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 â‚¬",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1006,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
107,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
117,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 â‚¬",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
284,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,TÃ¨cnic IT,0.0,True,63574.0,6.0,16.8
916,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1003,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1005,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7

Existen varios DNIs repetidos. En algunos casos solo 2 veces (los que se ven solo una vez en la tabla de arriba), pero otros tienen varias repeticiones y con distinto nombre de usuario.

La eliminación de los DNis repetidos lo haré en el siguiente paso. También los DNIs nulos

##### Registros duplicados y repetidos

Primero, corrijo la codificación por si existen registros duplicados, pero que tengan elementos bien codificados y otros mal. Si existiesen ese tipo de casos, no contarían como duplicados. Se aplica una corrección a todas las columnas.

Se crea una función para obtener un valor. Si el valor no es str lo devuelve.

Mientras hayan correcciones en valor (todo el codigo dentro de While) seguirá funcionando. Cuando no haya más cambios, parará (corregido = True/False)

Se han intrucido cp1252 y latin1 por si alguno no corrige correctamente el valor.

Se le agrega un replace para quitar los "_" de los titulos de las columnas.

Ejecuto un apply para que recorra las columnas y aplique con map la funcion a cada valor.

Solamente haciendo el cp1252 dejaba algún elemento sin corregir.

In [59]:
def corregir_texto(valor):
    if not isinstance(valor, str):
        return valor

    while True:
        corregido = False

        for encoding in ('cp1252', 'latin1'):
            try:
                nuevo = valor.encode(encoding).decode('utf-8')

                if nuevo != valor:
                    valor = nuevo
                    corregido = True
                    break

            except (UnicodeEncodeError, UnicodeDecodeError):
                pass

        if not corregido:
            break

    return valor.replace("_", ' ')

dataset_s8 = dataset_s8.apply(lambda col: col.map(corregir_texto))
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
308,Alexia,Díaz,62221499S,Espanya,Murcia,10.0,3.0,1985.0,H,"1,060 €",NaN,True,Grup A,Analista junior,NaN,True,80000,25.0,21.1
546,Adrià,Gómez Soler,21091816B,Espanya,Bilbao,26.0,8.0,1964.0,NaN,830 €,True,NaN,Grup A,Cap de Projecte,1,False,NaN,NaN,10.9
612,Lucía,Ribera,44426734K,Espanya,Madrid,6.0,6.0,1992.0,Home,2268 euros,True,NaN,Grup C,Tècnic IT,1.0,True,20000,5.1,16.8
982,Carlos,Vila Domènech,18004248E,Espanya,Palma,6.0,4.0,2004.0,F,902 €,NaN,True,Grup A,Data Analyst,NaN,NaN,NaN,NaN,NaN
80,Anna,Roca,64504816D,Espanya,Palma,8.0,8.0,1977.0,H,"2,958 €",NaN,True,Grup D,Responsable de vendes,NaN,False,NaN,NaN,13.0
929,David,Pérez,52298598B,Espanya,Murcia,-5.0,0.0,2019.0,Dona,779 €,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,19.0
656,Laia,Moreno Pujol,65110751A,Espanya,Palma,20.0,4.0,1986.0,H,1117 euros,NaN,NaN,Grup A,Analista,NaN,True,20000,8.4,20.3
50,Aina,Fernández,38468360C,Espanya,Zaragoza,-5.0,0.0,3000.0,Home,1939 euros,True,NaN,Grup C,Analista,1,True,78064.0,NaN,NaN
451,Martina,Romano,49849912M,Itàlia,Napoli,25.0,6.0,1985.0,H,"2,040 €",NaN,True,Grup B,Senior analyst,0.0,False,NaN,NaN,15.1
297,Aina,Roca,87210585T,Espanya,Murcia,-5.0,13.0,2026.0,D,"1,584 €",NaN,True,Grup B,Cap de projecte,NaN,False,NaN,NaN,15.0

Como la codificación se ha hecho después de definir el nombre de las columnas, "Càrrec" está mal escrita por lo que se lanza la función que se ha hecho antes a las columnas

In [60]:
dataset_s8.columns = dataset_s8.columns.map(corregir_texto)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
842,Lucía,López Puig,75610054T,Espanya,Valladolid,19.0,9.0,1965.0,M,2133€,NaN,True,Grup C,Administratiu,0.0,False,NaN,NaN,12.2
762,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
481,Adrià,Álvarez,51706253M,Espanya,Zaragoza,20.0,5.0,1974.0,D,"1,027 €",NaN,True,Grup A,Tècnic IT,NaN,NaN,NaN,NaN,15.0
759,Finn,Schröder,54777065H,Alemanya,München,27.0,9.0,1970.0,D,"1,519 €",True,NaN,Grup B,Senior analyst,3.0,True,77960.0,NaN,8.0
298,Claudia,Roca,22684736L,Espanya,Bilbao,25.0,3.0,1998.0,H,1723 euros,True,NaN,Grup B,Data Analyst,3.0,NaN,NaN,NaN,13.3
278,Noa,Costa Gómez,10969588M,Espanya,Murcia,1.0,2.0,1989.0,D,"1,682 €",NaN,True,Grup B,Analyst,NaN,True,80000,11.4,18.2
690,Alessia,Barbieri,22511284S,Itàlia,Genova,14.0,5.0,1968.0,D,1382€,NaN,True,Grup B,Administratiu,0.0,False,NaN,NaN,16.5
405,David,Vila,71174364G,Espanya,Barcelona,16.0,4.0,1976.0,F,"1,511 €",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,17.7
770,Arthur,Richard,45035917P,França,Nice,11.0,10.0,1959.0,D,1318 euros,True,True,Grup B,Responsable de vendes,0,NaN,NaN,NaN,17.0
545,Lucía,Pujol Muñoz,63442916W,Espanya,A Coruña,20.0,10.0,1958.0,D,889 €,True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,11.6

Ahora compruebo los registros duplicados y los borro.

In [61]:
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1005,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1006,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

Borramos los 4 registros duplicados.
Volvemos a comprobar los duplicados y ya no hay.

In [62]:
dataset_s8 = dataset_s8.drop_duplicates()
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

Tomaré la columna DNI como dato identificador y único de los usuarios. Como se ha comprobado antes, existen DNIs repetidos. Antes de borrarlos, compruebo si hay DNI con mayusculas/minusculas, con espacios y guiones. De esta manera nos aseguramos borrar los adecuados.

In [63]:
dni_espacio = dataset_s8[dataset_s8['DNI'].str.contains(' ')]
dni_espacio

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

In [64]:
dni_guion = dataset_s8[dataset_s8['DNI'].str.contains('-')]
dni_guion

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

No hay DNIs con espacios ni con guiones, por lo que omito la acción de borrarlos DNIs.

Ahora pongo todas las letras de los DNIs en mayuscula y elimino los duplicados.

In [65]:
dataset_s8['DNI'] = dataset_s8['DNI'].str.upper()
dni_num_duplicados = dataset_s8.duplicated(subset=['DNI']).sum()
print(f"Se han eliminado {dni_num_duplicados} DNIs duplicados")
dataset_s8 = dataset_s8.drop_duplicates(subset=['DNI'])
dataset_s8.head(10)

Se han eliminado 11 DNIs duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,Gómez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 €",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,López,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 €",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 €",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Borrados los DNI duplicados, compruebo la longitud de estos. Un DNI español tiene 9 caracteres. En caso de que sean extranjeros con un NIE también son 9 caracteres.

Primero cuento los DNIs que no tienen esa longitud

In [66]:
dni_longitud_mal = dataset_s8[dataset_s8['DNI'].str.len() != 9]
dni_longitud_mal

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
1008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

Sabiendo que hay 2 filas con DNIs con una longitud diferente a 9. Los borro

In [67]:
def longitud_dni(valor):
    return isinstance(valor, str) and len(valor) == 9

dataset_s8 = dataset_s8[dataset_s8['DNI'].apply(longitud_dni)]
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
300,Claudia,Pujol,25917805F,Espanya,A Coruña,24.0,1.0,1977.0,D,951 €,True,NaN,Grup A,Data Analyst,2.0,False,NaN,NaN,14.4
188,Marc,Ramos Gómez,34341456K,Espanya,Valladolid,4.0,4.0,1974.0,H,1734€,True,NaN,Grup B,Analista,1.0,True,80000,4.7,14.4
126,Xavier,Pérez,58376818P,Espanya,Girona,21.0,2.0,1975.0,D,"2,303 €",NaN,True,Grup C,Analista junior,0.0,True,35142.0,10.2,10.2
723,Adrià,Fernández Costa,57657637T,Espanya,Barcelona,20.0,8.0,1993.0,D,860 €,NaN,True,Grup A,Data Analyst,NaN,True,80000,25.0,NaN
958,Jordi,Martínez Gil,13976162W,Espanya,Zaragoza,3.0,8.0,1967.0,D,n/d,True,NaN,Grup A,Cap de Projecte,1.0,NaN,NaN,NaN,-5.0
432,Lucía,Hernández,61268618C,Espanya,Bilbao,24.0,2.0,1995.0,D,"2,290 €",NaN,True,Grup B,Cap de projecte,0.0,True,65950,NaN,15.0
904,Marina,Ruiz Díaz,35484177G,Espanya,Palma,0.0,0.0,2026.0,D,"1,870 €",NaN,True,Grup B,Data Analyst,0.0,True,32217.0,6.9,17.7
135,Léa,Roux,41272427V,França,Nice,1.0,7.0,1958.0,H,997 €,True,NaN,Grup A,Administratiu,4.0,NaN,NaN,NaN,19.0
613,Laia,Domènech López,92586963B,Espanya,Sevilla,14.0,4.0,1962.0,D,1098€,NaN,True,Grup A,Responsable de vendes,0.0,NaN,NaN,NaN,19.1
438,Adrià,Torres,97772249F,Espanya,Palma,5.0,6.0,1998.0,H,"1,148 €",NaN,True,Grup A,Tècnic IT,0.0,NaN,NaN,NaN,17.8

##### Valores nulos

Ante la existencia de los valores nulos, borro las filas que tengan TODAS las columnas con nulos. En este caso solo 1 fila tiene todo nulos.

In [68]:
num_nulos = dataset_s8.isna().all(axis=1).sum()
nulos = dataset_s8.isna().all(axis=1)
dataset_s8 = dataset_s8.dropna(how="all")
print(nulos)
num_nulos

3       False
4       False
5       False
6       False
7       False
        ...
999     False
1000    False
1001    False
1002    False
1004    False
Length: 990, dtype: bool

np.int64(0)

También compruebo si en DNI hay nulos. En este caso no hay.

In [69]:
dni_nulos = dataset_s8[dataset_s8['DNI'].isna()]
dni_nulos

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

##### Formatos incorrectos

In [70]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
585,Marc,Muñoz Vila,38834825Z,Espanya,Palma,15.0,7.0,1994.0,H,"1,105 €",NaN,True,Grup A,Cap de projecte,NaN,True,20000,8.2,19.1
442,Antoine,Richard Dubois,63741103L,França,Toulouse,7.0,12.0,1966.0,D,1729 euros,NaN,True,Grup B,Analista,NaN,NaN,NaN,NaN,14.4
464,Hugo,Bernard,96583583Q,França,Nice,20.0,5.0,1984.0,Home,1207 euros,NaN,True,Grup B,Project lead,0.0,True,80000,4.8,14.6
496,Marina,Ribera,68589370R,Espanya,Palma,11.0,4.0,1980.0,F,"1,385 €",NaN,True,Grup B,Senior analyst,0.0,True,18378.0,NaN,18.6
669,Paul,Laurent,39510761M,França,Bordeaux,11.0,10.0,1993.0,F,746 €,NaN,True,Grup A,Tècnic IT,NaN,True,65983,11.6,-5.0
683,Alessandro,Rossi Marino,64319134R,Itàlia,Napoli,16.0,5.0,1990.0,H,3423 euros,NaN,True,Grup D,Cap de projecte,0.0,True,32431.0,0.5,13.6
552,Alessandro,Rossi,91781029Z,Itàlia,Napoli,24.0,5.0,1997.0,D,"1,649 €",NaN,True,Grup B,Tècnic IT,0.0,False,NaN,NaN,15.4
617,Marta,Roca,58336521F,Espanya,Bilbao,18.0,8.0,1967.0,A,2.706 €,True,NaN,Grup C,Data Analyst,3.0,False,NaN,NaN,12.9
889,Carlos,Navarro,21346274W,Espanya,Valladolid,0.0,0.0,1940.0,Dona,"1,233 €",NaN,True,Grup A,Analista,NaN,NaN,NaN,NaN,13.0
46,Laia,Vidal Pérez,65767881M,Espanya,Palma,24.0,6.0,1976.0,F,"1,923 €",True,NaN,Grup B,Senior analyst,2.0,False,NaN,NaN,19.5

Corregido la codificación con el "cp1252" y "latin1", el formato que falla es el número de hijos, dia, mes y año de nacimiento. Estos parámetros deberían ser números enteros y no decimales (aunque realmente es un texto).

A continuación, busco todos los valores únicos de cada categoria para buscar valores imposibles, si son todos "decimales" u otra opción.

In [71]:
dataset_s8['Nombre fills'].unique()

array(['3.0', '0.0', '4.0', '2.0', nan, '1.0', 0, 1], dtype=object)

In [72]:
dataset_s8['Dia de Naixement'].unique()

<ArrowStringArray>
['23.0',  '8.0', '27.0', '13.0', '29.0',  '1.0', '25.0', '32.0', '24.0',
 '22.0', '10.0', '21.0', '14.0', '19.0', '15.0', '16.0', '11.0', '18.0',
 '28.0',  '9.0',  '3.0',  '2.0',  '0.0', '20.0',  '4.0', '-5.0', '26.0',
 '30.0', '17.0',  '5.0', '12.0',  '6.0',  '7.0', '31.0']
Length: 34, dtype: str

In [73]:
dataset_s8['Mes de Naixement'].unique()

<ArrowStringArray>
[ '3.0', '11.0',  '4.0', '10.0',  '8.0',  '9.0',  '0.0',  '6.0',  '2.0',
  '7.0',  '5.0', '12.0',  '1.0', '99.0', '13.0']
Length: 15, dtype: str

In [74]:
dataset_s8['Any de Naixement'].unique()

<ArrowStringArray>
['1958.0', '1960.0', '1961.0', '1985.0', '1965.0', '1978.0', '1971.0',
 '1962.0', '1963.0', '1940.0', '1974.0', '1973.0', '1980.0', '2004.0',
 '1964.0', '2002.0', '1993.0', '1972.0', '1982.0', '1987.0', '1992.0',
 '1994.0', '1967.0', '1990.0', '3000.0', '2019.0', '1976.0', '2001.0',
 '1997.0', '1984.0', '1977.0', '1988.0', '1995.0', '1981.0', '1983.0',
 '2003.0', '1991.0', '2000.0', '1989.0', '2026.0', '1966.0', '1959.0',
 '1969.0', '1975.0', '1986.0', '1999.0', '1979.0', '1996.0', '1998.0',
 '1970.0', '1968.0']
Length: 51, dtype: str

También las columnas Fills, No Fills y Te_cotxe deberian ser boleanas. Incluso Gènere si consideramos que solamente hay 2 generos. Estas columnas no las modificaremos todavía

Visto los datos únicos de cada columna se procede a cambiarlos de formato. Primero a float al tener escritura con decimales y despues a int64 (evita errores si hay nulos). Modifico las 4 columnas

In [75]:
columnas = ['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Nombre fills']
dataset_s8[columnas] = dataset_s8[columnas].astype(float).astype('Int64')
print(dataset_s8['Dia de Naixement'].unique())
dataset_s8.info()

<IntegerArray>
[23,  8, 27, 13, 29,  1, 25, 32, 24, 22, 10, 21, 14, 19, 15, 16, 11, 18, 28,
  9,  3,  2,  0, 20,  4, -5, 26, 30, 17,  5, 12,  6,  7, 31]
Length: 34, dtype: Int64
<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Dia de Naixement            990 non-null    Int64
 6   Mes de Naixement            990 non-null    Int64
 7   Any de Naixement            990 non-null    Int64
 8   Gènere                      951 non-null    str
 9   Salari mensual              990 non-null    str
 10  Fills                       414 non-null    str
 11  No Fills                    575 non-null    str
 12  Grup Professional           990 non-null    str
 13  Càrrec                      990 non-null    str
 14  Nombre fills                696 non-null    Int64
 15  Te cotxe                    647 non-null    str
 16  Km anuals                   310 non-null    object
 17  Consum mitja L 100km        257 non-null    str
 18  Temperatura mitjana ciutat  923 non-null    str
dtypes: Int64(4), object(1), str(14)
memory usage: 236.7+ KB

El siguiente paso es crear columna de fecha. Hay que unificarlas en una misma columna.

Pandas tiene una función de convertir a fecha y trabajar con ellas. errors='coerce' hace que si hay una fecha imposible (31 de febrero) sea un NA.

Igualmente se comprueba que no existan fechas superiores a la fecha de hoy. En valores únicos de 'Any de Naixement' usuarios han puesto que han nacido en el 3000 (dificil sin viaje en el tiempo) o en el 2019 (bastante ilegal en el 2026 trabajar a esa edad en España).

En la función es posible definir la edad mínima por la que queremos invalidar una fecha. En España la edad legal para trabajar son 16 años.

Con errors='coerce' se declaran nulas las fechas que en:
- 'Dia de Naixement' tenian un 32 o -5
- 'Mes de Naixement' tenian 99 y 13
- 'Any de Naixement' como tal no tenian años imposibles, pero si no se han declarado nulas las fechas con años 3000 o 2019 con el errors se han declarado al ser superiores a la fecha actual.

In [76]:
def crear_fecha(dia, mes, año, edad_minima=16):
    fecha = pd.to_datetime(
        {
            'year': año,
            'month': mes,
            'day': dia
        },
        errors='coerce'
    )

    if edad_minima is not None:
        limite = pd.Timestamp.today() - pd.DateOffset(years=edad_minima)
        fecha[fecha > limite] = pd.NaT

    return fecha

In [77]:
dataset_s8['Data de Naixement'] = crear_fecha(
    dataset_s8['Dia de Naixement'],
    dataset_s8['Mes de Naixement'],
    dataset_s8['Any de Naixement']
)

dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23,3,1958,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3,True,32108.0,25.0,10.1,1958-03-23
4,Marc,Muñoz,48840994W,Espanya,Alacant,8,11,1960,H,"2,718 €",NaN,True,Grup C,Senior analyst,0,True,19496.0,10.4,18.7,1960-11-08
5,Noa,Serra,14308421X,Espanya,Alacant,27,4,1961,D,1358 euros,True,NaN,Grup A,Tècnic IT,4,NaN,NaN,NaN,16.7,1961-04-27
6,Pol,Gil,58586340F,Espanya,Sevilla,13,10,1985,H,"1,478 €",True,NaN,Grup B,Data Analyst,2,False,NaN,NaN,18.3,1985-10-13
7,David,Vila,82070937P,Espanya,Bilbao,29,11,1965,Dona,"1,284 €",NaN,True,Grup B,Administratiu,<NA>,True,NaN,11.8,13.1,1965-11-29
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1,8,1978,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0,NaN,NaN,NaN,19.9,1978-08-01
9,David,Gómez Vila,36998038E,Espanya,Palma,25,9,1971,D,"2,349 €",NaN,True,Grup B,Cap de projecte,<NA>,True,6196.0,10.6,17.8,1971-09-25
10,Carmen,López,47376585K,Espanya,Barcelona,8,9,1962,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4,True,20000,5.9,15.4,1962-09-08
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8,3,1963,D,"1,338 €",NaN,True,Grup B,Analista junior,0,False,NaN,NaN,7.6,1963-03-08
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32,0,1940,H,"1,450 €",True,NaN,Grup A,Senior analyst,4,False,NaN,NaN,20.1,NaT

In [78]:
fechas_invalidas = dataset_s8[dataset_s8['Data de Naixement'] > pd.Timestamp.today()]
fechas_invalidas

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat, Data de Naixement]
Index: []

Elimino las columnas de dia, mes y año ya que puedo obtener los mismos datos validos en la columna de fecha de aniversario.

In [79]:
dataset_s8 = dataset_s8.drop(['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement'], axis=1)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
971,David,García,77176147R,Espanya,Bilbao,Dona,"1,762 €",NaN,True,Grup B,Analista,0,True,65950,0.5,13.1,1981-06-15
45,Laia,Puig,57287718F,Espanya,Girona,D,1438€,NaN,True,Grup A,Senior analyst,0,NaN,NaN,NaN,12.9,1976-04-20
224,Chiara,Esposito,62156850K,Itàlia,Roma,NaN,"1,893 €",True,True,Grup B,Responsable de vendes,1,True,80000,25.0,15.1,1994-11-27
981,Giulia,Conti Russo,72192924S,Itàlia,Bologna,H,1931 euros,NaN,True,Grup C,Administratiu,0,NaN,NaN,NaN,15.0,1990-10-29
806,Pau,Álvarez López,59997347Q,Espanya,A Coruña,H,"1,343 €",True,True,Grup A,Cap de projecte,0,False,NaN,NaN,NaN,2003-02-03
281,Víctor,García,89551741H,Espanya,València,F,"1,778 €",True,NaN,Grup B,Administratiu,2,NaN,NaN,NaN,16.6,1973-12-15
896,Marina,Ruiz,87027101V,Espanya,Girona,NaN,1549 euros,True,NaN,Grup B,Senior analyst,2,True,80000,6.8,11.3,1960-01-09
641,Sergio,López Pujol,80421269J,Espanya,Màlaga,Dona,1030 euros,NaN,True,Grup A,Tècnic IT,0,False,NaN,NaN,15.1,1983-09-02
20,Sigrid,Olsen,70604045C,Noruega,Bergen,D,"1,385 €",True,True,Grup A,Admin.,0,True,80000,25.0,8.8,1964-06-19
575,Sergio,Roca López,31236454Q,Espanya,A Coruña,H,1035€,True,NaN,Grup A,Analista junior,1,False,NaN,NaN,17.3,1993-02-18

## EJERCICIO 3: TRANSFORMACIONES NECESARIAS Y PREPARACIÓN DEL DATASET

Aspectos a revisar y transformar:

- ¿Los valores categóricos están normalizados y son consistentes?
- ¿Los valores nulos son coherentes con la información disponible?
- ¿Existe redundancia de variables que pueda generar problemas analíticos?
- ¿Las variables contextuales (como temperatura, salario) están completas y preparadas para el análisis?

Concretamente, tendrás que:

- Normalizar los valores categóricos para evitar ambigüedades (por ejemplo, valores que representan el mismo concepto pero están escritos de forma diferente).
- Revisar la coherencia de los valores nulos, asegurando que:
Las personas con kilometraje anual y consumo medio asociados disponen de coche. En los casos en que conste consumo medio pero no kilometraje anual, será necesario decidir cómo resolver esta incoherencia de forma justificada.
Las personas que tienen un valor en el número de hijos tienen efectivamente hijos.
- Unificar la información sobre hijos en una única columna, ya que mantener varias columnas con información complementaria no es óptimo y puede generar problemas analíticos (redundancia o multicolinealidad).
- Validar la temperatura media. En caso de que esa información falte, deberás imputarla utilizando un criterio razonable (por ciudad o por un nivel superior justificado).
- Revisar e imputar los salarios faltantes, aplicando criterios analíticos coherentes (como cargo, grupo profesional, ciudad, género o franja de edad).

In [80]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
473,Marina,Martínez,35427499N,Espanya,Màlaga,D,"1,151 €",NaN,True,Grup A,Data Analyst,0,True,16390.0,12.1,17.3,1985-04-10
486,Marc,Soler,29016797K,Espanya,Palma,F,"1,399 €",NaN,True,Grup A,Senior analyst,<NA>,NaN,NaN,NaN,15.9,1998-01-06
498,Anna,Hernández Gil,65141186E,Espanya,Las Palmas de Gran Canaria,D,"1,428 €",NaN,True,Grup B,Responsable de vendes,0,NaN,NaN,NaN,23.4,1961-06-29
606,Jordi,Costa Gil,49115199A,Espanya,Palma,H,"1,075 €",True,NaN,Grup A,Administratiu,2,NaN,NaN,NaN,42.0,1965-05-30
428,Xavier,Sánchez Gil,37111862V,Espanya,Palma,D,1753€,NaN,True,Grup B,Data Analyst,<NA>,False,NaN,NaN,20.4,1977-12-16
535,Chloé,Michel,18365183X,França,Marseille,H,1380€,NaN,True,Grup B,Analista junior,<NA>,False,NaN,NaN,15.1,1986-11-23
239,Leon,Müller,92189839F,Alemanya,Hamburg,H,3552€,NaN,True,Grup D,Senior analyst,<NA>,False,NaN,NaN,6.6,1975-10-19
343,Alba,Hernández,69886480C,Espanya,Barcelona,Dona,3041€,NaN,True,Grup C,Senior analyst,<NA>,False,NaN,NaN,17.0,1967-12-13
781,Marta,Puig,51373866L,Espanya,A Coruña,H,1833€,True,NaN,Grup B,Data analyst,3,True,-50.0,NaN,13.8,NaT
977,Riccardo,Colombo Rizzo,45376362C,Itàlia,Roma,H,"1,288 €",NaN,True,Grup A,Responsable de vendes,0,False,NaN,NaN,-10.0,1981-07-26

##### Valores categóricos

Tomo como valores categóricos "Gènere", "Te_cotxe", "Grup Professional" y "Càrrec". Compruebo los valores únicos de cada uno.

Gènere tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo. Después cambiar formato a boolean

In [81]:
dataset_s8['Gènere'].unique()

<ArrowStringArray>
['Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A']
Length: 9, dtype: str

Te cotxe es correcto. Solo hay que cambiar formato a boolean

In [82]:
dataset_s8["Te cotxe"].unique()

<ArrowStringArray>
['True', nan, 'False']
Length: 3, dtype: str

Grup Professional se deja así tal cual. Las categorias están bien escritas.

In [83]:
dataset_s8['Grup Professional'].unique()

<ArrowStringArray>
['Grup B', 'Grup C', 'Grup A', 'Grup D']
Length: 4, dtype: str

Càrrec tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo.

Una vez estandarizado se comparará vs Grup Professional si todas coinciden o hay discrepancias

In [84]:
dataset_s8['Càrrec'].unique()

<ArrowStringArray>
[      'Cap de projecte',        'Senior analyst',             'Tècnic IT',
          'Data Analyst',         'Administratiu', 'Responsable de vendes',
       'Analista junior',          'Project lead',                'Admin.',
               'Analyst',              'Analista',          'Data analyst',
       'Cap de Projecte']
Length: 13, dtype: str

##### Valores categóricos: Gènere

Antes de comenzar la estandarización de la columba Gènere, cuento cuantas filas hay nulas en la columna y cuantos registros hay por cada género especificado por el usuario. De este modo puedo comprobar después que se haya completado la estandarización completamente.

In [94]:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')
dataset_s8.groupby('Gènere').size()

Hay: 39 filas de género nulas y 951 no nulas

Gènere
A        24
D       320
Dona    118
F       107
H       274
Home     51
M        34
NC       23
dtype: int64

Creo un diccionario para estandarizar los valores de 'Gènere'. De 'Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A' no se modificarán los nan, 'NC' y 'A'. Al hacer la transformación se borrarán. Los demás se asigna a 'Dona' o 'Home'.

No nulos hay 951 que se le restarán las 47 de 'A' y 'NC'. Quedarán 904 no nulos y 86 nulos si no falla la calculadora.

In [99]:
dicc_genere = {
    'Dona':'Dona', 
    'H': 'Home', 
    'D': 'Dona', 
    'F': 'Dona', 
    'Home': 'Home', 
    'M': 'Home', 
}

def definir_genero(genero):
    for categoria in dicc_genere:
        if genero == categoria:
            return dicc_genere[categoria]

dataset_s8['Gènere'] = dataset_s8['Gènere'].apply(definir_genero)

#Aprovecho el mismo código de antes:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')


dataset_s8.groupby('Gènere').size()

Hay: 86 filas de género nulas y 904 no nulas

Gènere
Dona    545
Home    359
dtype: int64

##### Valores categóricos: Té cotxe

Para la columna 'Té cotxe' el objetivo es convertirla en tipo boolean para que 0 = no coche (False) y 1 = si coche (True). Valores nulos se mantendrán para no influir en la estafística. Igualmente se comprobará si hay valor en kilometros. Si tiene registro de kilometros se pondrá como True