# NIVEL 1: 'EDA' ESTRUCTURADO Y LIMPIEZA DE DATOS

## EJERCICIO 1: EXPLORACIÓN INICIAL DEL DATASET

#### OBJETIVOS:
Con "sprint8_complex.xlsx" responder a las preguntas:

- Cuantas filas y columnas tiene el dataset
- Tipos de datos tiene cada columna
- Hay duplicados?
- Datos coherentes a simple vista?
- Posibles problemas o inconvenientes evidentes

Para responderlas hay que:

- Analizar la dimension del dataset
- Monstrar una muestra representativa de filas
- Revisar los tipos de variables
- Detectar duplicados
- Coherencia de datos
- Identificar y describir posibles problemas iniciales (sin solucionarlos)

Primero de todo instalo openpyxl para poder abrir el archivo xlsx. Pandas tiene la función de abrir un arhivo xlsx, pero necesita las instrucciones de openyxl para hacerlo.

pip install openpyxl

Importación de librerias necesarias para el analisis, limpieza y gestión del dataset

In [99]:
import pandas as pd
import datetime as dt

In [100]:
dataset_s8 = pd.read_excel('sprint8_complex.xlsx')
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Dades de l'enquesta de treballadors 2025  1008 non-null   object
 1   Unnamed: 1                                1007 non-null   str
 2   Unnamed: 2                                1007 non-null   str
 3   Unnamed: 3                                1007 non-null   str
 4   Unnamed: 4                                1007 non-null   str
 5   Unnamed: 5                                1007 non-null   str
 6   Unnamed: 6                                1007 non-null   str
 7   Unnamed: 7                                1007 non-null   str
 8   Unnamed: 8                                1007 non-null   str
 9   Unnamed: 9                                967 non-null    str
 10  Unnamed: 10                               1007 non-null   str
 11  Unnamed: 11                               420 non-null    str
 12  Unnamed: 12                               586 non-null    str
 13  Unnamed: 13                               1006 non-null   str
 14  Unnamed: 14                               1006 non-null   str
 15  Unnamed: 15                               710 non-null    object
 16  Unnamed: 16                               659 non-null    str
 17  Unnamed: 17                               316 non-null    object
 18  Unnamed: 18                               262 non-null    str
 19  Unnamed: 19                               937 non-null    str
dtypes: object(3), str(17)
memory usage: 255.9+ KB

##### Muestra del dataset (20 primeros)

In [101]:
dataset_s8.head(20)

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,6,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,7,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,10,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,11,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,12,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,13,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,14,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,15,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,16,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

##### Número de filas y columnas

In [102]:
print(f"Hay {dataset_s8.shape[0]} filas y {dataset_s8.shape[1]} columnas")

Hay 1010 filas y 20 columnas

##### Tipo de datos y cantidad

In [103]:
dataset_s8.dtypes.value_counts()

str       17
object     3
Name: count, dtype: int64

Hay 17 columnas de tipo str y 3 tipo object

##### Duplicados

El número de duplicados será 0 al tener en cuenta la primera columna. Se ha generado aleatoriamente un número, por lo que no contará como duplicado aún habiendo realmente duplicados.

In [104]:
dataset_s8.duplicated().sum()

np.int64(0)

En cambio, si quitamos la primera columna, si existen 6 filas repetidas. Por lo que aprovechamos para eliminarla, ya que funciona como un indice, pero ya hay un indice en la tabla.

In [105]:
dataset_s8.iloc[:,1:].duplicated().sum()

np.int64(6)

In [106]:
dataset_s8 = dataset_s8.drop(["Dades de l'enquesta de treballadors 2025"], axis=True)

In [107]:
dataset_s8.head(20)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

##### Datos coherentes a simple vista?

Viendo la muestra, se detectan que hay columnas que se pueden juntar (Fills, No_Fills y Nombre_fills). Por el resto, está "bien" estructurado y solamente hay que pulir datos.

##### Futuros problemas

Existen columnas que se pueden juntar (fills, no_fills y nombre_fills)
Codificación de las variables es erronea y las palabras con acentos o signos especiales se ven afectadas.
Estandarización: el salario mensual hay usuarios que lo han puesto en numeros y otros en texto. La columna "dona" deberia ser genero y las variables H/M, pero hay "Dona".
En varias columnas hay números decimales cuando podrían ser enteros (n hijos)

## EJERCICIO 2: VALIDACIÓN BÀSICA DE DATOS Y DECISIONES DE ELIMINACIÓN 

Aspectos a validar:

- ¿Existen identificadores únicos (DNI) para cada persona?
- ¿Qué vas a hacer con las filas duplicadas o registros repetidos?
- ¿Existen valores obligatorios que faltan o información incoherente?
- ¿Detectos formatos incorrectos, errores de codificación o valores imposibles?

Concretamente, tendrás que:

- Corregir posibles problemas de codificación y acentuación en los nombres de las columnas y en los valores de texto, si procede.
- Detectar y eliminar filas duplicadas exactas, indicando cuántos registros se han eliminado.
- Comprobar la unicidad del DNI. En caso de detectar DNIs duplicados, deberás analizar la coherencia de la información asociada y descartar o anular los registros que no sean fiables, justificando claramente la decisión tomada.
- Identificar los campos clave que no deberían contener valores nulos, detectar registros con información insuficiente y eliminar únicamente aquellas filas completamente vacías o con información irrecuperable o no sustituible, explicando por qué no es posible ni razonable imputarlas.

##### DNI como identificadores

Para validar si existen DNIs y demás, es útil renombrar las columnas por su nombre correcto. En el dataframe se encuentran en la fila 3 (indice 2).

In [108]:
dataset_s8.columns = dataset_s8.iloc[2]
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8

Borro las 3 primeras filas porque no tienen datos

In [109]:
dataset_s8 = dataset_s8.drop(dataset_s8.index[0:3])
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Si existen DNIs como identificadores. Ahora compruebo si son únicos o repetidos y los muestro.

In [110]:
dni_duplicado = dataset_s8[dataset_s8.duplicated(['DNI'])]
dni_duplicado.sort_values(by='DNI')

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
607,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 â‚¬",True,False,Grup A,Analista,1,True,50.0,NaN,14.2
757,Oriol,GÃ³mez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 â‚¬,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
761,Oriol,GÃ³mez,16618423V,Espanya,MÃ laga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
762,Oriol,GÃ³mez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 â‚¬",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
695,Alexia,PÃ©rez DÃ­az,49529438G,Espanya,MÃ laga,12.0,10.0,1981.0,Dona,1663â‚¬,NaN,True,Grup C,Cap de projecte,NaN,True,80000,10.7,16.9
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
145,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 â‚¬",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1006,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
107,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
117,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 â‚¬",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
284,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,TÃ¨cnic IT,0.0,True,63574.0,6.0,16.8
916,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1003,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1005,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7

Existen varios DNIs repetidos. En algunos casos solo 2 veces (los que se ven solo una vez en la tabla de arriba), pero otros tienen varias repeticiones y con distinto nombre de usuario.

La eliminación de los DNis repetidos lo haré en el siguiente paso. También los DNIs nulos

##### Registros duplicados y repetidos

Primero, corrijo la codificación por si existen registros duplicados, pero que tengan elementos bien codificados y otros mal. Si existiesen ese tipo de casos, no contarían como duplicados. Se aplica una corrección a todas las columnas.

Se crea una función para obtener un valor. Si el valor no es str lo devuelve.

Mientras hayan correcciones en valor (todo el codigo dentro de While) seguirá funcionando. Cuando no haya más cambios, parará (corregido = True/False)

Se han intrucido cp1252 y latin1 por si alguno no corrige correctamente el valor.

Se le agrega un replace para quitar los "_" de los titulos de las columnas.

Ejecuto un apply para que recorra las columnas y aplique con map la funcion a cada valor.

Solamente haciendo el cp1252 dejaba algún elemento sin corregir.

In [111]:
def corregir_texto(valor):
    if not isinstance(valor, str):
        return valor

    while True:
        corregido = False

        for encoding in ('cp1252', 'latin1'):
            try:
                nuevo = valor.encode(encoding).decode('utf-8')

                if nuevo != valor:
                    valor = nuevo
                    corregido = True
                    break

            except (UnicodeEncodeError, UnicodeDecodeError):
                pass

        if not corregido:
            break

    return valor.replace("_", ' ')

dataset_s8 = dataset_s8.apply(lambda col: col.map(corregir_texto))
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
311,Hugo,Fournier Michel,81918425Y,França,Nantes,27.0,2.0,1998.0,Dona,1280 euros,NaN,True,Grup A,Cap de projecte,0.0,NaN,NaN,NaN,12.8
944,Elena,Esposito,19180850S,Itàlia,Bologna,26.0,9.0,1968.0,D,830 €,NaN,True,Grup A,Analista,0.0,False,NaN,NaN,16.3
579,Carlos,Sánchez,65717519Y,Espanya,Tarragona,11.0,12.0,1980.0,NaN,"1,469 €",True,NaN,Grup A,Senior analyst,1.0,True,65950,NaN,15.8
440,Luca,Bianchi Rossi,24228398K,Itàlia,Napoli,2.0,6.0,1985.0,Dona,"2,245 €",True,NaN,Grup C,Analista junior,1.0,True,54623.0,25.0,16.6
980,Anna,Soler,89365865K,Espanya,Zaragoza,13.0,9.0,1991.0,F,"1,222 €",True,NaN,Grup A,Senior analyst,1.0,True,97162.0,NaN,15.7
776,Pol,Soler Sánchez,34254080R,Espanya,Tarragona,30.0,3.0,1964.0,H,765 €,True,NaN,Grup A,Analista junior,1,True,116654.0,0.5,13.5
872,Nil,Fernández Ramos,34385885F,Espanya,Màlaga,11.0,11.0,1995.0,D,823 €,NaN,True,Grup A,Analista junior,NaN,False,NaN,NaN,16.9
863,Thomas,David,27341287F,França,Bordeaux,8.0,6.0,1972.0,Dona,n/d,True,NaN,Grup A,Tècnic IT,1.0,False,NaN,NaN,16.2
496,Marina,Ribera,68589370R,Espanya,Palma,11.0,4.0,1980.0,F,"1,385 €",NaN,True,Grup B,Senior analyst,0.0,True,18378.0,NaN,18.6
205,Sara,Torres,88762521T,Espanya,Zaragoza,15.0,11.0,1987.0,D,1734 euros,True,NaN,Grup B,Project lead,2.0,False,NaN,NaN,12.1

Como la codificación se ha hecho después de definir el nombre de las columnas, "Càrrec" está mal escrita por lo que se lanza la función que se ha hecho antes a las columnas

In [112]:
dataset_s8.columns = dataset_s8.columns.map(corregir_texto)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
441,Sarah,Garcia,18053170C,França,Lille,5.0,2.0,1976.0,D,"1,906 €",True,NaN,Grup C,Analista,4.0,False,NaN,NaN,12.1
276,Giorgio,Esposito,24271532A,Itàlia,Roma,27.0,2.0,1995.0,Dona,"1,895 €",True,NaN,Grup B,Responsable de vendes,3.0,NaN,NaN,NaN,17.1
323,Nil,Ferrer,48949039P,Espanya,Murcia,1.0,3.0,1984.0,D,"1,730 €",True,True,Grup B,Senior analyst,0.0,True,87108.0,25.0,18.9
45,Laia,Puig,57287718F,Espanya,Girona,20.0,4.0,1976.0,D,1438€,NaN,True,Grup A,Senior analyst,0.0,NaN,NaN,NaN,12.9
125,Emilia,Klein,83458776H,Alemanya,Düsseldorf,11.0,5.0,1978.0,Dona,1058 euros,NaN,True,Grup A,Cap de Projecte,0.0,False,NaN,NaN,14.8
712,Pau,Casals Costa,73889311E,Espanya,Madrid,2.0,4.0,1998.0,A,3600€,True,NaN,Grup D,Cap de projecte,4.0,True,28988.0,25.0,16.9
140,Jordi,Álvarez,47561442Z,Espanya,Palma,9.0,3.0,1971.0,M,3445€,NaN,NaN,Grup D,Data Analyst,NaN,False,NaN,NaN,19.3
432,Lucía,Hernández,61268618C,Espanya,Bilbao,24.0,2.0,1995.0,D,"2,290 €",NaN,True,Grup B,Cap de projecte,0.0,True,65950,NaN,15.0
186,Simone,Esposito Greco,63031203K,Itàlia,Firenze,13.0,8.0,1976.0,H,"2,266 €",True,NaN,Grup C,Analista,1,NaN,NaN,NaN,16.3
527,Clara,Martin Michel,92557389B,França,Lille,32.0,99.0,2019.0,F,1137 euros,NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,11.3

Ahora compruebo los registros duplicados y los borro.

In [113]:
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1005,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1006,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

Borramos los 4 registros duplicados.
Volvemos a comprobar los duplicados y ya no hay.

In [114]:
dataset_s8 = dataset_s8.drop_duplicates()
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

Tomaré la columna DNI como dato identificador y único de los usuarios. Como se ha comprobado antes, existen DNIs repetidos. Antes de borrarlos, compruebo si hay DNI con mayusculas/minusculas, con espacios y guiones. De esta manera nos aseguramos borrar los adecuados.

In [115]:
dni_espacio = dataset_s8[dataset_s8['DNI'].str.contains(' ')]
dni_espacio

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

In [116]:
dni_guion = dataset_s8[dataset_s8['DNI'].str.contains('-')]
dni_guion

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

No hay DNIs con espacios ni con guiones, por lo que omito la acción de borrarlos DNIs.

Ahora pongo todas las letras de los DNIs en mayuscula y elimino los duplicados.

In [117]:
dataset_s8['DNI'] = dataset_s8['DNI'].str.upper()
dni_num_duplicados = dataset_s8.duplicated(subset=['DNI']).sum()
print(f"Se han eliminado {dni_num_duplicados} DNIs duplicados")
dataset_s8 = dataset_s8.drop_duplicates(subset=['DNI'])
dataset_s8.head(10)

Se han eliminado 11 DNIs duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,Gómez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 €",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,López,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 €",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 €",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Borrados los DNI duplicados, compruebo la longitud de estos. Un DNI español tiene 9 caracteres. En caso de que sean extranjeros con un NIE también son 9 caracteres.

Primero cuento los DNIs que no tienen esa longitud

In [118]:
dni_longitud_mal = dataset_s8[dataset_s8['DNI'].str.len() != 9]
dni_longitud_mal

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
1008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

Sabiendo que hay 2 filas con DNIs con una longitud diferente a 9. Los borro

In [119]:
def longitud_dni(valor):
    return isinstance(valor, str) and len(valor) == 9

dataset_s8 = dataset_s8[dataset_s8['DNI'].apply(longitud_dni)]
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
672,Oriol,García,70699404E,Espanya,Alacant,3.0,12.0,1999.0,H,906 €,NaN,True,Grup A,Analista,NaN,True,NaN,NaN,21.4
666,Paul,Roux Garcia,49119248C,França,Nantes,24.0,2.0,1969.0,F,"1,432 €",NaN,True,Grup A,Senior analyst,NaN,False,NaN,NaN,9.0
821,Manon,Martin,94699404Q,França,Toulouse,15.0,6.0,2002.0,Home,"2,234 €",True,NaN,Grup C,Data Analyst,1,True,80000,5.8,13.8
861,Joana,Casals Puig,94227868E,Espanya,A Coruña,26.0,9.0,1983.0,Home,726 €,True,NaN,Grup A,Analista junior,1,NaN,NaN,NaN,11.9
318,Xavier,Casals,58701586K,Espanya,Girona,21.0,5.0,1982.0,D,845 €,NaN,True,Grup A,Analista junior,NaN,False,NaN,NaN,-5.0
663,Valentina,Ferrari Rossi,29537240C,Itàlia,Bologna,23.0,2.0,1993.0,D,"1,478 €",NaN,True,Grup B,Analista,NaN,NaN,NaN,NaN,12.7
221,Hugo,Moreno,96513378G,Espanya,Valladolid,32.0,0.0,2026.0,D,1471 euros,NaN,True,Grup B,Analista junior,NaN,True,81945.0,0.5,14.6
693,Noa,Vila Ruiz,45616810T,Espanya,Alacant,13.0,5.0,1995.0,Dona,"1,724 €",True,NaN,Grup B,Senior analyst,1.0,False,NaN,NaN,38.0
120,Irene,Romero Roca,32396311S,Espanya,A Coruña,18.0,3.0,1999.0,Home,"2,901 €",True,NaN,Grup C,Cap de projecte,1.0,True,50000,0.5,19.3
817,Sara,Ramos,83864238C,Espanya,Madrid,26.0,7.0,1975.0,Home,"2,491 €",NaN,NaN,Grup C,Data Analyst,0.0,True,-50.0,NaN,42.0

##### Valores nulos

Ante la existencia de los valores nulos, borro las filas que tengan TODAS las columnas con nulos. En este caso solo 1 fila tiene todo nulos.

In [120]:
num_nulos = dataset_s8.isna().all(axis=1).sum()
nulos = dataset_s8.isna().all(axis=1)
dataset_s8 = dataset_s8.dropna(how="all")
print(nulos)
num_nulos

3       False
4       False
5       False
6       False
7       False
        ...
999     False
1000    False
1001    False
1002    False
1004    False
Length: 990, dtype: bool

np.int64(0)

También compruebo si en DNI hay nulos. En este caso no hay.

In [121]:
dni_nulos = dataset_s8[dataset_s8['DNI'].isna()]
dni_nulos

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

##### Formatos incorrectos

In [122]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
65,Felix,Wagner Weber,82446804Q,Alemanya,Stuttgart,17.0,2.0,1976.0,D,1251€,NaN,True,Grup A,Analista,0.0,NaN,NaN,NaN,10.2
201,Julien,Petit,16986408M,França,Marseille,23.0,10.0,1993.0,D,722 euros,NaN,NaN,Grup A,Cap de Projecte,NaN,False,NaN,NaN,10.4
370,Marina,Pérez,60760544E,Espanya,Madrid,18.0,4.0,1970.0,Home,"1,021 €",True,NaN,Grup A,Administratiu,1,NaN,NaN,NaN,14.4
429,Xavier,Ramos,27305260D,Espanya,Las Palmas de Gran Canaria,31.0,12.0,1975.0,H,845 €,NaN,True,Grup A,Analista,NaN,NaN,NaN,NaN,NaN
108,Nil,Gómez,82553061X,Espanya,Madrid,29.0,11.0,1982.0,D,2138€,NaN,NaN,Grup C,Tècnic IT,NaN,False,NaN,NaN,15.0
158,Víctor,Díaz,60529679B,Espanya,A Coruña,29.0,7.0,1975.0,Dona,"1,654 €",True,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,-5.0
351,Marie,Moreau,93041052V,França,Paris,7.0,2.0,1993.0,D,2180€,NaN,True,Grup C,Analyst,0.0,NaN,NaN,NaN,14.0
873,Felix,Müller,63102334D,Alemanya,Frankfurt,15.0,9.0,1984.0,NaN,"2,025 €",NaN,True,Grup B,Cap de projecte,NaN,True,20000,8.9,10.2
435,David,Serra Gil,49827566A,Espanya,Barcelona,18.0,2.0,1960.0,H,"1,947 €",True,NaN,Grup C,Tècnic IT,3.0,NaN,NaN,NaN,14.6
919,Marta,Roca Pujol,49701147A,Espanya,Tarragona,24.0,9.0,1986.0,F,1043 euros,NaN,True,Grup A,Responsable de vendes,0.0,NaN,NaN,NaN,16.0

Corregido la codificación con el "cp1252" y "latin1", el formato que falla es el número de hijos, dia, mes y año de nacimiento. Estos parámetros deberían ser números enteros y no decimales (aunque realmente es un texto).

A continuación, busco todos los valores únicos de cada categoria para buscar valores imposibles, si son todos "decimales" u otra opción.

In [123]:
dataset_s8['Nombre fills'].unique()

array(['3.0', '0.0', '4.0', '2.0', nan, '1.0', 0, 1], dtype=object)

In [124]:
dataset_s8['Dia de Naixement'].unique()

<ArrowStringArray>
['23.0',  '8.0', '27.0', '13.0', '29.0',  '1.0', '25.0', '32.0', '24.0',
 '22.0', '10.0', '21.0', '14.0', '19.0', '15.0', '16.0', '11.0', '18.0',
 '28.0',  '9.0',  '3.0',  '2.0',  '0.0', '20.0',  '4.0', '-5.0', '26.0',
 '30.0', '17.0',  '5.0', '12.0',  '6.0',  '7.0', '31.0']
Length: 34, dtype: str

In [125]:
dataset_s8['Mes de Naixement'].unique()

<ArrowStringArray>
[ '3.0', '11.0',  '4.0', '10.0',  '8.0',  '9.0',  '0.0',  '6.0',  '2.0',
  '7.0',  '5.0', '12.0',  '1.0', '99.0', '13.0']
Length: 15, dtype: str

In [126]:
dataset_s8['Any de Naixement'].unique()

<ArrowStringArray>
['1958.0', '1960.0', '1961.0', '1985.0', '1965.0', '1978.0', '1971.0',
 '1962.0', '1963.0', '1940.0', '1974.0', '1973.0', '1980.0', '2004.0',
 '1964.0', '2002.0', '1993.0', '1972.0', '1982.0', '1987.0', '1992.0',
 '1994.0', '1967.0', '1990.0', '3000.0', '2019.0', '1976.0', '2001.0',
 '1997.0', '1984.0', '1977.0', '1988.0', '1995.0', '1981.0', '1983.0',
 '2003.0', '1991.0', '2000.0', '1989.0', '2026.0', '1966.0', '1959.0',
 '1969.0', '1975.0', '1986.0', '1999.0', '1979.0', '1996.0', '1998.0',
 '1970.0', '1968.0']
Length: 51, dtype: str

También las columnas Fills, No Fills y Te_cotxe deberian ser boleanas. Incluso Gènere si consideramos que solamente hay 2 generos. Estas columnas no las modificaremos todavía

Visto los datos únicos de cada columna se procede a cambiarlos de formato. Primero a float al tener escritura con decimales y despues a int64 (evita errores si hay nulos). Modifico las 4 columnas

In [127]:
columnas = ['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Nombre fills']
dataset_s8[columnas] = dataset_s8[columnas].astype(float).astype('Int64')
print(dataset_s8['Dia de Naixement'].unique())
dataset_s8.info()

<IntegerArray>
[23,  8, 27, 13, 29,  1, 25, 32, 24, 22, 10, 21, 14, 19, 15, 16, 11, 18, 28,
  9,  3,  2,  0, 20,  4, -5, 26, 30, 17,  5, 12,  6,  7, 31]
Length: 34, dtype: Int64
<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Dia de Naixement            990 non-null    Int64
 6   Mes de Naixement            990 non-null    Int64
 7   Any de Naixement            990 non-null    Int64
 8   Gènere                      951 non-null    str
 9   Salari mensual              990 non-null    str
 10  Fills                       414 non-null    str
 11  No Fills                    575 non-null    str
 12  Grup Professional           990 non-null    str
 13  Càrrec                      990 non-null    str
 14  Nombre fills                696 non-null    Int64
 15  Te cotxe                    647 non-null    str
 16  Km anuals                   310 non-null    object
 17  Consum mitja L 100km        257 non-null    str
 18  Temperatura mitjana ciutat  923 non-null    str
dtypes: Int64(4), object(1), str(14)
memory usage: 236.7+ KB

El siguiente paso es crear columna de fecha. Hay que unificarlas en una misma columna.

Pandas tiene una función de convertir a fecha y trabajar con ellas. errors='coerce' hace que si hay una fecha imposible (31 de febrero) sea un NA.

Igualmente se comprueba que no existan fechas superiores a la fecha de hoy. En valores únicos de 'Any de Naixement' usuarios han puesto que han nacido en el 3000 (dificil sin viaje en el tiempo) o en el 2019 (bastante ilegal en el 2026 trabajar a esa edad en España).

En la función es posible definir la edad mínima por la que queremos invalidar una fecha. En España la edad legal para trabajar son 16 años.

Con errors='coerce' se declaran nulas las fechas que en:
- 'Dia de Naixement' tenian un 32 o -5
- 'Mes de Naixement' tenian 99 y 13
- 'Any de Naixement' como tal no tenian años imposibles, pero si no se han declarado nulas las fechas con años 3000 o 2019 con el errors se han declarado al ser superiores a la fecha actual.

In [128]:
def crear_fecha(dia, mes, año, edad_minima=16):
    fecha = pd.to_datetime(
        {
            'year': año,
            'month': mes,
            'day': dia
        },
        errors='coerce'
    )

    if edad_minima is not None:
        limite = pd.Timestamp.today() - pd.DateOffset(years=edad_minima)
        fecha[fecha > limite] = pd.NaT

    return fecha

In [129]:
dataset_s8['Data de Naixement'] = crear_fecha(
    dataset_s8['Dia de Naixement'],
    dataset_s8['Mes de Naixement'],
    dataset_s8['Any de Naixement']
)

dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23,3,1958,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3,True,32108.0,25.0,10.1,1958-03-23
4,Marc,Muñoz,48840994W,Espanya,Alacant,8,11,1960,H,"2,718 €",NaN,True,Grup C,Senior analyst,0,True,19496.0,10.4,18.7,1960-11-08
5,Noa,Serra,14308421X,Espanya,Alacant,27,4,1961,D,1358 euros,True,NaN,Grup A,Tècnic IT,4,NaN,NaN,NaN,16.7,1961-04-27
6,Pol,Gil,58586340F,Espanya,Sevilla,13,10,1985,H,"1,478 €",True,NaN,Grup B,Data Analyst,2,False,NaN,NaN,18.3,1985-10-13
7,David,Vila,82070937P,Espanya,Bilbao,29,11,1965,Dona,"1,284 €",NaN,True,Grup B,Administratiu,<NA>,True,NaN,11.8,13.1,1965-11-29
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1,8,1978,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0,NaN,NaN,NaN,19.9,1978-08-01
9,David,Gómez Vila,36998038E,Espanya,Palma,25,9,1971,D,"2,349 €",NaN,True,Grup B,Cap de projecte,<NA>,True,6196.0,10.6,17.8,1971-09-25
10,Carmen,López,47376585K,Espanya,Barcelona,8,9,1962,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4,True,20000,5.9,15.4,1962-09-08
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8,3,1963,D,"1,338 €",NaN,True,Grup B,Analista junior,0,False,NaN,NaN,7.6,1963-03-08
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32,0,1940,H,"1,450 €",True,NaN,Grup A,Senior analyst,4,False,NaN,NaN,20.1,NaT

In [130]:
fechas_invalidas = dataset_s8[dataset_s8['Data de Naixement'] > pd.Timestamp.today()]
fechas_invalidas

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat, Data de Naixement]
Index: []

Elimino las columnas de dia, mes y año ya que puedo obtener los mismos datos validos en la columna de fecha de aniversario.

In [131]:
dataset_s8 = dataset_s8.drop(['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement'], axis=1)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
193,Jonas,Becker Wagner,71021210R,Alemanya,Frankfurt,D,1363€,NaN,True,Grup B,Analista,<NA>,False,NaN,NaN,11.5,1981-07-16
692,Sara,Gil Pujol,64671752H,Espanya,Girona,D,1.163 €,NaN,True,Grup A,Analista junior,0,NaN,NaN,NaN,14.8,1976-06-01
144,Marta,López Soler,53299069G,Espanya,Murcia,D,1.106 €,NaN,True,Grup A,Data Analyst,0,NaN,NaN,NaN,17.4,1964-06-10
376,Pol,Domènech,66061116Y,Espanya,Palma,A,"1,030 €",NaN,True,Grup A,Responsable de vendes,0,NaN,NaN,NaN,17.5,1978-04-14
725,Nil,Gómez Ribera,80910050J,Espanya,Zaragoza,Dona,1538 euros,NaN,True,Grup B,Senior analyst,<NA>,NaN,NaN,NaN,17.7,2003-03-12
280,Marina,Casals Vila,31442569K,Espanya,Sevilla,Home,"2,003 €",NaN,NaN,Grup C,Analista,4,NaN,NaN,NaN,19.6,NaT
453,Marc,Pérez,39343051Y,Espanya,Murcia,H,"1,525 €",True,NaN,Grup B,Tècnic IT,2,NaN,NaN,NaN,NaN,1995-02-02
255,Pau,Romero Serra,69839130L,Espanya,Barcelona,H,1110€,NaN,True,Grup A,Administratiu,0,False,NaN,NaN,12.2,1995-11-27
848,Marco,Rossi Lombardi,62597519M,Itàlia,Napoli,Dona,"2,065 €",True,NaN,Grup C,Data Analyst,1,NaN,NaN,NaN,42.0,1962-10-13
480,Laia,Torres Romero,28484302B,Espanya,Madrid,M,1.341 €,NaN,True,Grup A,Cap de projecte,0,True,14892.0,NaN,15.0,1958-01-09

## EJERCICIO 3: TRANSFORMACIONES NECESARIAS Y PREPARACIÓN DEL DATASET

Aspectos a revisar y transformar:

- ¿Los valores categóricos están normalizados y son consistentes?
- ¿Los valores nulos son coherentes con la información disponible?
- ¿Existe redundancia de variables que pueda generar problemas analíticos?
- ¿Las variables contextuales (como temperatura, salario) están completas y preparadas para el análisis?

Concretamente, tendrás que:

- Normalizar los valores categóricos para evitar ambigüedades (por ejemplo, valores que representan el mismo concepto pero están escritos de forma diferente).
- Revisar la coherencia de los valores nulos, asegurando que:
Las personas con kilometraje anual y consumo medio asociados disponen de coche. En los casos en que conste consumo medio pero no kilometraje anual, será necesario decidir cómo resolver esta incoherencia de forma justificada.
Las personas que tienen un valor en el número de hijos tienen efectivamente hijos.
- Unificar la información sobre hijos en una única columna, ya que mantener varias columnas con información complementaria no es óptimo y puede generar problemas analíticos (redundancia o multicolinealidad).
- Validar la temperatura media. En caso de que esa información falte, deberás imputarla utilizando un criterio razonable (por ciudad o por un nivel superior justificado).
- Revisar e imputar los salarios faltantes, aplicando criterios analíticos coherentes (como cargo, grupo profesional, ciudad, género o franja de edad).

In [132]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
299,Claudia,Díaz Torres,30744009Q,Espanya,València,Home,1510€,NaN,True,Grup A,Senior analyst,0,True,9639.0,NaN,16.4,1968-02-07
423,Oriol,Soler,27103900X,Espanya,Sevilla,M,1450 euros,True,NaN,Grup A,Tècnic IT,1,True,80000,13.0,22.6,1989-09-16
381,Anna,Puig,92279159M,Espanya,Valladolid,F,"1,222 €",NaN,True,Grup A,Tècnic IT,0,True,40723.0,25.0,9.8,2003-05-13
854,Núria,Álvarez,95325945X,Espanya,Tarragona,H,"1,105 €",NaN,True,Grup A,Senior analyst,<NA>,NaN,NaN,NaN,14.8,1975-12-25
546,Adrià,Gómez Soler,21091816B,Espanya,Bilbao,NaN,830 €,True,NaN,Grup A,Cap de Projecte,1,False,NaN,NaN,10.9,1964-08-26
355,Noa,Casals Vidal,37307523G,Espanya,Las Palmas de Gran Canaria,D,897 €,NaN,NaN,Grup A,Administratiu,<NA>,False,NaN,NaN,23.7,1963-11-17
653,Nicolas,Robert,64508486D,França,Lyon,D,918 €,True,NaN,Grup A,Senior analyst,1,NaN,NaN,NaN,8.4,1977-04-25
188,Marc,Ramos Gómez,34341456K,Espanya,Valladolid,H,1734€,True,NaN,Grup B,Analista,1,True,80000,4.7,14.4,1974-04-04
68,Marta,Ruiz Puig,29602406G,Espanya,Madrid,F,1664 euros,NaN,True,Grup B,Analista,<NA>,True,80000,25.0,13.9,2003-11-11
857,Adrià,Domènech Pujol,17494253Z,Espanya,València,Dona,850 €,True,True,Grup A,Tècnic IT,0,NaN,NaN,NaN,20.0,1977-04-23

##### Valores categóricos

Tomo como valores categóricos "Gènere", "Te_cotxe", "Grup Professional" y "Càrrec". Compruebo los valores únicos de cada uno.

Gènere tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo. Después cambiar formato a boolean

In [133]:
dataset_s8['Gènere'].unique()

<ArrowStringArray>
['Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A']
Length: 9, dtype: str

Te cotxe es correcto. Solo hay que cambiar formato a boolean

In [134]:
dataset_s8["Te cotxe"].unique()

<ArrowStringArray>
['True', nan, 'False']
Length: 3, dtype: str

Grup Professional se deja así tal cual. Las categorias están bien escritas.

In [135]:
dataset_s8['Grup Professional'].unique()

<ArrowStringArray>
['Grup B', 'Grup C', 'Grup A', 'Grup D']
Length: 4, dtype: str

Càrrec tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo.

Una vez estandarizado se comparará vs Grup Professional si todas coinciden o hay discrepancias

In [136]:
dataset_s8['Càrrec'].unique()

<ArrowStringArray>
[      'Cap de projecte',        'Senior analyst',             'Tècnic IT',
          'Data Analyst',         'Administratiu', 'Responsable de vendes',
       'Analista junior',          'Project lead',                'Admin.',
               'Analyst',              'Analista',          'Data analyst',
       'Cap de Projecte']
Length: 13, dtype: str

##### Valores categóricos: Gènere

Antes de comenzar la estandarización de la columba Gènere, cuento cuantas filas hay nulas en la columna y cuantos registros hay por cada género especificado por el usuario. De este modo puedo comprobar después que se haya completado la estandarización completamente.

In [137]:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')
dataset_s8.groupby('Gènere').size()

Hay: 39 filas de género nulas y 951 no nulas

Gènere
A        24
D       320
Dona    118
F       107
H       274
Home     51
M        34
NC       23
dtype: int64

Creo un diccionario para estandarizar los valores de 'Gènere'. De 'Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A' no se modificarán los nan, 'NC' y 'A'. Al hacer la transformación se borrarán. Los demás se asigna a 'Dona' o 'Home'.

No nulos hay 951 que se le restarán las 47 de 'A' y 'NC'. Quedarán 904 no nulos y 86 nulos si no falla la calculadora.

In [138]:
dicc_genere = {
    'Dona':'Dona', 
    'H': 'Home', 
    'D': 'Dona', 
    'F': 'Dona', 
    'Home': 'Home', 
    'M': 'Home', 
}

def definir_genero(genero):
    for categoria in dicc_genere:
        if genero == categoria:
            return dicc_genere[categoria]

dataset_s8['Gènere'] = dataset_s8['Gènere'].apply(definir_genero)

#Aprovecho el mismo código de antes:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')


dataset_s8.groupby('Gènere').size()

Hay: 86 filas de género nulas y 904 no nulas

Gènere
Dona    545
Home    359
dtype: int64

##### Valores categóricos: Té cotxe

In [139]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
408,Ole,Larsen,40728728N,Noruega,Oslo,Dona,"1,732 €",NaN,True,Grup C,Analista junior,0,True,11362.0,NaN,9.5,1966-08-03
184,Alexia,Muñoz,97446634Y,Espanya,Murcia,Home,dos mil,NaN,True,Grup B,Administratiu,0,True,48621.0,0.5,18.9,1989-01-10
314,Lucas,Richard Fournier,35758531T,França,Bordeaux,Dona,"1,125 €",NaN,True,Grup A,Senior analyst,<NA>,True,NaN,NaN,12.3,1973-02-05
572,Alexia,Soler Puig,88666938N,Espanya,Barcelona,Dona,856 €,NaN,True,Grup A,Analista,<NA>,True,80000,25.0,16.1,1973-05-20
1004,Kasper,Pettersen,62042563B,Noruega,Oslo,Dona,2.290 €,NaN,True,Grup B,Senior analyst,0,True,80000,0.5,6.5,1996-05-11
98,Elena,Moretti,19031632A,Itàlia,Roma,NaN,2488 euros,True,NaN,Grup C,Analista,1,True,42398.0,25.0,19.2,1959-04-07
981,Giulia,Conti Russo,72192924S,Itàlia,Bologna,Home,1931 euros,NaN,True,Grup C,Administratiu,0,NaN,NaN,NaN,15.0,1990-10-29
700,Kristian,Lie,15190410S,Noruega,Stavanger,Home,939 €,NaN,True,Grup A,Analista junior,0,NaN,NaN,NaN,8.5,NaT
944,Elena,Esposito,19180850S,Itàlia,Bologna,Dona,830 €,NaN,True,Grup A,Analista,0,False,NaN,NaN,16.3,1968-09-26
193,Jonas,Becker Wagner,71021210R,Alemanya,Frankfurt,Dona,1363€,NaN,True,Grup B,Analista,<NA>,False,NaN,NaN,11.5,1981-07-16

Para la columna 'Té cotxe' el objetivo es convertirla en tipo boolean para que 0 = no coche (False) y 1 = si coche (True).

Igualmente se comprobará si hay valor en Km anuals o Consum mitja L 100km. Si tiene registro en alguna de las columnas se pondrá como True.

In [140]:
dataset_s8['Te cotxe'] = dataset_s8['Te cotxe'].astype(bool)
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Gènere                      904 non-null    str
 6   Salari mensual              990 non-null    str
 7   Fills                       414 non-null    str
 8   No Fills                    575 non-null    str
 9   Grup Professional           990 non-null    str
 10  Càrrec                      990 non-null    str
 11  Nombre fills                696 non-null    Int64
 12  Te cotxe                    990 non-null    bool
 13  Km anuals                   310 non-null    object
 14  Consum mitja L 100km        257 non-null    str
 15  Temperatura mitjana ciutat  923 non-null    str
 16  Data de Naixement           913 non-null    datetime64[us]
dtypes: Int64(1), bool(1), datetime64[us](1), object(1), str(13)
memory usage: 210.7+ KB

Comprobamos valores únicos de Km anual y Consum mitja L 100km para echar un ojo a los datos. A simple vista son numeros en formato str, por lo que después del proceso de 'Té cotxe' se transformarán en enteros o decimales.

In [141]:
dataset_s8['Consum mitja L 100km'].unique()

<ArrowStringArray>
['25.0', '10.4',    nan, '11.8', '10.6',  '5.9',  '7.7', '12.9', '12.2',
  '0.5',  '7.4', '12.0', '11.0',  '7.3',  '7.0', '11.7',  '7.6', '11.5',
  '6.1', '12.7', '10.1', '10.2',  '6.7',  '7.1', '13.6',  '9.6', '13.9',
  '8.0',  '4.7',  '5.0', '10.5',  '7.8', '13.4',  '6.2', '13.8', '11.6',
 '11.4',  '8.8',  '8.7',  '5.8',  '5.4',  '5.7',  '6.8', '10.8', '13.3',
  '4.9', '12.1', '11.2', '13.0',  '9.8',  '4.6', '14.0',  '4.8',  '9.2',
 '13.5', '12.5',  '8.2',  '4.5', '13.2',  '6.6',  '5.1',  '9.0',  '4.1',
 '13.7', '10.3', '12.8',  '8.4', '10.7', '10.0', '12.4', '13.1',  '6.4',
  '6.5',  '8.6',  '8.3', '12.6',  '4.4',  '5.6',  '5.5',  '8.9',  '6.9',
  '5.3',  '9.1',  '9.4']
Length: 84, dtype: str

In [142]:
dataset_s8['Km anuals'].unique()

array(['32108.0', '19496.0', nan, '6196.0', 20000, '14178.0', '10800.0',
       '6931.0', '38248.0', 65950, 80000, '64444.0', '22384.0',
       '116927.0', 50000, '78064.0', '114730.0', '60856.0', '29300.0',
       '113964.0', '39561.0', 65983, '29386.0', '42398.0', '76180.0',
       '106611.0', '35142.0', '19232.0', '23728.0', '3920.0', '23206.0',
       '5776.0', '13870.0', '104603.0', '37506.0', '99990.0', '67841.0',
       '59507.0', '48621.0', '27526.0', '62723.0', '26866.0', 70000,
       1000000, '5252.0', '81945.0', 30000, '6283.0', '113059.0', '0.0',
       '4103.0', '100054.0', '56135.0', '30452.0', '9639.0', '14109.0',
       '49000.0', '87108.0', '13833.0', '27752.0', '54025.0', '15579.0',
       '12947.0', '43566.0', '42512.0', '72237.0', '40723.0', '6140.0',
       '118147.0', '60652.0', 40000, '21069.0', '94969.0', '11362.0',
       '31309.0', '86060.0', '95003.0', '57089.0', '115098.0', '21422.0',
       '71500.0', '54623.0', '53463.0', '11346.0', '44565.0', '23129.0',
       '3936.0', '14527.0', '42899.0', '16390.0', '8516.0', '14892.0',
       '5584.0', '12431.0', '13407.0', '29278.0', '18378.0', '21062.0',
       '74741.0', '28115.0', '26936.0', '113145.0', '2938.0', '93114.0',
       '111435.0', '8460.0', '67158.0', '80657.0', '44563.0', '107311.0',
       '33895.0', '84895.0', '22880.0', '11090.0', '11169.0', '29434.0',
       '62991.0', '114489.0', '32431.0', '18402.0', '74348.0', '96645.0',
       '99638.0', '28988.0', '60905.0', '29952.0', '107127.0', '28726.0',
       '-50.0', '6377.0', '45301.0', '99431.0', '77960.0', '81381.0',
       '56365.0', '116654.0', '52646.0', '16998.0', '29847.0', '53342.0',
       '52327.0', '4934.0', '43088.0', '13608.0', '22166.0', '29464.0',
       '113111.0', '32672.0', '6369.0', '30481.0', '115076.0', '36221.0',
       '82014.0', '32217.0', '25193.0', '109099.0', '81219.0', '24307.0',
       '110775.0', '17246.0', '50370.0', '9017.0', '7861.0', '97162.0',
       '56745.0', '116027.0', '50453.0', '27921.0', '35591.0'],
      dtype=object)

Creo una nueva columna de coche calculado a partir de una condificon de si km anuals o consumo tienen valor generará True o False.

Utilizo fillna("") para substituir las filas sin datos para que no de un falso positivo.
ne("") es un not equal o != pero en metodo para pandas. Busca una celca vacía "".

In [143]:
dataset_s8['Te cotxe calculat'] = dataset_s8['Km anuals'].fillna("").ne("") | dataset_s8['Consum mitja L 100km'].fillna("").ne("")
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat
81,Manon,Laurent,45899440Z,França,Lille,Dona,1092 euros,True,NaN,Grup A,Senior analyst,2,True,NaN,NaN,11.9,1973-08-04,False
740,Elias,Hagen,81192277J,Noruega,Bergen,Home,"1,944 €",NaN,True,Grup C,Data Analyst,<NA>,True,NaN,NaN,-5.0,1966-02-11,False
58,Carlos,Díaz,26104026T,Espanya,Barcelona,Home,"1,413 €",NaN,NaN,Grup B,Data analyst,<NA>,True,NaN,NaN,18.6,1974-05-11,False
361,Jordi,Serra,70924933T,Espanya,Valladolid,Home,"1,438 €",NaN,True,Grup A,Tècnic IT,<NA>,True,NaN,NaN,14.6,2001-09-29,False
209,Oriol,Costa Gómez,59970552B,Espanya,Bilbao,Dona,mil vuit-cents,NaN,True,Grup A,Tècnic IT,<NA>,True,NaN,NaN,17.3,1971-07-23,False
602,Emil,Moen,14887763Y,Noruega,Stavanger,Home,"1,501 €",NaN,True,Grup B,Analista junior,<NA>,True,NaN,NaN,8.7,1989-03-26,False
645,Guillem,Fernández,96950282C,Espanya,Girona,Home,"1,747 €",True,NaN,Grup B,Senior analyst,2,True,NaN,NaN,NaN,1981-08-02,False
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,Dona,"1,338 €",NaN,True,Grup B,Analista junior,0,True,NaN,NaN,7.6,1963-03-08,False
158,Víctor,Díaz,60529679B,Espanya,A Coruña,Dona,"1,654 €",True,True,Grup B,Responsable de vendes,0,True,NaN,NaN,-5.0,1975-07-29,False
686,Oriol,Gómez Díaz,57949350K,Espanya,Barcelona,Dona,806 €,NaN,True,Grup A,Analista junior,0,True,80000,25.0,15.6,NaT,True

Compruebo si hay alguna incongruencia con Te cotxe vs la columna calculada

In [144]:
coche_falso = dataset_s8['Te cotxe'] != dataset_s8['Te cotxe calculat']
coche_falso.value_counts()

True     678
False    312
Name: count, dtype: int64

Hay 312 que son iguales y 678 que la columna Te cotxe y la calculada son diferentes. Compruebo la cantidad de nulos que hay en Km anuals y Consum mitja L 100km.

In [145]:
dataset_s8.isna().sum()

2
Nom                             0
Cognoms                         0
DNI                             0
País d'origen                   0
Ciutat                          0
Gènere                         86
Salari mensual                  0
Fills                         576
No Fills                      415
Grup Professional               0
Càrrec                          0
Nombre fills                  294
Te cotxe                        0
Km anuals                     680
Consum mitja L 100km          733
Temperatura mitjana ciutat     67
Data de Naixement              77
Te cotxe calculat               0
dtype: int64

Al tener una cantidad importante de nulos en ambas columnas (más de la mitad) opto por dar como correcta la columna de 'Te cotxe calculat'. Por lo tanto, borro la columna 'Te cotxe' y mantengo la otra

In [146]:
dataset_s8.drop(columns='Te cotxe',inplace=True)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat
368,Lucía,Domènech,84449447A,Espanya,Zaragoza,Dona,966 €,NaN,True,Grup A,Data Analyst,0,72237.0,10.8,15.4,1962-06-01,True
699,Alba,Sánchez,73542673S,Espanya,València,Home,"2,401 €",NaN,True,Grup C,Administratiu,<NA>,74348.0,13.2,18.0,1965-10-05,True
799,Alexia,Ferrer,44721033L,Espanya,Palma,Home,"1,146 €",NaN,True,Grup B,Analista,0,NaN,NaN,20.6,1962-09-05,False
546,Adrià,Gómez Soler,21091816B,Espanya,Bilbao,NaN,830 €,True,NaN,Grup A,Cap de Projecte,1,NaN,NaN,10.9,1964-08-26,False
660,Alessandro,Colombo Bianchi,18052256Q,Itàlia,Roma,Dona,896 €,True,NaN,Grup A,Analista,2,62991.0,11.7,14.2,1983-01-12,True
815,Sara,Casals Sánchez,31087800H,Espanya,Sevilla,Home,1.311 €,NaN,True,Grup A,Senior analyst,0,4934.0,5.0,15.2,NaT,True
493,Luca,Moretti,58037222W,Itàlia,Napoli,Dona,874 €,NaN,True,Grup A,Data Analyst,<NA>,20000,9.2,15.6,1976-05-13,True
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3,32108.0,25.0,10.1,1958-03-23,True
819,Gabriele,Giordano Moretti,66329894V,Itàlia,Bologna,Dona,994 €,NaN,True,Grup A,Analyst,<NA>,NaN,NaN,11.9,1993-04-14,False
283,Carmen,Ribera Gómez,32808354H,Espanya,Màlaga,Dona,"1,179 €",True,True,Grup A,Senior analyst,0,NaN,NaN,19.3,1998-10-29,False

El siguiente paso es convertir a decimales km anuals y consum mitja L 100km.

In [147]:
dataset_s8['Km anuals'] = dataset_s8['Km anuals'].astype(float)
dataset_s8['Consum mitja L 100km'] = dataset_s8['Consum mitja L 100km'].astype(float)
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Gènere                      904 non-null    str
 6   Salari mensual              990 non-null    str
 7   Fills                       414 non-null    str
 8   No Fills                    575 non-null    str
 9   Grup Professional           990 non-null    str
 10  Càrrec                      990 non-null    str
 11  Nombre fills                696 non-null    Int64
 12  Km anuals                   310 non-null    float64
 13  Consum mitja L 100km        257 non-null    float64
 14  Temperatura mitjana ciutat  923 non-null    str
 15  Data de Naixement           913 non-null    datetime64[us]
 16  Te cotxe calculat           990 non-null    bool
dtypes: Int64(1), bool(1), datetime64[us](1), float64(2), str(12)
memory usage: 209.7 KB

Ahora compruebo la distribución de km y consumo. Si ambos estan informados o si uno de los dos falla.

In [148]:
print("Ambos informados:",
      ((dataset_s8['Km anuals'].notna()) &
       (dataset_s8['Consum mitja L 100km'].notna())).sum())

print("Km si, consumo no:",
      ((dataset_s8['Km anuals'].notna()) &
       (dataset_s8['Consum mitja L 100km'].isna())).sum())

print("Km no, consumo si:",
      ((dataset_s8['Km anuals'].isna()) &
       (dataset_s8['Consum mitja L 100km'].notna())).sum())

Ambos informados: 255
Km si, consumo no: 55
Km no, consumo si: 2

Obtengo la desviación estandar, media, mediana, modo, maximo y minimo para las columnas Km anuals y Consum mitja L 100km

In [149]:
km_desviacion = dataset_s8['Km anuals'].std()
km_media = dataset_s8['Km anuals'].mean()
km_mediana = dataset_s8['Km anuals'].median()
km_mode = dataset_s8['Km anuals'].mode()
km_max = dataset_s8['Km anuals'].max()
km_min = dataset_s8['Km anuals'].min()
print(f"""Km anuals:
km desviacion = {km_desviacion}
km media = {km_media}
km mediana = {km_mediana}
km_mode = {km_mode}
km_max = {km_max}
km_min = {km_min}""")

Km anuals:
km desviacion = 62464.19789379955
km media = 56031.04516129032
km mediana = 55379.0
km_mode = 0    80000.0
Name: Km anuals, dtype: float64
km_max = 1000000.0
km_min = -50.0

In [150]:
consum_desviacion = dataset_s8['Consum mitja L 100km'].std()
consum_media = dataset_s8['Consum mitja L 100km'].mean()
consum_mediana = dataset_s8['Consum mitja L 100km'].median()
consum_mode = dataset_s8['Consum mitja L 100km'].mode()
consum_max = dataset_s8['Consum mitja L 100km'].max()
consum_min = dataset_s8['Consum mitja L 100km'].min()
print(f"""consum data:
consum desviacion = {consum_desviacion}
consum media = {consum_media}
consum mediana = {consum_mediana}
consum mode = {consum_mode}
consum max = {consum_max}
consum min = {consum_min}""")

consum data:
consum desviacion = 8.832870803940532
consum media = 11.070038910505836
consum mediana = 9.8
consum mode = 0    25.0
Name: Consum mitja L 100km, dtype: float64
consum max = 25.0
consum min = 0.5

Hay una gran desviación en ambas columnas (casi más que el valor del promedio/media).

Los maximos y mínimos en ambas columnas son demasiado extremos. Incluso hay negativos.

Primero calculo la correlación.

In [151]:
dataset_s8[['Km anuals', 'Consum mitja L 100km']].corr()

2                     Km anuals  Consum mitja L 100km
2
Km anuals               1.00000               0.13008
Consum mitja L 100km    0.13008               1.00000

Al tener una asociación pequeña, averiguo la media, mediana y correlacion de consum por cada quartil de km anuals.

In [152]:
dataset_s8.groupby(pd.qcut(dataset_s8['Km anuals'], q=4))['Consum mitja L 100km'].agg(['mean','median','std'])

                           mean  median       std
Km anuals
(-50.001, 22508.0]     8.947170    8.20  5.986318
(22508.0, 55379.0]    11.059701   10.20  9.850182
(55379.0, 80000.0]    12.065686   11.45  9.220054
(80000.0, 1000000.0]  10.978788    9.40  8.987935

La desviación es bastante grande, por lo que muestra una gran variabilidad de resultados. Una posibilidad es rellenar datos, pero empujaría la estadística hacia lo standard. Los km anuales son muy variables debido a que un usuario puede vivir a 10km o 100km de su trabajo. El consumo es igual de variable dependiendo de las características del vehículo y el estílo de conducción del usuario.

Teniendo en cuenta estos datos, opto por borrar los valores negativos de km anual.

In [153]:
dataset_s8 = dataset_s8[dataset_s8['Km anuals']>=0]
dataset_s8['Km anuals'].min()

np.float64(0.0)