# NIVEL 1: 'EDA' ESTRUCTURADO Y LIMPIEZA DE DATOS

## EJERCICIO 1: EXPLORACIÓN INICIAL DEL DATASET

#### OBJETIVOS:
Con "sprint8_complex.xlsx" responder a las preguntas:

- Cuantas filas y columnas tiene el dataset
- Tipos de datos tiene cada columna
- Hay duplicados?
- Datos coherentes a simple vista?
- Posibles problemas o inconvenientes evidentes

Para responderlas hay que:

- Analizar la dimension del dataset
- Monstrar una muestra representativa de filas
- Revisar los tipos de variables
- Detectar duplicados
- Coherencia de datos
- Identificar y describir posibles problemas iniciales (sin solucionarlos)

Primero de todo instalo openpyxl para poder abrir el archivo xlsx. Pandas tiene la función de abrir un arhivo xlsx, pero necesita las instrucciones de openyxl para hacerlo.

pip install openpyxl

Importación de librerias necesarias para el analisis, limpieza y gestión del dataset

In [443]:
import pandas as pd
import json

In [312]:
dataset_s8 = pd.read_excel('sprint8_complex.xlsx')
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Dades de l'enquesta de treballadors 2025  1008 non-null   object
 1   Unnamed: 1                                1007 non-null   str
 2   Unnamed: 2                                1007 non-null   str
 3   Unnamed: 3                                1007 non-null   str
 4   Unnamed: 4                                1007 non-null   str
 5   Unnamed: 5                                1007 non-null   str
 6   Unnamed: 6                                1007 non-null   str
 7   Unnamed: 7                                1007 non-null   str
 8   Unnamed: 8                                1007 non-null   str
 9   Unnamed: 9                                967 non-null    str
 10  Unnamed: 10                               1007 non-null   str
 11  Unnamed: 11                               420 non-null    str
 12  Unnamed: 12                               586 non-null    str
 13  Unnamed: 13                               1006 non-null   str
 14  Unnamed: 14                               1006 non-null   str
 15  Unnamed: 15                               710 non-null    object
 16  Unnamed: 16                               659 non-null    str
 17  Unnamed: 17                               316 non-null    object
 18  Unnamed: 18                               262 non-null    str
 19  Unnamed: 19                               937 non-null    str
dtypes: object(3), str(17)
memory usage: 255.9+ KB

### Muestra del dataset (20 primeros)

In [313]:
dataset_s8.head(20)

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,6,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,7,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,10,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,11,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,12,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,13,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,14,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,15,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,16,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

### Número de filas y columnas

In [314]:
print(f"Hay {dataset_s8.shape[0]} filas y {dataset_s8.shape[1]} columnas")

Hay 1010 filas y 20 columnas

### Tipo de datos y cantidad

In [315]:
dataset_s8.dtypes.value_counts()

str       17
object     3
Name: count, dtype: int64

Hay 17 columnas de tipo str y 3 tipo object

### Duplicados

El número de duplicados será 0 al tener en cuenta la primera columna. Se ha generado aleatoriamente un número, por lo que no contará como duplicado aún habiendo realmente duplicados.

In [316]:
dataset_s8.duplicated().sum()

np.int64(0)

En cambio, si quitamos la primera columna, si existen 6 filas repetidas. Por lo que aprovechamos para eliminarla, ya que funciona como un indice, pero ya hay un indice en la tabla.

In [317]:
dataset_s8.iloc[:,1:].duplicated().sum()

np.int64(6)

In [318]:
dataset_s8 = dataset_s8.drop(["Dades de l'enquesta de treballadors 2025"], axis=True)

In [319]:
dataset_s8.head(20)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

### Datos coherentes a simple vista?

Viendo la muestra, se detectan que hay columnas que se pueden juntar (Fills, No_Fills y Nombre_fills). Por el resto, está "bien" estructurado y solamente hay que pulir datos.

### Futuros problemas

Existen columnas que se pueden juntar (fills, no_fills y nombre_fills)
Codificación de las variables es erronea y las palabras con acentos o signos especiales se ven afectadas.
Estandarización: el salario mensual hay usuarios que lo han puesto en numeros y otros en texto. La columna "dona" deberia ser genero y las variables H/M, pero hay "Dona".
En varias columnas hay números decimales cuando podrían ser enteros (n hijos)

## EJERCICIO 2: VALIDACIÓN BÀSICA DE DATOS Y DECISIONES DE ELIMINACIÓN 

Aspectos a validar:

- ¿Existen identificadores únicos (DNI) para cada persona?
- ¿Qué vas a hacer con las filas duplicadas o registros repetidos?
- ¿Existen valores obligatorios que faltan o información incoherente?
- ¿Detectos formatos incorrectos, errores de codificación o valores imposibles?

Concretamente, tendrás que:

- Corregir posibles problemas de codificación y acentuación en los nombres de las columnas y en los valores de texto, si procede.
- Detectar y eliminar filas duplicadas exactas, indicando cuántos registros se han eliminado.
- Comprobar la unicidad del DNI. En caso de detectar DNIs duplicados, deberás analizar la coherencia de la información asociada y descartar o anular los registros que no sean fiables, justificando claramente la decisión tomada.
- Identificar los campos clave que no deberían contener valores nulos, detectar registros con información insuficiente y eliminar únicamente aquellas filas completamente vacías o con información irrecuperable o no sustituible, explicando por qué no es posible ni razonable imputarlas.

### DNI como identificadores

Para validar si existen DNIs y demás, es útil renombrar las columnas por su nombre correcto. En el dataframe se encuentran en la fila 3 (indice 2).

In [320]:
dataset_s8.columns = dataset_s8.iloc[2]
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8

Borro las 3 primeras filas porque no tienen datos

In [321]:
dataset_s8 = dataset_s8.drop(dataset_s8.index[0:3])
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Si existen DNIs como identificadores. Ahora compruebo si son únicos o repetidos y los muestro.

In [322]:
dni_duplicado = dataset_s8[dataset_s8.duplicated(['DNI'])]
dni_duplicado.sort_values(by='DNI')

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
607,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 â‚¬",True,False,Grup A,Analista,1,True,50.0,NaN,14.2
757,Oriol,GÃ³mez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 â‚¬,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
761,Oriol,GÃ³mez,16618423V,Espanya,MÃ laga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
762,Oriol,GÃ³mez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 â‚¬",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
695,Alexia,PÃ©rez DÃ­az,49529438G,Espanya,MÃ laga,12.0,10.0,1981.0,Dona,1663â‚¬,NaN,True,Grup C,Cap de projecte,NaN,True,80000,10.7,16.9
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
145,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 â‚¬",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1006,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
107,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
117,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 â‚¬",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
284,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,TÃ¨cnic IT,0.0,True,63574.0,6.0,16.8
916,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1003,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1005,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7

Existen varios DNIs repetidos. En algunos casos solo 2 veces (los que se ven solo una vez en la tabla de arriba), pero otros tienen varias repeticiones y con distinto nombre de usuario.

La eliminación de los DNis repetidos lo haré en el siguiente paso. También los DNIs nulos

### Registros duplicados y repetidos

Primero, corrijo la codificación por si existen registros duplicados, pero que tengan elementos bien codificados y otros mal. Si existiesen ese tipo de casos, no contarían como duplicados. Se aplica una corrección a todas las columnas.

Se crea una función para obtener un valor. Si el valor no es str lo devuelve.

Mientras hayan correcciones en valor (todo el codigo dentro de While) seguirá funcionando. Cuando no haya más cambios, parará (corregido = True/False)

Se han intrucido cp1252 y latin1 por si alguno no corrige correctamente el valor.

Se le agrega un replace para quitar los "_" de los titulos de las columnas.

Ejecuto un apply para que recorra las columnas y aplique con map la funcion a cada valor.

Solamente haciendo el cp1252 dejaba algún elemento sin corregir.

In [323]:
def corregir_texto(valor):
    if not isinstance(valor, str):
        return valor

    while True:
        corregido = False

        for encoding in ('cp1252', 'latin1'):
            try:
                nuevo = valor.encode(encoding).decode('utf-8')

                if nuevo != valor:
                    valor = nuevo
                    corregido = True
                    break

            except (UnicodeEncodeError, UnicodeDecodeError):
                pass

        if not corregido:
            break

    return valor.replace("_", ' ')

dataset_s8 = dataset_s8.apply(lambda col: col.map(corregir_texto))
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
767,Anna,Weber,22111010Q,Alemanya,Hamburg,-5.0,0.0,2019.0,Dona,"1,209 €",True,NaN,Grup A,Responsable de vendes,1.0,True,50000,11.6,4.6
727,Xavier,García,77239032Q,Espanya,Alacant,18.0,4.0,1981.0,D,937€,True,NaN,Grup A,Data Analyst,1,True,NaN,NaN,17.9
486,Marc,Soler,29016797K,Espanya,Palma,6.0,1.0,1998.0,F,"1,399 €",NaN,True,Grup A,Senior analyst,NaN,NaN,NaN,NaN,15.9
515,Anna,Puig Sánchez,98735423C,Espanya,Màlaga,-5.0,0.0,2019.0,H,962 €,NaN,True,Grup A,Analista,0.0,False,NaN,NaN,19.7
575,Sergio,Roca López,31236454Q,Espanya,A Coruña,18.0,2.0,1993.0,H,1035€,True,NaN,Grup A,Analista junior,1.0,False,NaN,NaN,17.3
427,Thomas,Vincent,88427071N,França,Nantes,7.0,5.0,1999.0,H,864€,True,NaN,Grup A,Analista junior,1,NaN,NaN,NaN,10.7
149,Luca,Gallo Ferrari,74468586Y,Itàlia,Torino,20.0,11.0,2000.0,D,n/d,NaN,True,Grup A,Analista junior,NaN,False,NaN,NaN,14.4
740,Elias,Hagen,81192277J,Noruega,Bergen,11.0,2.0,1966.0,Home,"1,944 €",NaN,True,Grup C,Data Analyst,NaN,False,NaN,NaN,-5.0
295,Sergio,López,64956876C,Espanya,Las Palmas de Gran Canaria,1.0,2.0,1982.0,H,3001€,NaN,True,Grup C,Cap de projecte,0.0,False,NaN,NaN,24.4
351,Marie,Moreau,93041052V,França,Paris,7.0,2.0,1993.0,D,2180€,NaN,True,Grup C,Analyst,0.0,NaN,NaN,NaN,14.0

Como la codificación se ha hecho después de definir el nombre de las columnas, "Càrrec" está mal escrita por lo que se lanza la función que se ha hecho antes a las columnas

In [324]:
dataset_s8.columns = dataset_s8.columns.map(corregir_texto)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
483,Hugo,Puig Ruiz,82916404H,Espanya,València,20.0,3.0,1981.0,Dona,1579€,NaN,True,Grup B,Cap de projecte,NaN,True,5584.0,NaN,17.2
994,Carlos,Gómez,54542152B,Espanya,Barcelona,28.0,4.0,2002.0,M,1377€,True,True,Grup B,Analista,NaN,False,NaN,NaN,16.5
775,Guillem,Vidal,16498347C,Espanya,Sevilla,13.0,3.0,1965.0,H,"1,364 €",NaN,True,Grup B,Data Analyst,NaN,NaN,NaN,NaN,16.7
892,Carlos,Fernández,77404592Q,Espanya,Murcia,10.0,1.0,1986.0,NC,"1,121 €",True,True,Grup A,Responsable de vendes,0.0,False,NaN,NaN,16.9
331,Claudia,Moreno,30813102S,Espanya,Barcelona,23.0,11.0,1999.0,Home,880 €,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,42.0
116,Núria,Muñoz Pujol,56300738T,Espanya,Sevilla,5.0,9.0,2002.0,Dona,"1,240 €",NaN,True,Grup A,Responsable de vendes,0.0,False,NaN,NaN,21.2
620,Carlos,Álvarez,30918595C,Espanya,Girona,25.0,10.0,2001.0,D,"1,201 €",True,NaN,Grup A,Tècnic IT,2.0,True,33895.0,7.7,12.2
185,Guillem,Pérez Serra,33889703P,Espanya,Girona,2.0,2.0,1963.0,D,"1,306 €",NaN,True,Grup B,Analista junior,NaN,True,27526.0,25.0,13.2
770,Arthur,Richard,45035917P,França,Nice,11.0,10.0,1959.0,D,1318 euros,True,True,Grup B,Responsable de vendes,0,NaN,NaN,NaN,17.0
216,Oriol,Díaz Romero,10968781V,Espanya,Tarragona,26.0,4.0,1996.0,F,935 €,NaN,True,Grup A,Administratiu,NaN,True,1000000,25.0,17.1

Ahora compruebo los registros duplicados y los borro.

In [325]:
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1005,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1006,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

Borramos los 4 registros duplicados.
Volvemos a comprobar los duplicados y ya no hay.

In [326]:
dataset_s8 = dataset_s8.drop_duplicates()
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

Tomaré la columna DNI como dato identificador y único de los usuarios. Como se ha comprobado antes, existen DNIs repetidos. Antes de borrarlos, compruebo si hay DNI con mayusculas/minusculas, con espacios y guiones. De esta manera nos aseguramos borrar los adecuados.

In [327]:
dni_espacio = dataset_s8[dataset_s8['DNI'].str.contains(' ')]
dni_espacio

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

In [328]:
dni_guion = dataset_s8[dataset_s8['DNI'].str.contains('-')]
dni_guion

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

No hay DNIs con espacios ni con guiones, por lo que omito la acción de borrarlos DNIs.

Ahora pongo todas las letras de los DNIs en mayuscula y elimino los duplicados.

In [329]:
dataset_s8['DNI'] = dataset_s8['DNI'].str.upper()
dni_num_duplicados = dataset_s8.duplicated(subset=['DNI']).sum()
print(f"Se han eliminado {dni_num_duplicados} DNIs duplicados")
dataset_s8 = dataset_s8.drop_duplicates(subset=['DNI'])
dataset_s8.head(10)

Se han eliminado 11 DNIs duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,Gómez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 €",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,López,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 €",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 €",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Borrados los DNI duplicados, compruebo la longitud de estos. Un DNI español tiene 9 caracteres. En caso de que sean extranjeros con un NIE también son 9 caracteres.

Primero cuento los DNIs que no tienen esa longitud

In [330]:
dni_longitud_mal = dataset_s8[dataset_s8['DNI'].str.len() != 9]
dni_longitud_mal

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
1008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

Sabiendo que hay 2 filas con DNIs con una longitud diferente a 9. Los borro

In [331]:
def longitud_dni(valor):
    return isinstance(valor, str) and len(valor) == 9

dataset_s8 = dataset_s8[dataset_s8['DNI'].apply(longitud_dni)]
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
360,Noah,Schröder,91339562Y,Alemanya,Köln,23.0,12.0,1989.0,F,842 euros,NaN,True,Grup A,Analista,NaN,True,43566.0,25.0,-5.0
154,Anna,Ribera Ruiz,59988144T,Espanya,Zaragoza,29.0,5.0,1988.0,D,845 €,NaN,True,Grup A,Administratiu,0.0,True,50000,0.5,12.8
459,Xavier,López,95156202C,Espanya,Las Palmas de Gran Canaria,15.0,3.0,2004.0,F,"1,310 €",NaN,True,Grup B,Administratiu,NaN,NaN,NaN,NaN,21.9
396,Marco,Barbieri,38122043N,Itàlia,Milano,24.0,5.0,1967.0,H,"2,795 €",NaN,True,Grup C,Cap de projecte,NaN,NaN,NaN,NaN,13.2
838,Giulia,Ferrari,62501008M,Itàlia,Firenze,0.0,13.0,2019.0,F,"1,691 €",NaN,True,Grup B,Cap de projecte,0.0,True,22166.0,4.4,15.6
442,Antoine,Richard Dubois,63741103L,França,Toulouse,7.0,12.0,1966.0,D,1729 euros,NaN,True,Grup B,Analista,NaN,NaN,NaN,NaN,14.4
746,Sergio,Pérez,35553337Y,Espanya,Valladolid,4.0,7.0,1980.0,M,"2,574 €",NaN,True,Grup C,Responsable de vendes,0.0,False,0.0,NaN,10.8
48,Hugo,Ribera,18484847C,Espanya,Barcelona,21.0,4.0,1997.0,D,"1,032 €",True,NaN,Grup A,Responsable de vendes,1.0,False,NaN,NaN,NaN
244,Tim,Schäfer Wolf,37226295T,Alemanya,Berlin,5.0,2.0,1969.0,Dona,2099 euros,NaN,True,Grup B,Cap de projecte,NaN,NaN,NaN,NaN,8.1
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1

### Valores nulos

Ante la existencia de los valores nulos, borro las filas que tengan TODAS las columnas con nulos. En este caso solo 1 fila tiene todo nulos.

In [332]:
num_nulos = dataset_s8.isna().all(axis=1).sum()
nulos = dataset_s8.isna().all(axis=1)
dataset_s8 = dataset_s8.dropna(how="all")
print(nulos)
num_nulos

3       False
4       False
5       False
6       False
7       False
        ...
999     False
1000    False
1001    False
1002    False
1004    False
Length: 990, dtype: bool

np.int64(0)

También compruebo si en DNI hay nulos. En este caso no hay.

In [333]:
dni_nulos = dataset_s8[dataset_s8['DNI'].isna()]
dni_nulos

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

### Formatos incorrectos

In [334]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
291,Chiara,Lombardi,70187134V,Itàlia,Torino,12.0,3.0,1980.0,H,795 €,NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,-5.0
924,Lucía,Roca Hernández,93114754K,Espanya,Bilbao,10.0,9.0,1990.0,D,988 €,NaN,True,Grup A,Responsable de vendes,NaN,NaN,NaN,NaN,15.0
697,Nicolas,Laurent Lefebvre,78775814N,França,Toulouse,26.0,2.0,1985.0,F,1342€,NaN,True,Grup A,Senior analyst,0.0,NaN,NaN,NaN,11.5
184,Alexia,Muñoz,97446634Y,Espanya,Murcia,10.0,1.0,1989.0,H,dos mil,NaN,True,Grup B,Administratiu,0.0,True,48621.0,0.5,18.9
897,Charlotte,Klein,88228686A,Alemanya,Düsseldorf,0.0,0.0,2019.0,F,"1,166 €",True,NaN,Grup B,Administratiu,2.0,NaN,NaN,NaN,8.2
352,Alba,Serra,53007542N,Espanya,Sevilla,20.0,9.0,1963.0,D,"1,092 €",True,NaN,Grup A,Analista,1.0,False,NaN,NaN,17.1
238,Alejandro,Díaz,29482024C,Espanya,Murcia,30.0,7.0,1966.0,D,1.147 €,True,NaN,Grup A,Data Analyst,3.0,True,65950,NaN,20.0
755,Sergio,Ramos,52715309K,Espanya,València,18.0,11.0,1960.0,H,1412€,True,NaN,Grup B,Data analyst,1.0,True,65950,0.5,20.2
959,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,10.0,5.0,2004.0,D,n/d,NaN,True,Grup A,Cap de projecte,NaN,True,9017.0,0.5,13.0
171,Marc,Moreno,98813650F,Espanya,Valladolid,14.0,2.0,1997.0,H,"1,281 €",True,True,Grup A,Responsable de vendes,0.0,True,99990.0,11.8,11.2

Corregido la codificación con el "cp1252" y "latin1", el formato que falla es el número de hijos, dia, mes y año de nacimiento. Estos parámetros deberían ser números enteros y no decimales (aunque realmente es un texto).

A continuación, busco todos los valores únicos de cada categoria para buscar valores imposibles, si son todos "decimales" u otra opción.

In [335]:
dataset_s8['Nombre fills'].unique()

array(['3.0', '0.0', '4.0', '2.0', nan, '1.0', 0, 1], dtype=object)

In [336]:
dataset_s8['Dia de Naixement'].unique()

<ArrowStringArray>
['23.0',  '8.0', '27.0', '13.0', '29.0',  '1.0', '25.0', '32.0', '24.0',
 '22.0', '10.0', '21.0', '14.0', '19.0', '15.0', '16.0', '11.0', '18.0',
 '28.0',  '9.0',  '3.0',  '2.0',  '0.0', '20.0',  '4.0', '-5.0', '26.0',
 '30.0', '17.0',  '5.0', '12.0',  '6.0',  '7.0', '31.0']
Length: 34, dtype: str

In [337]:
dataset_s8['Mes de Naixement'].unique()

<ArrowStringArray>
[ '3.0', '11.0',  '4.0', '10.0',  '8.0',  '9.0',  '0.0',  '6.0',  '2.0',
  '7.0',  '5.0', '12.0',  '1.0', '99.0', '13.0']
Length: 15, dtype: str

In [338]:
dataset_s8['Any de Naixement'].unique()

<ArrowStringArray>
['1958.0', '1960.0', '1961.0', '1985.0', '1965.0', '1978.0', '1971.0',
 '1962.0', '1963.0', '1940.0', '1974.0', '1973.0', '1980.0', '2004.0',
 '1964.0', '2002.0', '1993.0', '1972.0', '1982.0', '1987.0', '1992.0',
 '1994.0', '1967.0', '1990.0', '3000.0', '2019.0', '1976.0', '2001.0',
 '1997.0', '1984.0', '1977.0', '1988.0', '1995.0', '1981.0', '1983.0',
 '2003.0', '1991.0', '2000.0', '1989.0', '2026.0', '1966.0', '1959.0',
 '1969.0', '1975.0', '1986.0', '1999.0', '1979.0', '1996.0', '1998.0',
 '1970.0', '1968.0']
Length: 51, dtype: str

También las columnas Fills, No Fills y Te_cotxe deberian ser boleanas. Incluso Gènere si consideramos que solamente hay 2 generos. Fills y No Fills se fusionarán con Nombre fills y Te cotxe se modificará en el ejercicio 3.

Visto los datos únicos de cada columna se procede a cambiarlos de formato. Primero a float al tener escritura con decimales y despues a int64 (evita errores si hay nulos). Modifico las 4 columnas

In [339]:
columnas = ['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Nombre fills']
dataset_s8[columnas] = dataset_s8[columnas].astype(float).astype('Int64')
print(dataset_s8['Dia de Naixement'].unique())
dataset_s8.info()

<IntegerArray>
[23,  8, 27, 13, 29,  1, 25, 32, 24, 22, 10, 21, 14, 19, 15, 16, 11, 18, 28,
  9,  3,  2,  0, 20,  4, -5, 26, 30, 17,  5, 12,  6,  7, 31]
Length: 34, dtype: Int64
<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Dia de Naixement            990 non-null    Int64
 6   Mes de Naixement            990 non-null    Int64
 7   Any de Naixement            990 non-null    Int64
 8   Gènere                      951 non-null    str
 9   Salari mensual              990 non-null    str
 10  Fills                       414 non-null    str
 11  No Fills                    575 non-null    str
 12  Grup Professional           990 non-null    str
 13  Càrrec                      990 non-null    str
 14  Nombre fills                696 non-null    Int64
 15  Te cotxe                    647 non-null    str
 16  Km anuals                   310 non-null    object
 17  Consum mitja L 100km        257 non-null    str
 18  Temperatura mitjana ciutat  923 non-null    str
dtypes: Int64(4), object(1), str(14)
memory usage: 236.7+ KB

El siguiente paso es crear columna de fecha. Hay que unificarlas en una misma columna.

Pandas tiene una función de convertir a fecha y trabajar con ellas. errors='coerce' hace que si hay una fecha imposible (31 de febrero) sea un NA.

Igualmente se comprueba que no existan fechas superiores a la fecha de hoy. En valores únicos de 'Any de Naixement' usuarios han puesto que han nacido en el 3000 (dificil sin viaje en el tiempo) o en el 2019 (bastante ilegal en el 2026 trabajar a esa edad en España).

En la función es posible definir la edad mínima por la que queremos invalidar una fecha. En España la edad legal para trabajar son 16 años.

Con errors='coerce' se declaran nulas las fechas que en:
- 'Dia de Naixement' tenian un 32 o -5
- 'Mes de Naixement' tenian 99 y 13
- 'Any de Naixement' como tal no tenian años imposibles, pero si no se han declarado nulas las fechas con años 3000 o 2019 con el errors se han declarado al ser superiores a la fecha actual.

In [340]:
def crear_fecha(dia, mes, año, edad_minima=16):
    fecha = pd.to_datetime(
        {
            'year': año,
            'month': mes,
            'day': dia
        },
        errors='coerce'
    )

    if edad_minima is not None:
        limite = pd.Timestamp.today() - pd.DateOffset(years=edad_minima)
        fecha[fecha > limite] = pd.NaT

    return fecha

In [341]:
dataset_s8['Data de Naixement'] = crear_fecha(
    dataset_s8['Dia de Naixement'],
    dataset_s8['Mes de Naixement'],
    dataset_s8['Any de Naixement']
)

dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23,3,1958,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3,True,32108.0,25.0,10.1,1958-03-23
4,Marc,Muñoz,48840994W,Espanya,Alacant,8,11,1960,H,"2,718 €",NaN,True,Grup C,Senior analyst,0,True,19496.0,10.4,18.7,1960-11-08
5,Noa,Serra,14308421X,Espanya,Alacant,27,4,1961,D,1358 euros,True,NaN,Grup A,Tècnic IT,4,NaN,NaN,NaN,16.7,1961-04-27
6,Pol,Gil,58586340F,Espanya,Sevilla,13,10,1985,H,"1,478 €",True,NaN,Grup B,Data Analyst,2,False,NaN,NaN,18.3,1985-10-13
7,David,Vila,82070937P,Espanya,Bilbao,29,11,1965,Dona,"1,284 €",NaN,True,Grup B,Administratiu,<NA>,True,NaN,11.8,13.1,1965-11-29
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1,8,1978,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0,NaN,NaN,NaN,19.9,1978-08-01
9,David,Gómez Vila,36998038E,Espanya,Palma,25,9,1971,D,"2,349 €",NaN,True,Grup B,Cap de projecte,<NA>,True,6196.0,10.6,17.8,1971-09-25
10,Carmen,López,47376585K,Espanya,Barcelona,8,9,1962,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4,True,20000,5.9,15.4,1962-09-08
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8,3,1963,D,"1,338 €",NaN,True,Grup B,Analista junior,0,False,NaN,NaN,7.6,1963-03-08
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32,0,1940,H,"1,450 €",True,NaN,Grup A,Senior analyst,4,False,NaN,NaN,20.1,NaT

In [342]:
fechas_invalidas = dataset_s8[dataset_s8['Data de Naixement'] > pd.Timestamp.today()]
fechas_invalidas

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat, Data de Naixement]
Index: []

Elimino las columnas de dia, mes y año ya que puedo obtener los mismos datos validos en la columna de fecha de aniversario.

In [343]:
dataset_s8 = dataset_s8.drop(['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement'], axis=1)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
620,Carlos,Álvarez,30918595C,Espanya,Girona,D,"1,201 €",True,NaN,Grup A,Tècnic IT,2,True,33895.0,7.7,12.2,2001-10-25
881,Aina,Serra Díaz,62061217F,Espanya,Madrid,F,985 €,True,NaN,Grup A,Analista junior,2,False,NaN,NaN,13.5,2002-06-13
570,Alba,Ferrer Díaz,64234848R,Espanya,Màlaga,D,tres mil,True,NaN,Grup A,Tècnic IT,2,NaN,NaN,NaN,14.8,1983-07-01
727,Xavier,García,77239032Q,Espanya,Alacant,D,937€,True,NaN,Grup A,Data Analyst,1,True,NaN,NaN,17.9,1981-04-18
380,Ilaria,Colombo,29151794Z,Itàlia,Bologna,H,"1,012 €",NaN,True,Grup A,Analista junior,<NA>,NaN,NaN,NaN,12.1,1975-04-01
387,Pau,Ribera Díaz,81965066H,Espanya,Barcelona,D,n/d,NaN,True,Grup B,Data Analyst,0,NaN,NaN,NaN,13.4,1989-02-23
911,David,Fernández,99490648V,Espanya,A Coruña,H,2056 euros,NaN,True,Grup B,Senior analyst,0,False,NaN,NaN,15.1,1979-08-10
599,Marc,Costa,35801896J,Espanya,Barcelona,D,1900€,NaN,True,Grup B,Data Analyst,<NA>,NaN,NaN,NaN,20.8,1993-09-19
618,Paolo,Ricci,64464528J,Itàlia,Genova,D,1.766 €,NaN,True,Grup B,Tècnic IT,<NA>,False,NaN,NaN,15.9,1998-06-07
535,Chloé,Michel,18365183X,França,Marseille,H,1380€,NaN,True,Grup B,Analista junior,<NA>,False,NaN,NaN,15.1,1986-11-23

## EJERCICIO 3: TRANSFORMACIONES NECESARIAS Y PREPARACIÓN DEL DATASET

Aspectos a revisar y transformar:

- ¿Los valores categóricos están normalizados y son consistentes?
- ¿Los valores nulos son coherentes con la información disponible?
- ¿Existe redundancia de variables que pueda generar problemas analíticos?
- ¿Las variables contextuales (como temperatura, salario) están completas y preparadas para el análisis?

Concretamente, tendrás que:

- Normalizar los valores categóricos para evitar ambigüedades (por ejemplo, valores que representan el mismo concepto pero están escritos de forma diferente).
- Revisar la coherencia de los valores nulos, asegurando que:
Las personas con kilometraje anual y consumo medio asociados disponen de coche. En los casos en que conste consumo medio pero no kilometraje anual, será necesario decidir cómo resolver esta incoherencia de forma justificada.
Las personas que tienen un valor en el número de hijos tienen efectivamente hijos.
- Unificar la información sobre hijos en una única columna, ya que mantener varias columnas con información complementaria no es óptimo y puede generar problemas analíticos (redundancia o multicolinealidad).
- Validar la temperatura media. En caso de que esa información falte, deberás imputarla utilizando un criterio razonable (por ciudad o por un nivel superior justificado).
- Revisar e imputar los salarios faltantes, aplicando criterios analíticos coherentes (como cargo, grupo profesional, ciudad, género o franja de edad).

In [344]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
866,Paolo,Barbieri Romano,60603699M,Itàlia,Firenze,M,"1,804 €",NaN,True,Grup C,Administratiu,<NA>,True,6369.0,0.5,11.3,1980-07-02
844,Élise,Robert,54519864D,França,Lille,H,"2,225 €",True,True,Grup C,Analista,0,True,80000,12.4,12.0,1969-09-09
816,Riccardo,Mancini Russo,84908042K,Itàlia,Genova,H,"1,319 €",NaN,True,Grup B,Responsable de vendes,0,True,43088.0,NaN,15.2,1990-11-20
605,Marta,Sánchez Ramos,13711597H,Espanya,Valladolid,NC,1844€,NaN,True,Grup C,Administratiu,0,True,80000,13.5,10.8,1978-07-10
19,Sara,Hernández Costa,91363974Q,Espanya,València,Home,982 €,NaN,True,Grup A,Analista junior,0,NaN,NaN,NaN,15.8,2004-06-14
489,Alba,Roca,78045733K,Espanya,Alacant,Dona,"1,336 €",NaN,NaN,Grup A,Cap de projecte,<NA>,True,12431.0,0.5,17.2,NaT
504,Erik,Bakke,79291785G,Noruega,Oslo,F,"1,906 €",True,NaN,Grup B,Responsable de vendes,1,NaN,NaN,NaN,7.1,1961-12-07
432,Lucía,Hernández,61268618C,Espanya,Bilbao,D,"2,290 €",NaN,True,Grup B,Cap de projecte,0,True,65950,NaN,15.0,1995-02-24
362,Laia,Ribera,52445278T,Espanya,Tarragona,D,mil vuit-cents,NaN,True,Grup B,Tècnic IT,<NA>,True,80000,5.7,15.1,1984-09-15
646,Nicolas,David,92727823A,França,Marseille,D,2936 euros,NaN,True,Grup D,Analista,0,False,NaN,NaN,NaN,2000-04-03

### Valores categóricos

Tomo como valores categóricos "Gènere", "Te_cotxe", "Grup Professional" y "Càrrec". Compruebo los valores únicos de cada uno.

Gènere tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo. Después cambiar formato a boolean

In [345]:
dataset_s8['Gènere'].unique()

<ArrowStringArray>
['Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A']
Length: 9, dtype: str

Te cotxe es correcto. Solo hay que cambiar formato a boolean

In [346]:
dataset_s8["Te cotxe"].unique()

<ArrowStringArray>
['True', nan, 'False']
Length: 3, dtype: str

Grup Professional se deja así tal cual. Las categorias están bien escritas.

In [347]:
dataset_s8['Grup Professional'].unique()

<ArrowStringArray>
['Grup B', 'Grup C', 'Grup A', 'Grup D']
Length: 4, dtype: str

Càrrec tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo.

Una vez estandarizado se comparará vs Grup Professional si todas coinciden o hay discrepancias

In [348]:
dataset_s8['Càrrec'].unique()

<ArrowStringArray>
[      'Cap de projecte',        'Senior analyst',             'Tècnic IT',
          'Data Analyst',         'Administratiu', 'Responsable de vendes',
       'Analista junior',          'Project lead',                'Admin.',
               'Analyst',              'Analista',          'Data analyst',
       'Cap de Projecte']
Length: 13, dtype: str

#### Valores categóricos: Gènere

Antes de comenzar la estandarización de la columba Gènere, cuento cuantas filas hay nulas en la columna y cuantos registros hay por cada género especificado por el usuario. De este modo puedo comprobar después que se haya completado la estandarización completamente.

In [349]:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')
dataset_s8.groupby('Gènere').size()

Hay: 39 filas de género nulas y 951 no nulas

Gènere
A        24
D       320
Dona    118
F       107
H       274
Home     51
M        34
NC       23
dtype: int64

Creo un diccionario para estandarizar los valores de 'Gènere'. De 'Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A' no se modificarán los nan, 'NC' y 'A'. Al hacer la transformación se borrarán. Los demás se asigna a 'Dona' o 'Home'.

No nulos hay 951 que se le restarán las 47 de 'A' y 'NC'. Quedarán 904 no nulos y 86 nulos si no falla la calculadora.

In [350]:
dicc_genere = {
    'Dona':'Dona', 
    'H': 'Home', 
    'D': 'Dona', 
    'F': 'Dona', 
    'Home': 'Home', 
    'M': 'Home', 
}

def estandarizar(elemento, diccionario):
    for categoria in diccionario:
        if elemento == categoria:
            return diccionario[categoria]

dataset_s8['Gènere'] = dataset_s8['Gènere'].apply(lambda x: estandarizar(x, dicc_genere))

#Aprovecho el mismo código de antes:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')


dataset_s8.groupby('Gènere').size()

Hay: 86 filas de género nulas y 904 no nulas

Gènere
Dona    545
Home    359
dtype: int64

#### Valores categóricos: Té cotxe

In [351]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
154,Anna,Ribera Ruiz,59988144T,Espanya,Zaragoza,Dona,845 €,NaN,True,Grup A,Administratiu,0,True,50000,0.5,12.8,1988-05-29
422,Marta,Díaz Ribera,98084362Z,Espanya,Zaragoza,Home,"2,368 €",NaN,True,Grup C,Data Analyst,0,False,NaN,NaN,12.0,1975-02-15
85,Maja,Berg Johnsen,50308572Q,Noruega,Bergen,Dona,1133€,NaN,True,Grup A,Cap de projecte,0,False,NaN,NaN,-5.0,2000-02-24
467,Sofie,Johnsen,59943747Z,Noruega,Tromsø,Dona,858€,NaN,True,Grup A,Administratiu,<NA>,False,NaN,NaN,0.0,1969-10-13
591,Katharina,Schröder Wolf,91877605Z,Alemanya,München,Dona,958 €,True,NaN,Grup A,Data Analyst,3,False,NaN,NaN,8.7,1965-09-24
848,Marco,Rossi Lombardi,62597519M,Itàlia,Napoli,Dona,"2,065 €",True,NaN,Grup C,Data Analyst,1,NaN,NaN,NaN,42.0,1962-10-13
518,Elias,Lie,12781968G,Noruega,Trondheim,Home,"1,139 €",True,NaN,Grup A,Tècnic IT,1,False,NaN,NaN,3.9,1991-12-21
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,Home,"1,450 €",True,NaN,Grup A,Senior analyst,4,False,NaN,NaN,20.1,NaT
18,Carmen,Hernández Serra,36786211Z,Espanya,Tarragona,Home,"1,336 €",True,NaN,Grup B,Administratiu,3,True,65950,NaN,NaN,1960-08-08
254,Camille,Fournier,52746321P,França,Lyon,Home,"1,261 €",True,NaN,Grup A,Data analyst,3,False,NaN,NaN,8.1,1992-06-18

Para la columna 'Té cotxe' el objetivo es convertirla en tipo boolean para que 0 = no coche (False) y 1 = si coche (True).

Igualmente se comprobará si hay valor en Km anuals o Consum mitja L 100km. Si tiene registro en alguna de las columnas se pondrá como True.

In [352]:
dataset_s8['Te cotxe'] = dataset_s8['Te cotxe'].astype(bool)
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Gènere                      904 non-null    str
 6   Salari mensual              990 non-null    str
 7   Fills                       414 non-null    str
 8   No Fills                    575 non-null    str
 9   Grup Professional           990 non-null    str
 10  Càrrec                      990 non-null    str
 11  Nombre fills                696 non-null    Int64
 12  Te cotxe                    990 non-null    bool
 13  Km anuals                   310 non-null    object
 14  Consum mitja L 100km        257 non-null    str
 15  Temperatura mitjana ciutat  923 non-null    str
 16  Data de Naixement           913 non-null    datetime64[us]
dtypes: Int64(1), bool(1), datetime64[us](1), object(1), str(13)
memory usage: 210.7+ KB

Comprobamos valores únicos de Km anual y Consum mitja L 100km para echar un ojo a los datos. A simple vista son numeros en formato str, por lo que después del proceso de 'Té cotxe' se transformarán en enteros o decimales.

In [353]:
dataset_s8['Consum mitja L 100km'].unique()

<ArrowStringArray>
['25.0', '10.4',    nan, '11.8', '10.6',  '5.9',  '7.7', '12.9', '12.2',
  '0.5',  '7.4', '12.0', '11.0',  '7.3',  '7.0', '11.7',  '7.6', '11.5',
  '6.1', '12.7', '10.1', '10.2',  '6.7',  '7.1', '13.6',  '9.6', '13.9',
  '8.0',  '4.7',  '5.0', '10.5',  '7.8', '13.4',  '6.2', '13.8', '11.6',
 '11.4',  '8.8',  '8.7',  '5.8',  '5.4',  '5.7',  '6.8', '10.8', '13.3',
  '4.9', '12.1', '11.2', '13.0',  '9.8',  '4.6', '14.0',  '4.8',  '9.2',
 '13.5', '12.5',  '8.2',  '4.5', '13.2',  '6.6',  '5.1',  '9.0',  '4.1',
 '13.7', '10.3', '12.8',  '8.4', '10.7', '10.0', '12.4', '13.1',  '6.4',
  '6.5',  '8.6',  '8.3', '12.6',  '4.4',  '5.6',  '5.5',  '8.9',  '6.9',
  '5.3',  '9.1',  '9.4']
Length: 84, dtype: str

In [354]:
dataset_s8['Km anuals'].unique()

array(['32108.0', '19496.0', nan, '6196.0', 20000, '14178.0', '10800.0',
       '6931.0', '38248.0', 65950, 80000, '64444.0', '22384.0',
       '116927.0', 50000, '78064.0', '114730.0', '60856.0', '29300.0',
       '113964.0', '39561.0', 65983, '29386.0', '42398.0', '76180.0',
       '106611.0', '35142.0', '19232.0', '23728.0', '3920.0', '23206.0',
       '5776.0', '13870.0', '104603.0', '37506.0', '99990.0', '67841.0',
       '59507.0', '48621.0', '27526.0', '62723.0', '26866.0', 70000,
       1000000, '5252.0', '81945.0', 30000, '6283.0', '113059.0', '0.0',
       '4103.0', '100054.0', '56135.0', '30452.0', '9639.0', '14109.0',
       '49000.0', '87108.0', '13833.0', '27752.0', '54025.0', '15579.0',
       '12947.0', '43566.0', '42512.0', '72237.0', '40723.0', '6140.0',
       '118147.0', '60652.0', 40000, '21069.0', '94969.0', '11362.0',
       '31309.0', '86060.0', '95003.0', '57089.0', '115098.0', '21422.0',
       '71500.0', '54623.0', '53463.0', '11346.0', '44565.0', '23129.0',
       '3936.0', '14527.0', '42899.0', '16390.0', '8516.0', '14892.0',
       '5584.0', '12431.0', '13407.0', '29278.0', '18378.0', '21062.0',
       '74741.0', '28115.0', '26936.0', '113145.0', '2938.0', '93114.0',
       '111435.0', '8460.0', '67158.0', '80657.0', '44563.0', '107311.0',
       '33895.0', '84895.0', '22880.0', '11090.0', '11169.0', '29434.0',
       '62991.0', '114489.0', '32431.0', '18402.0', '74348.0', '96645.0',
       '99638.0', '28988.0', '60905.0', '29952.0', '107127.0', '28726.0',
       '-50.0', '6377.0', '45301.0', '99431.0', '77960.0', '81381.0',
       '56365.0', '116654.0', '52646.0', '16998.0', '29847.0', '53342.0',
       '52327.0', '4934.0', '43088.0', '13608.0', '22166.0', '29464.0',
       '113111.0', '32672.0', '6369.0', '30481.0', '115076.0', '36221.0',
       '82014.0', '32217.0', '25193.0', '109099.0', '81219.0', '24307.0',
       '110775.0', '17246.0', '50370.0', '9017.0', '7861.0', '97162.0',
       '56745.0', '116027.0', '50453.0', '27921.0', '35591.0'],
      dtype=object)

Creo una nueva columna de coche calculado a partir de una condificon de si km anuals o consumo tienen valor generará True o False.

Utilizo fillna("") para substituir las filas sin datos para que no de un falso positivo.
ne("") es un not equal o != pero en metodo para pandas. Busca una celca vacía "".

In [355]:
dataset_s8['Te cotxe calculat'] = dataset_s8['Km anuals'].fillna("").ne("") | dataset_s8['Consum mitja L 100km'].fillna("").ne("")
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat
182,Sergio,Ramos Gómez,82890984V,Espanya,Girona,Dona,"1,549 €",True,NaN,Grup B,Tècnic IT,2,True,NaN,NaN,15.3,1990-03-14,False
55,Marina,Vidal,24524825B,Espanya,Màlaga,Dona,1647 euros,NaN,True,Grup B,Administratiu,0,True,NaN,NaN,19.0,1988-04-28,False
626,Alessia,Gallo,55919735G,Itàlia,Genova,Dona,"2,212 €",True,NaN,Grup C,Administratiu,4,True,22880.0,4.1,15.9,1985-07-23,True
38,Hugo,Pujol,83715012G,Espanya,Màlaga,Dona,"1,974 €",NaN,True,Grup B,Cap de projecte,0,True,NaN,NaN,19.1,1961-04-09,False
1000,Jordi,Hernández,67755039Y,Espanya,Zaragoza,Dona,"1,074 €",NaN,NaN,Grup A,Data Analyst,1,True,80000,12.0,12.0,1961-10-12,True
502,Aina,Casals,86294869K,Espanya,Valladolid,Home,"1,342 €",NaN,NaN,Grup B,Administratiu,<NA>,True,NaN,NaN,11.1,1958-02-10,False
435,David,Serra Gil,49827566A,Espanya,Barcelona,Home,"1,947 €",True,NaN,Grup C,Tècnic IT,3,True,NaN,NaN,14.6,1960-02-18,False
791,Hannah,Fischer Wolf,14098443W,Alemanya,Leipzig,Home,"1,034 €",NaN,True,Grup A,Tècnic IT,<NA>,True,NaN,NaN,12.5,NaT,False
565,Carlos,Ferrer,18169177Y,Espanya,Girona,Dona,"2,050 €",NaN,True,Grup B,Senior analyst,0,True,NaN,NaN,14.9,1966-09-10,False
357,Carlos,Costa,45079216E,Espanya,Zaragoza,Dona,"1,591 €",True,True,Grup B,Responsable de vendes,0,True,NaN,NaN,10.9,2001-06-21,False

Compruebo si hay alguna incongruencia con Te cotxe vs la columna calculada

In [356]:
coche_falso = dataset_s8['Te cotxe'] != dataset_s8['Te cotxe calculat']
coche_falso.value_counts()

True     678
False    312
Name: count, dtype: int64

Hay 312 que son iguales y 678 que la columna Te cotxe y la calculada son diferentes. Compruebo la cantidad de nulos que hay en Km anuals y Consum mitja L 100km.

In [357]:
dataset_s8.isna().sum()

2
Nom                             0
Cognoms                         0
DNI                             0
País d'origen                   0
Ciutat                          0
Gènere                         86
Salari mensual                  0
Fills                         576
No Fills                      415
Grup Professional               0
Càrrec                          0
Nombre fills                  294
Te cotxe                        0
Km anuals                     680
Consum mitja L 100km          733
Temperatura mitjana ciutat     67
Data de Naixement              77
Te cotxe calculat               0
dtype: int64

Al tener una cantidad importante de nulos en ambas columnas (más de la mitad) opto por dar como correcta la columna de 'Te cotxe calculat'. Por lo tanto, borro la columna 'Te cotxe' y mantengo la otra

In [358]:
dataset_s8.drop(columns='Te cotxe',inplace=True)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat
895,Alessandro,Costa,93540199D,Itàlia,Genova,Dona,1310€,NaN,True,Grup B,Data Analyst,0,NaN,NaN,13.5,1999-07-06,False
6,Pol,Gil,58586340F,Espanya,Sevilla,Home,"1,478 €",True,NaN,Grup B,Data Analyst,2,NaN,NaN,18.3,1985-10-13,False
526,Marc,Ferrer,20402470N,Espanya,Las Palmas de Gran Canaria,NaN,929€,True,NaN,Grup A,Data Analyst,4,50000,0.5,20.3,1964-07-23,True
234,Jordi,Álvarez,18067834D,Espanya,Valladolid,Dona,"2,184 €",NaN,NaN,Grup B,Senior analyst,0,NaN,NaN,15.0,1960-05-06,False
100,Chiara,Colombo Ferrari,29374563Z,Itàlia,Bologna,Dona,"2,166 €",True,NaN,Grup C,Analista,3,NaN,NaN,10.8,1969-09-03,False
954,Aina,Moreno,35382259C,Espanya,Girona,Dona,"2,179 €",True,NaN,Grup B,Cap de projecte,2,NaN,NaN,-5.0,1977-03-01,False
63,Núria,Navarro,47969333N,Espanya,Girona,Home,"2,125 €",NaN,NaN,Grup B,Tècnic IT,<NA>,NaN,25.0,NaN,1981-06-30,True
610,Julien,Moreau Durand,40651547B,França,Toulouse,Dona,1099€,True,NaN,Grup A,Tècnic IT,4,NaN,NaN,-10.0,1979-03-13,False
555,Adrià,Ribera,99152055K,Espanya,Sevilla,Home,"1,698 €",True,NaN,Grup B,Project lead,4,NaN,NaN,NaN,1981-11-04,False
934,Marco,Russo Lombardi,11110324P,Itàlia,Firenze,Home,"1,529 €",NaN,True,Grup B,Data Analyst,0,NaN,NaN,15.0,1966-08-07,False

El siguiente paso es convertir a decimales km anuals y consum mitja L 100km.

In [359]:
dataset_s8['Km anuals'] = dataset_s8['Km anuals'].astype(float)
dataset_s8['Consum mitja L 100km'] = dataset_s8['Consum mitja L 100km'].astype(float)
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Gènere                      904 non-null    str
 6   Salari mensual              990 non-null    str
 7   Fills                       414 non-null    str
 8   No Fills                    575 non-null    str
 9   Grup Professional           990 non-null    str
 10  Càrrec                      990 non-null    str
 11  Nombre fills                696 non-null    Int64
 12  Km anuals                   310 non-null    float64
 13  Consum mitja L 100km        257 non-null    float64
 14  Temperatura mitjana ciutat  923 non-null    str
 15  Data de Naixement           913 non-null    datetime64[us]
 16  Te cotxe calculat           990 non-null    bool
dtypes: Int64(1), bool(1), datetime64[us](1), float64(2), str(12)
memory usage: 209.7 KB

Ahora compruebo la distribución de km y consumo. Si ambos estan informados o si uno de los dos falla.

In [360]:
print("Ambos informados:",
      ((dataset_s8['Km anuals'].notna()) &
       (dataset_s8['Consum mitja L 100km'].notna())).sum())

print("Km si, consumo no:",
      ((dataset_s8['Km anuals'].notna()) &
       (dataset_s8['Consum mitja L 100km'].isna())).sum())

print("Km no, consumo si:",
      ((dataset_s8['Km anuals'].isna()) &
       (dataset_s8['Consum mitja L 100km'].notna())).sum())

Ambos informados: 255
Km si, consumo no: 55
Km no, consumo si: 2

Obtengo la desviación estandar, media, mediana, modo, maximo y minimo para las columnas Km anuals y Consum mitja L 100km

In [361]:
km_desviacion = dataset_s8['Km anuals'].std()
km_media = dataset_s8['Km anuals'].mean()
km_mediana = dataset_s8['Km anuals'].median()
km_mode = dataset_s8['Km anuals'].mode()
km_max = dataset_s8['Km anuals'].max()
km_min = dataset_s8['Km anuals'].min()
print(f"""Km anuals:
km desviacion = {km_desviacion}
km media = {km_media}
km mediana = {km_mediana}
km_mode = {km_mode}
km_max = {km_max}
km_min = {km_min}""")

Km anuals:
km desviacion = 62464.19789379955
km media = 56031.04516129032
km mediana = 55379.0
km_mode = 0    80000.0
Name: Km anuals, dtype: float64
km_max = 1000000.0
km_min = -50.0

In [362]:
consum_desviacion = dataset_s8['Consum mitja L 100km'].std()
consum_media = dataset_s8['Consum mitja L 100km'].mean()
consum_mediana = dataset_s8['Consum mitja L 100km'].median()
consum_mode = dataset_s8['Consum mitja L 100km'].mode()
consum_max = dataset_s8['Consum mitja L 100km'].max()
consum_min = dataset_s8['Consum mitja L 100km'].min()
print(f"""consum data:
consum desviacion = {consum_desviacion}
consum media = {consum_media}
consum mediana = {consum_mediana}
consum mode = {consum_mode}
consum max = {consum_max}
consum min = {consum_min}""")

consum data:
consum desviacion = 8.832870803940532
consum media = 11.070038910505836
consum mediana = 9.8
consum mode = 0    25.0
Name: Consum mitja L 100km, dtype: float64
consum max = 25.0
consum min = 0.5

Hay una gran desviación en ambas columnas (casi más que el valor del promedio/media).

Los maximos y mínimos en ambas columnas son demasiado extremos. Incluso hay negativos.

Primero calculo la correlación.

In [363]:
dataset_s8[['Km anuals', 'Consum mitja L 100km']].corr()

2                     Km anuals  Consum mitja L 100km
2
Km anuals               1.00000               0.13008
Consum mitja L 100km    0.13008               1.00000

Al tener una asociación pequeña, obtengo metricas para cada percentil para ver como son los datos

In [364]:
dataset_s8.groupby(pd.qcut(dataset_s8['Km anuals'], q=4))['Consum mitja L 100km'].agg(['mean','median','std'])

                           mean  median       std
Km anuals
(-50.001, 22508.0]     8.947170    8.20  5.986318
(22508.0, 55379.0]    11.059701   10.20  9.850182
(55379.0, 80000.0]    12.065686   11.45  9.220054
(80000.0, 1000000.0]  10.978788    9.40  8.987935

In [365]:
dataset_s8.groupby(pd.qcut(dataset_s8['Consum mitja L 100km'], q=4))['Km anuals'].agg(['mean','median','std'])

                              mean   median            std
Consum mitja L 100km
(0.499, 4.6]          56512.276923  53342.0   27854.640887
(4.6, 9.8]            50127.359375  41256.0   32011.173308
(9.8, 13.7]           56468.873016  65983.0   33683.085908
(13.7, 25.0]          77844.253968  80000.0  121121.637917

La desviación es bastante grande, por lo que muestra una gran variabilidad de dados. Una posibilidad es rellenar a partir de media, desviación u otros, pero empujaría la estadística hacia lo standard. Los km anuales son muy variables debido a que un usuario puede vivir a 10km o 100km de su trabajo. El consumo es igual de variable dependiendo de las características del vehículo y el estílo de conducción del usuario.

Teniendo en cuenta estos datos, opto solamente por borrar los valores negativos de km anual. Las filas sin datos no las modifico.

In [366]:
dataset_s8 = dataset_s8[dataset_s8['Km anuals']>=0]
dataset_s8['Km anuals'].min()

np.float64(0.0)

#### Valores categóricos: Càrrec

En Càrrec hay que estandarizar los nombres de los cargos. Al estandarizarlo, es posible que cada grupo profesional esté relacionado con un cargo (o no). Ya dependerá de la organización de la empresa.

In [367]:
dataset_s8.groupby(['Càrrec','Grup Professional']).size()

Càrrec                 Grup Professional
Admin.                 Grup A                1
                       Grup B                3
Administratiu          Grup A                9
                       Grup B               13
                       Grup C                7
                       Grup D                2
Analista               Grup A               16
                       Grup B               16
                       Grup C                6
Analista junior        Grup A               21
                       Grup B                8
                       Grup C                7
                       Grup D                2
Analyst                Grup B                2
Cap de Projecte        Grup A                1
                       Grup B                1
Cap de projecte        Grup A               10
                       Grup B               13
                       Grup C                6
                       Grup D                3
Data Analyst           Grup A               22
                       Grup B               15
                       Grup C                1
                       Grup D                1
Data analyst           Grup A                1
                       Grup B                1
                       Grup C                1
Project lead           Grup A                4
                       Grup B                2
                       Grup C                1
Responsable de vendes  Grup A               17
                       Grup B               14
                       Grup C                4
                       Grup D                1
Senior analyst         Grup A               15
                       Grup B               15
                       Grup C                3
                       Grup D                2
Tècnic IT              Grup A               22
                       Grup B               11
                       Grup C                2
                       Grup D                2
dtype: int64

Visto que muchos puestos son lo mismo pero escritos de distinta forma o idiomas, primero estandarizo. Para ello necesito los valores únicos de Càrrec y aprovecho la función que he creado antes (estandarizar)

In [368]:
dataset_s8.groupby('Càrrec').size()

Càrrec
Admin.                    4
Administratiu            31
Analista                 38
Analista junior          38
Analyst                   2
Cap de Projecte           2
Cap de projecte          32
Data Analyst             39
Data analyst              3
Project lead              7
Responsable de vendes    36
Senior analyst           35
Tècnic IT                37
dtype: int64

Se igualan:
- Cap de projecte, Cap de Projecte y Project lead como Cap de projecte
- Admin. y Administratiu como Administratiu
- Data Analyst, Data analyst, Analista, Senior analyst y Analista jr como Analista. Al final, independientemente del grado de especialización o conocimientos todos son analistas.

Se mantienen:
- Tècnic IT
- Responsable de vendes

Para no perder datos, se crea una columna "Categoria càrrec" donde se indique jr y senior o data analyst.

In [369]:
diccionario_carrec = {
    'Cap de projecte': 'Cap de projecte',
    'Senior analyst':'Analista',
    'Responsable de vendes':'Responsable de vendes',
    'Administratiu':'Administratiu',
    'Project lead':'Cap de projecte',
    'Analista junior':'Analista',
    'Admin.':'Administratiu',
    'Tècnic IT':'Tècnic IT',
    'Analista':'Analista',
    'Data Analyst':'Analista',
    'Analyst':'Analista',
    'Data analyst':'Analista',
    'Cap de Projecte':'Cap de projecte'
}

diccionario_categoria = {
    'Senior analyst': 'Analista senior',
    'Analista junior': 'Analista junior',
    'Data analyst': 'Analista de dades',
    'Data Analyst': 'Analista de dades',
    'Analista': 'Analista'
}

# 2 maneras diferentes de agregar datos con un diccionario.
dataset_s8['Categoria càrrec'] = dataset_s8['Càrrec'].apply(lambda x: estandarizar(x, diccionario_categoria))
dataset_s8['Càrrec'] = dataset_s8['Càrrec'].map(diccionario_carrec)

In [370]:
dataset_s8.groupby(['Categoria càrrec','Càrrec']).size()

Categoria càrrec   Càrrec
Analista           Analista    38
Analista de dades  Analista    42
Analista junior    Analista    38
Analista senior    Analista    35
dtype: int64

In [371]:
dataset_s8.groupby('Càrrec').size()

Càrrec
Administratiu             35
Analista                 155
Cap de projecte           41
Responsable de vendes     36
Tècnic IT                 37
dtype: int64

Estandarizado el nombre del càrrec, lo volvemos a confrontar con el grup profesional.

In [372]:
dataset_s8.groupby(['Càrrec','Grup Professional']).size()

Càrrec                 Grup Professional
Administratiu          Grup A               10
                       Grup B               16
                       Grup C                7
                       Grup D                2
Analista               Grup A               75
                       Grup B               57
                       Grup C               18
                       Grup D                5
Cap de projecte        Grup A               15
                       Grup B               16
                       Grup C                7
                       Grup D                3
Responsable de vendes  Grup A               17
                       Grup B               14
                       Grup C                4
                       Grup D                1
Tècnic IT              Grup A               22
                       Grup B               11
                       Grup C                2
                       Grup D                2
dtype: int64

Aún existen variedad de Grup Professional para un mismo cargo, pero se observa que la mayoría están en el grupo professional A-B. Dependerá del rango de edad la permanencia a cada uno. Para averiguarlo creo un rango de edad a partir de la edad

In [373]:
dataset_s8['Edat'] =  (pd.Timestamp.today().year - dataset_s8['Data de Naixement'].dt.year )
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat
419,Nicolas,David,92716588Y,França,Marseille,Dona,1104€,True,NaN,Grup A,Analista,1,57089.0,11.2,13.6,NaT,True,Analista,NaN
423,Oriol,Soler,27103900X,Espanya,Sevilla,Home,1450 euros,True,NaN,Grup A,Tècnic IT,1,80000.0,13.0,22.6,1989-09-16,True,NaN,37.0
844,Élise,Robert,54519864D,França,Lille,Home,"2,225 €",True,True,Grup C,Analista,0,80000.0,12.4,12.0,1969-09-09,True,Analista,57.0
339,Marc,Ramos,71355706A,Espanya,Girona,Dona,1121 euros,NaN,NaN,Grup A,Analista,<NA>,12947.0,13.6,14.8,1961-08-26,True,Analista junior,65.0
195,Pol,Sánchez,96873663J,Espanya,Màlaga,Home,"2,405 €",NaN,True,Grup C,Analista,0,80000.0,0.5,18.3,1971-10-06,True,Analista,55.0
303,Lucía,Domènech Álvarez,25145863X,Espanya,Madrid,NaN,920 €,True,NaN,Grup A,Analista,3,80000.0,25.0,14.9,1990-04-14,True,Analista junior,36.0
684,Nil,López Costa,52138595R,Espanya,Màlaga,Dona,"1,669 €",NaN,True,Grup B,Tècnic IT,<NA>,65950.0,0.5,22.9,2000-02-25,True,NaN,26.0
293,Nora,Pettersen,86003182L,Noruega,Trondheim,Dona,"2,626 €",NaN,True,Grup C,Tècnic IT,<NA>,30452.0,0.5,2.4,1965-03-29,True,NaN,61.0
733,Claudia,Gil Ferrer,55297384F,Espanya,València,Home,1.789 €,NaN,True,Grup B,Responsable de vendes,0,29952.0,9.2,20.3,1981-11-01,True,NaN,45.0
814,Oriol,Vidal,70319344K,Espanya,Màlaga,Dona,1203 euros,NaN,True,Grup B,Analista,<NA>,52327.0,25.0,16.3,1964-05-27,True,Analista de dades,62.0

In [374]:
def rango_edad(edad):
    if 16 <= edad <= 24:
        return '16-24'
    elif 25 <= edad <= 35:
        return '25-35'
    elif 36 <= edad <= 45:
        return '36-45'
    elif 46 <= edad <= 55:
        return '46-55'
    elif edad >= 56:
        return '56 +'

In [375]:
dataset_s8['Grup edat'] = dataset_s8['Edat'].apply(rango_edad)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
678,Alejandro,Navarro,50530014N,Espanya,Tarragona,Dona,"1,947 €",NaN,True,Grup B,Analista,<NA>,50000.0,10.7,-5.0,1966-11-26,True,Analista senior,60.0,56 +
329,Alejandro,Fernández,17453784W,Espanya,A Coruña,Dona,1.403 €,True,True,Grup B,Tècnic IT,0,30000.0,12.9,11.1,1976-06-26,True,NaN,50.0,46-55
303,Lucía,Domènech Álvarez,25145863X,Espanya,Madrid,NaN,920 €,True,NaN,Grup A,Analista,3,80000.0,25.0,14.9,1990-04-14,True,Analista junior,36.0,36-45
139,Marco,Rossi Ricci,94597104C,Itàlia,Torino,NaN,771 €,True,NaN,Grup A,Analista,4,23728.0,25.0,12.5,1983-06-22,True,Analista junior,43.0,36-45
626,Alessia,Gallo,55919735G,Itàlia,Genova,Dona,"2,212 €",True,NaN,Grup C,Administratiu,4,22880.0,4.1,15.9,1985-07-23,True,NaN,41.0,36-45
13,Joana,Torres Díaz,82772208R,Espanya,Valladolid,Dona,982 €,NaN,True,Grup A,Administratiu,0,14178.0,7.7,38.0,1961-10-24,True,NaN,65.0,56 +
873,Felix,Müller,63102334D,Alemanya,Frankfurt,NaN,"2,025 €",NaN,True,Grup B,Cap de projecte,<NA>,20000.0,8.9,10.2,1984-09-15,True,NaN,42.0,36-45
89,Aina,Ferrer,85432781E,Espanya,Valladolid,Dona,"1,436 €",True,NaN,Grup A,Cap de projecte,1,65983.0,11.7,15.9,1992-05-30,True,NaN,34.0,25-35
392,Manon,David Lefebvre,82101452G,França,Lille,Dona,985 €,NaN,NaN,Grup A,Analista,<NA>,60652.0,25.0,9.8,1963-05-20,True,Analista de dades,63.0,56 +
363,Marie,Simon,17305854X,França,Paris,Home,1507€,NaN,True,Grup A,Analista,<NA>,20000.0,5.7,12.2,1988-04-11,True,Analista senior,38.0,36-45

In [376]:
dataset_s8['Grup edat'].value_counts(dropna=False)

Grup edat
56 +     86
36-45    63
25-35    59
46-55    55
NaN      24
16-24    17
Name: count, dtype: int64

Para hacernos una idea aproximada, agrupamos los grupos profesionales con los grupos de edad que se han creado.

In [377]:
dataset_s8.groupby(['Grup Professional',dataset_s8['Grup edat'].fillna("No definit")]).size()

Grup Professional  Grup edat
Grup A             16-24         11
                   25-35         29
                   36-45         27
                   46-55         23
                   56 +          38
                   No definit    11
Grup B             16-24          5
                   25-35         23
                   36-45         24
                   46-55         21
                   56 +          32
                   No definit     9
Grup C             16-24          1
                   25-35          4
                   36-45          7
                   46-55         10
                   56 +          13
                   No definit     3
Grup D             25-35          3
                   36-45          5
                   46-55          1
                   56 +           3
                   No definit     1
dtype: int64

### Valores nulos

In [378]:
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 304 entries, 3 to 1004
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         304 non-null    str
 1   Cognoms                     304 non-null    str
 2   DNI                         304 non-null    str
 3   País d'origen               304 non-null    str
 4   Ciutat                      304 non-null    str
 5   Gènere                      279 non-null    str
 6   Salari mensual              304 non-null    str
 7   Fills                       121 non-null    str
 8   No Fills                    182 non-null    str
 9   Grup Professional           304 non-null    str
 10  Càrrec                      304 non-null    str
 11  Nombre fills                209 non-null    Int64
 12  Km anuals                   304 non-null    float64
 13  Consum mitja L 100km        255 non-null    float64
 14  Temperatura mitjana ciutat  285 non-null    str
 15  Data de Naixement           280 non-null    datetime64[us]
 16  Te cotxe calculat           304 non-null    bool
 17  Categoria càrrec            153 non-null    str
 18  Edat                        280 non-null    float64
 19  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(3), str(14)
memory usage: 74.3 KB

Las únicas columnas con nulos son las siguientes:

In [379]:
for col in dataset_s8.columns:
    if dataset_s8[col].isna().sum() > 0:
        print(col)

Gènere
Fills
No Fills
Nombre fills
Consum mitja L 100km
Temperatura mitjana ciutat
Data de Naixement
Categoria càrrec
Edat
Grup edat

Fills/No Fills ahora se fusionarán con Nombre fills. El resto tienen un número relativamente bajo de nulos (no más de 30 nulos). Excepto Categoria càrrec porque solo engloba al cargo Analista.

Los datos importantes para identificar a los usuarios es DNI que no tiene nulos ni duplicados.

### Valores redundantes

En este apartado es donde se juntarán Fills/No Fills con Nombre de Fills. Para contar cuantas veces aparece True/False en cada columna por valor único de Nombre fills hay que poner FIlls/No Fills boleanas.

In [380]:
dataset_s8['Fills'].unique()

<ArrowStringArray>
['True', nan]
Length: 2, dtype: str

In [381]:
dataset_s8['No Fills'].unique()

<ArrowStringArray>
[nan, 'True']
Length: 2, dtype: str

Necesitamos hacer un crosstab porque el agrupar por Nombre fills y contar cuantas veces sale Fills/No Fills no funciona correctamente.

In [382]:
pd.crosstab(
    dataset_s8['Nombre fills'],
    dataset_s8['No Fills'].isna()
)

No Fills      False  True
Nombre fills
0                90      2
1                 2     61
2                 3     17
3                 1     13
4                 1     19

In [383]:
pd.crosstab(
    dataset_s8['Nombre fills'],
    dataset_s8['Fills'].isna()
)

Fills         False  True
Nombre fills
0                 9     83
1                61      2
2                18      2
3                14      0
4                19      1

Teniendo en cuenta que la columna Nombre fills es la que tiene valor de referencia y es la verdad absoluta, Crosstab muestra que la mayoria de usuarios que pusieron que tenian 0 hijos, luego contestaron mal a Fills/No Fills.
El resto de personas con +1 hijos contestaron con sentido el formulario. 

Teniendo en cuenta que las personas que si tienen hijos pero han contestado 0 hijos (83 en la columna 'Fills' y 90 en 'No Fills') y la diferencia sería cambiar el total en +7 personas con hijos se opta por dejar la columna 'Nombre fills' tal y como está y borrar las columnas Fills y No Fills.

Aprovecho para darle un reset al indice

In [384]:
dataset_s8 = dataset_s8.drop(['Fills','No Fills'], axis=1).reset_index()
dataset_s8.sample(5)

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
100,339,Marc,Ramos,71355706A,Espanya,Girona,Dona,1121 euros,Grup A,Analista,<NA>,12947.0,13.6,14.8,1961-08-26,True,Analista junior,65.0,56 +
107,381,Anna,Puig,92279159M,Espanya,Valladolid,Dona,"1,222 €",Grup A,Tècnic IT,0,40723.0,25.0,9.8,2003-05-13,True,NaN,23.0,16-24
257,858,Alba,Muñoz,83683223Z,Espanya,Las Palmas de Gran Canaria,Dona,"1,644 €",Grup B,Analista,3,65950.0,0.5,22.1,1965-02-12,True,Analista junior,61.0,56 +
259,862,Camille,Fournier,43035177B,França,Marseille,Dona,1929 euros,Grup B,Analista,0,30000.0,25.0,10.4,1998-08-26,True,Analista de dades,28.0,25-35
19,61,Riccardo,Barbieri,93821894X,Itàlia,Venezia,Dona,1597€,Grup B,Administratiu,0,65950.0,NaN,13.8,1994-11-21,True,NaN,32.0,25-35

In [385]:
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       304 non-null    int64
 1   Nom                         304 non-null    str
 2   Cognoms                     304 non-null    str
 3   DNI                         304 non-null    str
 4   País d'origen               304 non-null    str
 5   Ciutat                      304 non-null    str
 6   Gènere                      279 non-null    str
 7   Salari mensual              304 non-null    str
 8   Grup Professional           304 non-null    str
 9   Càrrec                      304 non-null    str
 10  Nombre fills                209 non-null    Int64
 11  Km anuals                   304 non-null    float64
 12  Consum mitja L 100km        255 non-null    float64
 13  Temperatura mitjana ciutat  285 non-null    str
 14  Data de Naixement           280 non-null    datetime64[us]
 15  Te cotxe calculat           304 non-null    bool
 16  Categoria càrrec            153 non-null    str
 17  Edat                        280 non-null    float64
 18  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(3), int64(1), str(12)
memory usage: 68.4 KB

### Valores contextuales

#### Valores contextuales: Temperatura mitjana ciutat

Para comprobar los valores de temperatura mitjana, las cambio a formato float (temperatura con decimales puede existir). Viendo los valores únicos no puedo identidicar si hay números envueltos en string ('15.6') o si algún usuario ha puesto 'mucho frío' o 'quince y medio'. Esto se soluciona con un pd.to_numeric y error='cource' como se ha hecho anteriormente y los errores les asigna un NA. Para comprobar que no perdemos datos, se comparan los nulos del nuevo formato vs los datos originales.

In [386]:
dataset_s8['Temperatura mitjana ciutat'].unique()

<ArrowStringArray>
['10.1', '18.7', '17.8', '15.4', '38.0', '22.0', '12.4', '19.7',    nan,
  '8.8',
 ...
 '22.1', '10.4', '10.9',  '9.4', '10.5', '21.7', '13.3', '10.7', '10.6',
  '6.5']
Length: 129, dtype: str

In [387]:
temp_num = pd.to_numeric(dataset_s8['Temperatura mitjana ciutat'], errors='coerce')

dataset_s8.loc[temp_num.isna() & 
               dataset_s8['Temperatura mitjana ciutat'].notna()]

Empty DataFrame
Columns: [index, Nom, Cognoms, DNI, País d'origen, Ciutat, Gènere, Salari mensual, Grup Professional, Càrrec, Nombre fills, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat, Data de Naixement, Te cotxe calculat, Categoria càrrec, Edat, Grup edat]
Index: []

Al no existir nulos en formato float y datos en la original, es se suponer que no se han perdido datos. Hago la transformación definitiva.

In [388]:
dataset_s8['Temperatura mitjana ciutat'] = pd.to_numeric(dataset_s8['Temperatura mitjana ciutat'], errors='coerce')

In [389]:
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       304 non-null    int64
 1   Nom                         304 non-null    str
 2   Cognoms                     304 non-null    str
 3   DNI                         304 non-null    str
 4   País d'origen               304 non-null    str
 5   Ciutat                      304 non-null    str
 6   Gènere                      279 non-null    str
 7   Salari mensual              304 non-null    str
 8   Grup Professional           304 non-null    str
 9   Càrrec                      304 non-null    str
 10  Nombre fills                209 non-null    Int64
 11  Km anuals                   304 non-null    float64
 12  Consum mitja L 100km        255 non-null    float64
 13  Temperatura mitjana ciutat  285 non-null    float64
 14  Data de Naixement           280 non-null    datetime64[us]
 15  Te cotxe calculat           304 non-null    bool
 16  Categoria càrrec            153 non-null    str
 17  Edat                        280 non-null    float64
 18  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(4), int64(1), str(11)
memory usage: 67.3 KB

Miro los datos de cada ciudad con su temperatura. El promedio da valores bastante reales, pero el mínimo y máximo en algunos casos es imposible (-10 en Alicante nunca se ha registrado). Si estuviesemos hablando de temperatura maxima, minima o media de una ciudad en un dia podrían ser 99% reales.

Al ordenar por la desviación, a partir de >5 los valores mínimos y máximos son bastante irreales. En una simple búsqueda en internet Bourdeos tiene una temperatura mínima de 6ºC en invierno y 21.5ºC en verano (15ºC anual).

In [390]:
dataset_s8.groupby('Ciutat')['Temperatura mitjana ciutat'].describe().sort_values(by='std')

,count,mean,std,min,25%,50%,75%,max
Ciutat,,,,,,,,
Berlin,2.0,10.900000,0.282843,10.7,10.800,10.90,11.000,11.1
Paris,2.0,11.900000,0.424264,11.6,11.750,11.90,12.050,12.2
Stuttgart,3.0,12.400000,0.700000,11.7,12.050,12.40,12.750,13.1
Genova,5.0,16.160000,0.926283,15.2,15.900,15.90,16.100,17.7
Toulouse,3.0,14.100000,1.178983,13.1,13.450,13.80,14.600,15.4
Nice,2.0,15.550000,1.343503,14.6,15.075,15.55,16.025,16.5
Bergen,3.0,8.400000,1.345362,6.9,7.850,8.80,9.150,9.5
Lille,3.0,10.400000,1.400000,9.4,9.600,9.80,10.900,12.0
Las Palmas de Gran Canaria,11.0,20.736364,1.537057,18.4,19.650,21.30,21.950,22.7
Zaragoza,14.0,15.114286,1.640758,12.0,14.150,15.45,15.950,17.7
Frankfurt,2.0,11.400000,1.697056,10.2,10.800,11.40,12.000,12.6
Murcia,14.0,18.878571,1.705727,14.9,17.900,18.90,20.000,21.1
Madrid,19.0,15.289474,1.846286,11.6,14.600,15.00,16.300,19.0
Milano,5.0,13.240000,1.908664,10.6,12.600,12.80,14.900,15.3
Roma,5.0,16.420000,1.997999,14.2,15.100,16.00,17.600,19.2
Napoli,5.0,16.440000,2.016928,13.6,15.600,16.60,17.400,19.0
Oslo,6.0,7.666667,2.126656,4.8,6.350,7.55,9.275,10.3
Bilbao,20.0,13.820000,2.212310,9.9,12.925,13.80,15.425,18.2
Nantes,3.0,11.733333,2.218859,9.7,10.550,11.40,12.750,14.1
Marseille,2.0,12.000000,2.262742,10.4,11.200,12.00,12.800,13.6
A Coruña,13.0,14.200000,2.297825,11.1,12.900,13.90,15.500,19.3
Sevilla,9.0,19.555556,2.548093,15.2,17.500,19.20,21.700,22.6
València,11.0,17.490909,2.675614,12.6,16.200,18.00,19.350,21.3
Palma,16.0,17.606250,3.193007,10.9,15.375,17.90,19.625,22.3
Girona,13.0,13.630769,3.455041,8.1,11.300,13.20,16.500,19.4
Tarragona,18.0,15.483333,5.370754,-5.0,15.100,17.20,17.825,19.4
Màlaga,10.0,20.740000,6.350363,16.3,17.550,18.60,20.250,38.0
Barcelona,15.0,18.646667,8.012746,13.2,14.600,15.60,17.900,38.0
Bordeaux,4.0,7.450000,8.501568,-5.0,5.500,10.90,12.850,13.0
Valladolid,12.0,12.441667,9.614427,-5.0,9.800,10.80,14.450,38.0
Köln,2.0,2.250000,10.253048,-5.0,-1.375,2.25,5.875,9.5
Torino,5.0,19.360000,10.600142,12.5,13.600,15.00,17.700,38.0
Alacant,12.0,13.808333,11.183385,-10.0,16.975,18.45,19.025,20.9
Firenze,10.0,14.940000,11.399532,-5.0,11.950,14.20,15.975,42.0
Hamburg,1.0,4.600000,NaN,4.6,4.600,4.60,4.600,4.6
Leipzig,1.0,9.100000,NaN,9.1,9.100,9.10,9.100,9.1
München,1.0,8.000000,NaN,8.0,8.000,8.00,8.000,8.0
Tromsø,1.0,2.600000,NaN,2.6,2.600,2.60,2.600,2.6
Trondheim,1.0,2.400000,NaN,2.4,2.400,2.40,2.400,2.4
Venezia,1.0,13.800000,NaN,13.8,13.800,13.80,13.800,13.8

Se comprueban los outliers para las ciudades con >5 en std y el IQR inferior y superior para cada ciudad.

El objetivo es que las ciudades con outliers con >5 en std se le borren los valores que no estén entre el IQR inferior y IQR superior. Las temperaturas de una ciudad no son como el consumo de un vehículo que depende de sus características y cada usuario puede indicar un consumo muy variado. Las temperaturas en una misma ciudad no suelen variar. 

Por lo que se le asignará la mediana a las filas que no tengan temperatura registrada por el usuario y se substituirá los outliers por la mediana.

In [391]:
ciutat_q1 = dataset_s8.groupby('Ciutat')['Temperatura mitjana ciutat'].quantile(0.25)
ciutat_q3 = dataset_s8.groupby('Ciutat')['Temperatura mitjana ciutat'].quantile(0.75)
ciutat_iqr = ciutat_q3 - ciutat_q1
ciutat_inferior = ciutat_q1 - (1.5 * ciutat_iqr)
ciutat_inferior.to_dict()
ciutat_superior = ciutat_q3 + (1.5 * ciutat_iqr)
ciutat_superior.to_dict()

ciutat_desv = dataset_s8.groupby('Ciutat')['Temperatura mitjana ciutat'].std()

Creo una columna para cada parámetro y hacer una condición para seleccionar los outliers

In [392]:
dataset_s8['temp_inferior'] = dataset_s8['Ciutat'].map(ciutat_inferior)
dataset_s8['temp_superior'] = dataset_s8['Ciutat'].map(ciutat_superior)
dataset_s8['temp_desv'] = dataset_s8['Ciutat'].map(ciutat_desv)
dataset_s8.sample(5)

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,...,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat,temp_inferior,temp_superior,temp_desv
160,563,Hugo,Pujol,71649116H,Espanya,Bilbao,Home,1278 euros,Grup A,Analista,...,NaN,9.9,1970-06-16,True,Analista,56.0,56 +,9.1750,19.1750,2.212310
120,424,Gabriele,Rossi Greco,92894635G,Itàlia,Genova,Dona,"1,616 €",Grup B,Analista,...,13.4,17.7,1963-07-08,True,Analista de dades,63.0,56 +,15.6000,16.4000,0.926283
13,34,Adrià,Ferrer,64830300Z,Espanya,Barcelona,Home,927€,Grup A,Cap de projecte,...,12.0,38.0,1987-05-10,True,NaN,39.0,36-45,9.6500,22.8500,8.012746
148,496,Marina,Ribera,68589370R,Espanya,Palma,Dona,"1,385 €",Grup B,Analista,...,NaN,18.6,1980-04-11,True,Analista senior,46.0,46-55,9.0000,26.0000,3.193007
260,864,Elias,Pettersen Karlsen,48272885X,Noruega,Oslo,NaN,1.237 €,Grup A,Analista,...,10.4,10.3,1984-01-01,True,Analista de dades,42.0,36-45,1.9625,13.6625,2.126656

Compruebo cuantos valores se borrarán de cada ciudad

In [393]:
outliers_temp = ((dataset_s8['temp_desv'] > 5)    &
    ((dataset_s8['Temperatura mitjana ciutat'] < dataset_s8['temp_inferior'])
    |
    (dataset_s8['Temperatura mitjana ciutat'] > dataset_s8['temp_superior'])))
dataset_s8[outliers_temp]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,...,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat,temp_inferior,temp_superior,temp_desv
4,13,Joana,Torres Díaz,82772208R,Espanya,Valladolid,Dona,982 €,Grup A,Administratiu,...,7.7,38.0,1961-10-24,True,NaN,65.0,56 +,2.8250,21.4250,9.614427
13,34,Adrià,Ferrer,64830300Z,Espanya,Barcelona,Home,927€,Grup A,Cap de projecte,...,12.0,38.0,1987-05-10,True,NaN,39.0,36-45,9.6500,22.8500,8.012746
184,636,Chiara,Bianchi,89568937L,Itàlia,Firenze,Home,"1,815 €",Grup B,Analista,...,25.0,-5.0,1994-04-23,True,Analista senior,32.0,25-35,5.9125,22.0125,11.399532
198,678,Alejandro,Navarro,50530014N,Espanya,Tarragona,Dona,"1,947 €",Grup B,Analista,...,10.7,-5.0,1966-11-26,True,Analista senior,60.0,56 +,11.0125,21.9125,5.370754
218,741,Alba,Fernández Torres,29557879Y,Espanya,Alacant,Dona,"3,087 €",Grup D,Administratiu,...,8.7,-10.0,1964-11-27,True,NaN,62.0,56 +,13.9000,22.1000,11.183385
234,792,Riccardo,Rossi,16284386J,Itàlia,Firenze,Dona,1920 euros,Grup B,Responsable de vendes,...,4.5,42.0,1959-05-18,True,NaN,67.0,56 +,5.9125,22.0125,11.399532
250,834,Alba,Torres Navarro,83919680R,Espanya,Barcelona,Dona,"1,778 €",Grup B,Administratiu,...,12.6,38.0,1966-08-20,True,NaN,60.0,56 +,9.6500,22.8500,8.012746
258,859,Lucía,Vila,65153035X,Espanya,Valladolid,Dona,"1,072 €",Grup A,Analista,...,5.5,-5.0,1959-12-17,True,Analista de dades,67.0,56 +,2.8250,21.4250,9.614427
265,879,Carlos,Díaz,88598588G,Espanya,Màlaga,Dona,797 €,Grup A,Analista,...,13.2,38.0,1981-06-16,True,Analista de dades,45.0,36-45,13.5000,24.3000,6.350363
267,890,Anna,López,14839040C,Espanya,Alacant,NaN,"1,072 €",Grup A,Analista,...,0.5,-10.0,1989-05-23,True,Analista senior,37.0,36-45,13.9000,22.1000,11.183385
295,984,Giulia,Romano,34747698K,Itàlia,Torino,Dona,"1,316 €",Grup B,Tècnic IT,...,9.1,38.0,NaT,True,NaN,NaN,NaN,7.4500,23.8500,10.600142

Substituyo los valores que son outliers por el valor de la mediana de cada ciudad.

In [394]:
ciutat_mediana = dataset_s8.groupby('Ciutat')['Temperatura mitjana ciutat'].median()

dataset_s8.loc[outliers_temp, 'Temperatura mitjana ciutat'] = dataset_s8.loc[outliers_temp, 'Ciutat'].map(ciutat_mediana)

Vuelvo a mirar la temperatura de los outliers y se ha cambiado.

In [395]:
dataset_s8[outliers_temp]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,...,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat,temp_inferior,temp_superior,temp_desv
4,13,Joana,Torres Díaz,82772208R,Espanya,Valladolid,Dona,982 €,Grup A,Administratiu,...,7.7,10.80,1961-10-24,True,NaN,65.0,56 +,2.8250,21.4250,9.614427
13,34,Adrià,Ferrer,64830300Z,Espanya,Barcelona,Home,927€,Grup A,Cap de projecte,...,12.0,15.60,1987-05-10,True,NaN,39.0,36-45,9.6500,22.8500,8.012746
184,636,Chiara,Bianchi,89568937L,Itàlia,Firenze,Home,"1,815 €",Grup B,Analista,...,25.0,14.20,1994-04-23,True,Analista senior,32.0,25-35,5.9125,22.0125,11.399532
198,678,Alejandro,Navarro,50530014N,Espanya,Tarragona,Dona,"1,947 €",Grup B,Analista,...,10.7,17.20,1966-11-26,True,Analista senior,60.0,56 +,11.0125,21.9125,5.370754
218,741,Alba,Fernández Torres,29557879Y,Espanya,Alacant,Dona,"3,087 €",Grup D,Administratiu,...,8.7,18.45,1964-11-27,True,NaN,62.0,56 +,13.9000,22.1000,11.183385
234,792,Riccardo,Rossi,16284386J,Itàlia,Firenze,Dona,1920 euros,Grup B,Responsable de vendes,...,4.5,14.20,1959-05-18,True,NaN,67.0,56 +,5.9125,22.0125,11.399532
250,834,Alba,Torres Navarro,83919680R,Espanya,Barcelona,Dona,"1,778 €",Grup B,Administratiu,...,12.6,15.60,1966-08-20,True,NaN,60.0,56 +,9.6500,22.8500,8.012746
258,859,Lucía,Vila,65153035X,Espanya,Valladolid,Dona,"1,072 €",Grup A,Analista,...,5.5,10.80,1959-12-17,True,Analista de dades,67.0,56 +,2.8250,21.4250,9.614427
265,879,Carlos,Díaz,88598588G,Espanya,Màlaga,Dona,797 €,Grup A,Analista,...,13.2,18.60,1981-06-16,True,Analista de dades,45.0,36-45,13.5000,24.3000,6.350363
267,890,Anna,López,14839040C,Espanya,Alacant,NaN,"1,072 €",Grup A,Analista,...,0.5,18.45,1989-05-23,True,Analista senior,37.0,36-45,13.9000,22.1000,11.183385
295,984,Giulia,Romano,34747698K,Itàlia,Torino,Dona,"1,316 €",Grup B,Tècnic IT,...,9.1,15.00,NaT,True,NaN,NaN,NaN,7.4500,23.8500,10.600142

Vuelvo a obtener las métricas de las ciudades.

Menos Koln y Bourdeos, todas han bajado su desviación. Ningúna de esas 2 ciudades tenia valores en outliers.

In [396]:
dataset_s8.groupby('Ciutat')['Temperatura mitjana ciutat'].describe().sort_values(by='std')

,count,mean,std,min,25%,50%,75%,max
Ciutat,,,,,,,,
Berlin,2.0,10.900000,0.282843,10.7,10.800,10.900,11.000,11.1
Paris,2.0,11.900000,0.424264,11.6,11.750,11.900,12.050,12.2
Stuttgart,3.0,12.400000,0.700000,11.7,12.050,12.400,12.750,13.1
Genova,5.0,16.160000,0.926283,15.2,15.900,15.900,16.100,17.7
Toulouse,3.0,14.100000,1.178983,13.1,13.450,13.800,14.600,15.4
Alacant,12.0,18.550000,1.181871,16.3,18.225,18.475,19.025,20.9
Nice,2.0,15.550000,1.343503,14.6,15.075,15.550,16.025,16.5
Bergen,3.0,8.400000,1.345362,6.9,7.850,8.800,9.150,9.5
Lille,3.0,10.400000,1.400000,9.4,9.600,9.800,10.900,12.0
Las Palmas de Gran Canaria,11.0,20.736364,1.537057,18.4,19.650,21.300,21.950,22.7
Barcelona,15.0,15.660000,1.570168,13.2,14.600,15.600,15.900,18.9
Zaragoza,14.0,15.114286,1.640758,12.0,14.150,15.450,15.950,17.7
Tarragona,18.0,16.716667,1.651470,13.5,15.250,17.250,17.825,19.4
Frankfurt,2.0,11.400000,1.697056,10.2,10.800,11.400,12.000,12.6
Murcia,14.0,18.878571,1.705727,14.9,17.900,18.900,20.000,21.1
Madrid,19.0,15.289474,1.846286,11.6,14.600,15.000,16.300,19.0
Màlaga,10.0,18.800000,1.885029,16.3,17.550,18.450,19.575,22.9
Milano,5.0,13.240000,1.908664,10.6,12.600,12.800,14.900,15.3
Firenze,10.0,14.080000,1.926309,10.5,13.950,14.200,15.275,16.6
Torino,5.0,14.760000,1.950128,12.5,13.600,15.000,15.000,17.7
Roma,5.0,16.420000,1.997999,14.2,15.100,16.000,17.600,19.2
Napoli,5.0,16.440000,2.016928,13.6,15.600,16.600,17.400,19.0
Oslo,6.0,7.666667,2.126656,4.8,6.350,7.550,9.275,10.3
Bilbao,20.0,13.820000,2.212310,9.9,12.925,13.800,15.425,18.2
Valladolid,12.0,11.491667,2.214193,8.9,10.025,10.800,12.000,15.9
Nantes,3.0,11.733333,2.218859,9.7,10.550,11.400,12.750,14.1
Marseille,2.0,12.000000,2.262742,10.4,11.200,12.000,12.800,13.6
A Coruña,13.0,14.200000,2.297825,11.1,12.900,13.900,15.500,19.3
Sevilla,9.0,19.555556,2.548093,15.2,17.500,19.200,21.700,22.6
València,11.0,17.490909,2.675614,12.6,16.200,18.000,19.350,21.3
Palma,16.0,17.606250,3.193007,10.9,15.375,17.900,19.625,22.3
Girona,13.0,13.630769,3.455041,8.1,11.300,13.200,16.500,19.4
Bordeaux,4.0,7.450000,8.501568,-5.0,5.500,10.900,12.850,13.0
Köln,2.0,2.250000,10.253048,-5.0,-1.375,2.250,5.875,9.5
Hamburg,1.0,4.600000,NaN,4.6,4.600,4.600,4.600,4.6
Leipzig,1.0,9.100000,NaN,9.1,9.100,9.100,9.100,9.1
München,1.0,8.000000,NaN,8.0,8.000,8.000,8.000,8.0
Tromsø,1.0,2.600000,NaN,2.6,2.600,2.600,2.600,2.6
Trondheim,1.0,2.400000,NaN,2.4,2.400,2.400,2.400,2.4
Venezia,1.0,13.800000,NaN,13.8,13.800,13.800,13.800,13.8

Compruebo si a alguna ciudad le faltan datos en sus filas para añadirle también la mediana de cada ciudad.

In [397]:
ciudad_no_temp = dataset_s8.loc[:,'Temperatura mitjana ciutat'].isna()
dataset_s8.loc[ciudad_no_temp, 'Temperatura mitjana ciutat'] = dataset_s8.loc[:,'Ciutat'].map(ciutat_mediana)

Compruebo que se han añadido las temperatuas a las ciudades que no tenian temperatura.

In [398]:
dataset_s8[ciudad_no_temp]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,...,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat,temp_inferior,temp_superior,temp_desv
8,18,Carmen,Hernández Serra,36786211Z,Espanya,Tarragona,Home,"1,336 €",Grup B,Administratiu,...,NaN,17.20,1960-08-08,True,NaN,66.0,56 +,11.0125,21.9125,5.370754
15,50,Aina,Fernández,38468360C,Espanya,Zaragoza,Home,1939 euros,Grup C,Analista,...,NaN,15.45,NaT,True,Analista,NaN,NaN,11.4500,18.6500,1.640758
38,137,Max,Zimmermann Weber,62741214E,Alemanya,München,Dona,"1,343 €",Grup B,Administratiu,...,NaN,8.00,1974-06-30,True,NaN,52.0,46-55,8.0000,8.0000,NaN
84,301,Adrià,Martínez Martínez,43958759R,Espanya,Tarragona,Home,"1,247 €",Grup B,Analista,...,NaN,17.20,1961-08-04,True,Analista junior,65.0,56 +,11.0125,21.9125,5.370754
92,327,Oriol,Sánchez,37344675D,Espanya,Palma,Dona,1250 euros,Grup A,Analista,...,5.4,17.90,1965-06-03,True,Analista de dades,61.0,56 +,9.0000,26.0000,3.193007
129,446,Núria,Casals Díaz,62027391F,Espanya,Màlaga,Dona,2.121 €,Grup B,Analista,...,11.6,18.60,1985-01-29,True,Analista senior,41.0,36-45,13.5000,24.3000,6.350363
134,460,Noa,García,89979598A,Espanya,València,Dona,"1,113 €",Grup A,Analista,...,0.5,18.00,1964-02-15,True,Analista junior,62.0,56 +,11.4750,24.0750,2.675614
135,461,Anna,Moreno,11361006M,Espanya,Zaragoza,Dona,dos mil,Grup B,Analista,...,12.9,15.45,1968-03-10,True,Analista,58.0,56 +,11.4500,18.6500,1.640758
137,468,Clara,Moreau,60184824L,França,Paris,Dona,"1,034 €",Grup A,Cap de projecte,...,NaN,11.90,1999-02-27,True,NaN,27.0,25-35,11.3000,12.5000,0.424264
214,723,Adrià,Fernández Costa,57657637T,Espanya,Barcelona,Dona,860 €,Grup A,Analista,...,25.0,15.60,1993-08-20,True,Analista de dades,33.0,25-35,9.6500,22.8500,8.012746
222,747,Nil,Martínez Fernández,81696670A,Espanya,Bilbao,Home,1280€,Grup A,Analista,...,25.0,13.80,1964-07-16,True,Analista de dades,62.0,56 +,9.1750,19.1750,2.212310
224,756,Aina,Ribera,43716263M,Espanya,València,Dona,"1,636 €",Grup B,Tècnic IT,...,13.3,18.00,1979-06-09,True,NaN,47.0,46-55,11.4750,24.0750,2.675614
246,823,Thomas,Leroy,49412831B,França,Bordeaux,Dona,803 €,Grup A,Responsable de vendes,...,8.6,10.90,1993-06-22,True,NaN,33.0,25-35,-5.5250,23.8750,8.501568
255,847,Joana,Casals,57762576N,Espanya,Màlaga,Home,2634€,Grup D,Analista,...,5.6,18.60,NaT,True,Analista junior,NaN,NaN,13.5000,24.3000,6.350363
266,884,Lucía,Gómez,55411287M,Espanya,Barcelona,Home,1.340 €,Grup A,Responsable de vendes,...,25.0,15.60,1975-07-13,True,NaN,51.0,46-55,9.6500,22.8500,8.012746
280,925,Simone,Esposito,88357247Z,Itàlia,Torino,Home,926 €,Grup A,Analista,...,NaN,15.00,1967-02-15,True,Analista junior,59.0,56 +,7.4500,23.8500,10.600142
283,941,Anna,Serra,81614472L,Espanya,Murcia,Dona,"1,530 €",Grup B,Administratiu,...,6.5,18.90,1984-02-04,True,NaN,42.0,36-45,14.7500,23.1500,1.705727
284,942,Alexia,Casals Ribera,86670701B,Espanya,Màlaga,Dona,"1,308 €",Grup A,Analista,...,25.0,18.60,2004-03-03,True,Analista senior,22.0,16-24,13.5000,24.3000,6.350363
296,988,Pol,García,76459478B,Espanya,Palma,Home,"1,244 €",Grup B,Cap de projecte,...,NaN,17.90,1977-01-14,True,NaN,49.0,46-55,9.0000,26.0000,3.193007

Y compruebo que no hay ninguna ciudad con temperatura nula

In [399]:
dataset_s8[dataset_s8['Temperatura mitjana ciutat'].isna()].groupby('Ciutat').value_counts()

Series([], Name: count, dtype: int64)

Elimino las 3 columnas que he creado y ya no las necesito.

In [400]:
dataset_s8.drop(['temp_inferior','temp_superior','temp_desv'], axis=1, inplace=True)

#### Valores contextuales: Salario

In [401]:
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       304 non-null    int64
 1   Nom                         304 non-null    str
 2   Cognoms                     304 non-null    str
 3   DNI                         304 non-null    str
 4   País d'origen               304 non-null    str
 5   Ciutat                      304 non-null    str
 6   Gènere                      279 non-null    str
 7   Salari mensual              304 non-null    str
 8   Grup Professional           304 non-null    str
 9   Càrrec                      304 non-null    str
 10  Nombre fills                209 non-null    Int64
 11  Km anuals                   304 non-null    float64
 12  Consum mitja L 100km        255 non-null    float64
 13  Temperatura mitjana ciutat  304 non-null    float64
 14  Data de Naixement           280 non-null    datetime64[us]
 15  Te cotxe calculat           304 non-null    bool
 16  Categoria càrrec            153 non-null    str
 17  Edat                        280 non-null    float64
 18  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(4), int64(1), str(11)
memory usage: 67.3 KB

Salari es tipo string, por lo que hay que cambiarlo a tipo numerico. Antes de eso, hay que quitar el símbolo de moneda, estandarizar el número y comprobar que no hayan escrito "mil seiscientos con catorce centimos".

Se comprueban los valores.

In [402]:
dataset_s8['Salari mensual'].unique()

<ArrowStringArray>
[       '1,469 €',        '2,718 €',        '2,349 €',        '2,855 €',
          '982 €',        '3,672 €',        '1,003 €', 'mil vuit-cents',
        '1,336 €',        '1,385 €',
 ...
          '1692€',           '950€',        '1,316 €',        '1,244 €',
     '1225 euros',        '1,002 €',        '1,183 €',     '3486 euros',
        '1,074 €',        '2.290 €']
Length: 283, dtype: str

Por lo que se ve, hay comas, puntos, € y números escritos en letras. Primero se reemplazan las comas, puntos y €.

Creo una función que si es nulo, devuelva el nulo. Por cada elemento que quiera borrar, me devuelva el valor sin el elemento.

In [403]:
def substituir(valor, elementos):
    if pd.isna(valor):
        return valor
    
    for elemento in elementos:
        valor = valor.replace(elemento,"")
    return valor

In [404]:
elementos_borrar = [',', '.','€','euros']
dataset_s8['Salari mensual'] = dataset_s8['Salari mensual'].apply(lambda x: substituir(x, elementos_borrar))

Compruebo que ningúna fila le quede €.

In [405]:
dataset_s8['Salari mensual'].str.contains("€").sum()

np.int64(0)

Ahora que los salarios no tienen comas, puntos o símbolos de euro, se convierten a formato numérico. Con el error='coerce' detectaré los que no son números estrictamente y los podré corregir.

In [406]:
salario_num = pd.to_numeric(dataset_s8['Salari mensual'], errors='coerce').isna()
salario_num

0      False
1      False
2      False
3      False
4      False
       ...
299    False
300    False
301     True
302    False
303    False
Name: Salari mensual, Length: 304, dtype: bool

In [407]:
dataset_s8.loc[salario_num]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
7,17,Xavier,Casals,43491314K,Espanya,Alacant,Home,mil vuit-cents,Grup A,Analista,0,38248.0,0.5,19.70,1980-04-22,True,Analista junior,46.0,46-55
32,112,Katharina,Braun Fischer,93240786N,Alemanya,Leipzig,NaN,mil vuit-cents,Grup B,Administratiu,1,76180.0,NaN,9.10,1958-07-11,True,NaN,68.0,56 +
51,184,Alexia,Muñoz,97446634Y,Espanya,Murcia,Home,dos mil,Grup B,Administratiu,0,48621.0,0.5,18.90,1989-01-10,True,NaN,37.0,36-45
103,362,Laia,Ribera,52445278T,Espanya,Tarragona,Dona,mil vuit-cents,Grup B,Tècnic IT,<NA>,80000.0,5.7,15.10,1984-09-15,True,NaN,42.0,36-45
122,431,Aina,Puig Vila,38182016V,Espanya,Alacant,Dona,tres mil,Grup A,Analista,1,80000.0,5.8,16.30,1999-04-27,True,Analista junior,27.0,25-35
135,461,Anna,Moreno,11361006M,Espanya,Zaragoza,Dona,dos mil,Grup B,Analista,3,3936.0,12.9,15.45,1968-03-10,True,Analista,58.0,56 +
278,920,Claudia,Gil Fernández,19213734E,Espanya,Palma,Home,n/d,Grup C,Analista,<NA>,81219.0,6.6,13.30,1971-07-03,True,Analista senior,55.0,46-55
287,959,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,Dona,n/d,Grup A,Cap de projecte,<NA>,9017.0,0.5,13.00,2004-05-10,True,NaN,22.0,16-24
301,997,Adrià,Hernández Ramos,80771894Q,Espanya,Bilbao,NaN,tres mil,Grup A,Analista,<NA>,80000.0,25.0,18.20,1990-06-24,True,Analista senior,36.0,36-45

Por suerte hay pocos usuarios que han escrito su salario y solo hay 3 cantidades. Se corrige.

In [408]:
diccionario_salario = {
    'mil vuit-cents':'1800',
    'dos mil':'2000',
    'tres mil':'3000'
}

In [409]:
dataset_s8.loc[salario_num,'Salari mensual'] = dataset_s8.loc[salario_num,'Salari mensual'].apply(lambda x: estandarizar(x, diccionario_salario))

Compruebo que se ha corregido bien.

In [410]:
dataset_s8[salario_num]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
7,17,Xavier,Casals,43491314K,Espanya,Alacant,Home,1800,Grup A,Analista,0,38248.0,0.5,19.70,1980-04-22,True,Analista junior,46.0,46-55
32,112,Katharina,Braun Fischer,93240786N,Alemanya,Leipzig,NaN,1800,Grup B,Administratiu,1,76180.0,NaN,9.10,1958-07-11,True,NaN,68.0,56 +
51,184,Alexia,Muñoz,97446634Y,Espanya,Murcia,Home,2000,Grup B,Administratiu,0,48621.0,0.5,18.90,1989-01-10,True,NaN,37.0,36-45
103,362,Laia,Ribera,52445278T,Espanya,Tarragona,Dona,1800,Grup B,Tècnic IT,<NA>,80000.0,5.7,15.10,1984-09-15,True,NaN,42.0,36-45
122,431,Aina,Puig Vila,38182016V,Espanya,Alacant,Dona,3000,Grup A,Analista,1,80000.0,5.8,16.30,1999-04-27,True,Analista junior,27.0,25-35
135,461,Anna,Moreno,11361006M,Espanya,Zaragoza,Dona,2000,Grup B,Analista,3,3936.0,12.9,15.45,1968-03-10,True,Analista,58.0,56 +
278,920,Claudia,Gil Fernández,19213734E,Espanya,Palma,Home,NaN,Grup C,Analista,<NA>,81219.0,6.6,13.30,1971-07-03,True,Analista senior,55.0,46-55
287,959,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,Dona,NaN,Grup A,Cap de projecte,<NA>,9017.0,0.5,13.00,2004-05-10,True,NaN,22.0,16-24
301,997,Adrià,Hernández Ramos,80771894Q,Espanya,Bilbao,NaN,3000,Grup A,Analista,<NA>,80000.0,25.0,18.20,1990-06-24,True,Analista senior,36.0,36-45

Estandarizados los salarios mensuales, los convierto en formato numérico y cambio de nombre a la columna de 'Salari mensual' a 'Salari mensual €'.

In [411]:
dataset_s8['Salari mensual'] = pd.to_numeric(dataset_s8['Salari mensual'], errors='coerce')
dataset_s8 = dataset_s8.rename(columns={'Salari mensual':'Salari mensual €'})

In [412]:
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       304 non-null    int64
 1   Nom                         304 non-null    str
 2   Cognoms                     304 non-null    str
 3   DNI                         304 non-null    str
 4   País d'origen               304 non-null    str
 5   Ciutat                      304 non-null    str
 6   Gènere                      279 non-null    str
 7   Salari mensual €            302 non-null    float64
 8   Grup Professional           304 non-null    str
 9   Càrrec                      304 non-null    str
 10  Nombre fills                209 non-null    Int64
 11  Km anuals                   304 non-null    float64
 12  Consum mitja L 100km        255 non-null    float64
 13  Temperatura mitjana ciutat  304 non-null    float64
 14  Data de Naixement           280 non-null    datetime64[us]
 15  Te cotxe calculat           304 non-null    bool
 16  Categoria càrrec            153 non-null    str
 17  Edat                        280 non-null    float64
 18  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(5), int64(1), str(10)
memory usage: 64.7 KB

En la estandarización del salario se observa hay 2 nulos.

In [413]:
dataset_s8[dataset_s8['Salari mensual €'].isna()]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual €,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
278,920,Claudia,Gil Fernández,19213734E,Espanya,Palma,Home,NaN,Grup C,Analista,<NA>,81219.0,6.6,13.3,1971-07-03,True,Analista senior,55.0,46-55
287,959,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,Dona,NaN,Grup A,Cap de projecte,<NA>,9017.0,0.5,13.0,2004-05-10,True,NaN,22.0,16-24

Creo una agrupación con las categorías y la mediana del sueldo para establecer una mayor exactitud en la asignación de los salarios que deberían tener los 2 usuarios que no han indicado el suyo.

Se tendrá en cuenta el cargo, la categoria (si existe), ciudad, grupo profesional y grupo de edad.

Cargo, categoria y grupo profesional: está relacionado con el puesto de trabajo.
Ciudad y grupo de edad: dependiendo el país y la experiencia (edad) pagarán más o menos.

In [414]:
combinado_salario = dataset_s8.groupby([
    'Càrrec',
    dataset_s8['Categoria càrrec'].fillna("no categoria"),
    dataset_s8['Ciutat'],
    dataset_s8['Grup Professional'],
    dataset_s8['Grup edat'].fillna("edat no definida")])['Salari mensual €'].transform('median')
combinado_salario

0      1469.0
1      2718.0
2      1796.5
3      2855.0
4       982.0
        ...
299    1183.0
300    3486.0
301    3000.0
302    1020.0
303    2290.0
Name: Salari mensual €, Length: 304, dtype: float64

Se le asigna el salario de la agrupación a los usuarios que no tienen salario indicado

In [415]:
dataset_s8['Salari mensual €'] = (dataset_s8['Salari mensual €'].fillna(combinado_salario))

Comprobamos los nulos en Salari mensual €

In [416]:
dataset_s8[dataset_s8['Salari mensual €'].isna()]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual €,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
278,920,Claudia,Gil Fernández,19213734E,Espanya,Palma,Home,NaN,Grup C,Analista,<NA>,81219.0,6.6,13.3,1971-07-03,True,Analista senior,55.0,46-55
287,959,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,Dona,NaN,Grup A,Cap de projecte,<NA>,9017.0,0.5,13.0,2004-05-10,True,NaN,22.0,16-24

Compruebo si para el cargo y la ciudad hay más combinaciones (la combinación más probable de que fallase).

Como no se le ha podido asignar un salario a partir de la combinación cargo, categoria, ciudad y grupo de edad, se le asignará solamente con cargo, grupo profesional y grupo de edad.

In [417]:
dataset_s8[(dataset_s8['Ciutat']=='Zaragoza')&(dataset_s8['Càrrec']=='Cap de projecte')]

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual €,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
287,959,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,Dona,NaN,Grup A,Cap de projecte,<NA>,9017.0,0.5,13.0,2004-05-10,True,NaN,22.0,16-24

Creo otro combinado salario para Alexia, le asigno el salario y vuelvo a comprobar si hay nulos en Salari mensual €.

In [418]:
combinado_salario_alexia = dataset_s8.groupby([
    'Càrrec',
    dataset_s8['Categoria càrrec'].fillna("no categoria"),
    dataset_s8['Grup Professional'],
    dataset_s8['Grup edat'].fillna("edat no definida")])['Salari mensual €'].transform('median')
dataset_s8['Salari mensual €'] = (dataset_s8['Salari mensual €'].fillna(combinado_salario_alexia))
dataset_s8[dataset_s8['Salari mensual €'].isna()]

Empty DataFrame
Columns: [index, Nom, Cognoms, DNI, País d'origen, Ciutat, Gènere, Salari mensual €, Grup Professional, Càrrec, Nombre fills, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat, Data de Naixement, Te cotxe calculat, Categoria càrrec, Edat, Grup edat]
Index: []

## RESUMEN EJERCICIOS 1-2-3

Tras las transformaciones necesarias, se obtiene un dataframe con 19 columnas y 304 filas con el tipo de dato formateado al más idóneo para representar y analizar los valores y solamente 5 columnas con nulos.

Originalmente había 20 columnas y 1010 filas. Todas las columnas eran tipo string y había una gran cantidad de nulos y valores duplicados.

In [474]:
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       304 non-null    int64
 1   Nom                         304 non-null    str
 2   Cognoms                     304 non-null    str
 3   DNI                         304 non-null    str
 4   País d'origen               304 non-null    str
 5   Ciutat                      304 non-null    str
 6   Gènere                      279 non-null    str
 7   Salari mensual €            304 non-null    float64
 8   Grup Professional           304 non-null    str
 9   Càrrec                      304 non-null    str
 10  Nombre fills                209 non-null    Int64
 11  Km anuals                   304 non-null    float64
 12  Consum mitja L 100km        255 non-null    float64
 13  Temperatura mitjana ciutat  304 non-null    float64
 14  Data de Naixement           280 non-null    datetime64[us]
 15  Te cotxe calculat           304 non-null    bool
 16  Categoria càrrec            153 non-null    str
 17  Edat                        280 non-null    float64
 18  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(5), int64(1), str(10)
memory usage: 64.7 KB

## EJERCICIO 4: PRIMEROS ANÁLISIS DESCRIPTIVOS

#### Tabla salarios (media, mediana, máximo y mínimo) separado por género.

In [420]:
genere_salari = dataset_s8.pivot_table(values='Salari mensual €',
                       index='Gènere',
                       aggfunc=['mean','median','max','min'])

In [421]:
genere_salari.columns = genere_salari.columns.droplevel(1)
genere_salari = genere_salari.rename(columns={'mean':'Salari mig',
                              'median':'Salari medià',
                              'max':'Salari màxim',
                              'min':'Salari mínim'})
genere_salari

         Salari mig  Salari medià  Salari màxim  Salari mínim
Gènere
Dona    1461.118497        1324.0        3564.0         746.0
Home    1721.811321        1508.5        3672.0         765.0

Los hombres en todas las medidas ganan más que las mujeres. Aunque el salario máximo y mínimo de ambos géneros se parezcan, el salario medio y mediano es bastante desigual. La tendencia es que las mujeres se concentran en salarios más bajos y los hombres en salarios más altos.

#### Tabla salarios medio por género y país de orígen

In [422]:
salario_gene_country = dataset_s8.pivot_table(
    values='Salari mensual €',
    index='Gènere',
    columns="País d'origen",
    aggfunc='mean',
    margins=True,
    margins_name='Mitjana'
)

In [423]:
salario_gene_country

País d'origen,Alemanya,Espanya,França,Itàlia,Noruega,Mitjana
Gènere,,,,,,
Dona,1453.500000,1453.889344,1317.615385,1463.363636,1923.5,1461.118497
Home,1740.000000,1731.927711,1730.833333,1844.250000,1126.5,1721.811321
Mitjana,1479.545455,1566.460976,1448.105263,1597.794118,1604.7,1560.163082

Si comparamos por países de orígen, el país donde más ganan los trabajadores es Noruega, seguido de Itália y España. Respecto al gènero, los hombres ganan más que las mujeres, excepto en Noruega. 
Donde más ganan las mujeres es en Noruega y los hombres en Itàlia. Donde menos ganan las mujeres es en Francia y los hombres en Noruega.

Para calcular la brecha salarial la formula es: 
brecha salarial = ((salario medio hombre - salario medio mujer)/salario medio hombre)*100

Este indicador marca el % de la diferencia de los salarios medios del hombre respecto a la mujer.

In [424]:
brecha_salario = ((salario_gene_country.loc['Home'] - salario_gene_country.loc['Dona'])/ salario_gene_country.loc['Home']) * 100
brecha_salario

País d'origen
Alemanya    16.465517
Espanya     16.053694
França      23.873931
Itàlia      20.652643
Noruega    -70.750111
Mitjana     15.140615
dtype: float64

En este caso, se observa como los hombres cobran al rededor de un 18% más que las mujeres, pero la media de los países se ve afectada por Noruega. En este país la diferencia es del 70% y las mujeres ganan más de 2/3 que los hombres.
Con esta medida, España y Alemania es donde menor brecha salarial hay.

Otra forma de verlo es el porcentaje de salario que cobra una mujer del salario de un hombre (en este caso).

In [425]:
porcentaje_salario = (salario_gene_country.loc['Dona'] / salario_gene_country.loc['Home'] * 100)
porcentaje_salario

País d'origen
Alemanya     83.534483
Espanya      83.946306
França       76.126069
Itàlia       79.347357
Noruega     170.750111
Mitjana      84.859385
dtype: float64

# NIVEL 2: ANÁLISIS CON DATOS ENRIQUECIDOS Y ESTRUCTURAS MÚLTIPLES

## Ejercicio 1: Enriquecimiento con datasets externos

### Importación

Primero importamos el json y csv con la información de politica salarial y ciudades

In [486]:
with open('politica_salarial.json', 'r', encoding='utf-8') as json_data:
    politica_salarial = json.load(json_data)


ciutat_context = pd.read_csv('ciutats_context.csv', encoding='cp1252')

In [488]:
politica_salarial

{'base_increment_by_group': {'Grup A': 5.0,
  'Grup B': 3.5,
  'Grup C': 2.0,
  'Grup D': 8.0},
 'children_adjustment': {'has_children': 1.5, 'no_children': 0.0},
 'age_adjustment': {'18-29': 0.0, '30-44': 1.0, '45-59': 2.0, '60+': 1.5},
 'cost_of_living_adjustment': {'low': 0.0, 'medium': 1.0, 'high': 2.0},
 'transport_adjustment': {'low': 0.5, 'medium': 0.0, 'high': -0.5},
 'rules': {'max_total_increment_percent': 15, 'min_salary_threshold': 800}}

In [462]:
ciutat_context

,Ciutat,País,Cost_vida_index,Transport_public_score,Clima_tipus
0,Barcelona,Espanya,78,8.5,Mediterrani
1,Madrid,Espanya,75,8.0,Continental
2,València,Espanya,70,7.5,Mediterrani
3,Sevilla,Espanya,65,7.0,Mediterrani
4,Bilbao,Espanya,72,7.8,Oceànic
5,Zaragoza,Espanya,68,7.0,Continental
6,Murcia,Espanya,60,6.5,Mediterrani
7,Palma,Espanya,73,7.2,Mediterrani
8,Girona,Espanya,66,6.8,Mediterrani
9,Tarragona,Espanya,67,6.9,Mediterrani
10,A Coru\u00f1a,Espanya,69,7.1,Oceànic
11,Valladolid,Espanya,64,6.7,Continental
12,Alacant,Espanya,68,7.0,Mediterrani
13,Las Palmas de Gran Canaria,Espanya,62,6.8,Subtropical
14,Paris,França,85,9.0,Oceànic
15,Marseille,França,72,7.4,Mediterrani
16,Lyon,França,74,7.6,Continental
17,Bordeaux,França,73,7.2,Oceànic
18,Lille,França,71,7.3,Continental
19,Milano,Itàlia,80,7.5,Continental
20,Roma,Itàlia,78,7.6,Mediterrani
21,Torino,Itàlia,74,7.2,Continental
22,Genova,Itàlia,72,6.9,Mediterrani
23,Venezia,Itàlia,79,7.0,Mediterrani
24,Napoli,Itàlia,65,6.5,Mediterrani
25,Firenze,Itàlia,77,7.1,Continental
26,Berlin,Alemanya,76,8.5,Continental
27,Munchen,Alemanya,82,8.0,Continental
28,Hamburg,Alemanya,78,8.1,Oceànic
29,Frankfurt,Alemanya,80,8.3,Continental
30,Stuttgart,Alemanya,79,7.9,Continental
31,Leipzig,Alemanya,70,7.2,Continental
32,Oslo,Noruega,90,9.2,Fred
33,Bergen,Noruega,85,8.8,Oceànic
34,Paris,Estats Units,88,6.0,Continental
35,Valencia,Veneçuela,55,5.5,Tropical

A coruña no se corrige con cp1252 al tener la ñ. Se hace una corrección manual.

In [463]:
ciutat_context['Ciutat'] = ciutat_context['Ciutat'].str.replace('A Coru\\u00f1a','A Coruña')

In [464]:
ciutat_context.sort_values(by='Ciutat')

,Ciutat,País,Cost_vida_index,Transport_public_score,Clima_tipus
10,A Coruña,Espanya,69,7.1,Oceànic
12,Alacant,Espanya,68,7.0,Mediterrani
0,Barcelona,Espanya,78,8.5,Mediterrani
33,Bergen,Noruega,85,8.8,Oceànic
26,Berlin,Alemanya,76,8.5,Continental
4,Bilbao,Espanya,72,7.8,Oceànic
17,Bordeaux,França,73,7.2,Oceànic
25,Firenze,Itàlia,77,7.1,Continental
29,Frankfurt,Alemanya,80,8.3,Continental
22,Genova,Itàlia,72,6.9,Mediterrani
8,Girona,Espanya,66,6.8,Mediterrani
28,Hamburg,Alemanya,78,8.1,Oceànic
13,Las Palmas de Gran Canaria,Espanya,62,6.8,Subtropical
31,Leipzig,Alemanya,70,7.2,Continental
18,Lille,França,71,7.3,Continental
16,Lyon,França,74,7.6,Continental
1,Madrid,Espanya,75,8.0,Continental
15,Marseille,França,72,7.4,Mediterrani
19,Milano,Itàlia,80,7.5,Continental
27,Munchen,Alemanya,82,8.0,Continental
6,Murcia,Espanya,60,6.5,Mediterrani
24,Napoli,Itàlia,65,6.5,Mediterrani
32,Oslo,Noruega,90,9.2,Fred
7,Palma,Espanya,73,7.2,Mediterrani
14,Paris,França,85,9.0,Oceànic
34,Paris,Estats Units,88,6.0,Continental
20,Roma,Itàlia,78,7.6,Mediterrani
3,Sevilla,Espanya,65,7.0,Mediterrani
30,Stuttgart,Alemanya,79,7.9,Continental
9,Tarragona,Espanya,67,6.9,Mediterrani
21,Torino,Itàlia,74,7.2,Continental
35,Valencia,Veneçuela,55,5.5,Tropical
11,Valladolid,Espanya,64,6.7,Continental
2,València,Espanya,70,7.5,Mediterrani
23,Venezia,Itàlia,79,7.0,Mediterrani
5,Zaragoza,Espanya,68,7.0,Continental

In [465]:
ciutat_context.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Ciutat                  36 non-null     str
 1   País                    36 non-null     str
 2   Cost_vida_index         36 non-null     int64
 3   Transport_public_score  36 non-null     float64
 4   Clima_tipus             36 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 2.4 KB

### Combinar datasets externos con dataset interno

Primero completo la combinación del dataset_s8 y ciutat_context porque necesito los datos que aporta ciutat_context para calcular el incremento de salario.

#### Ciudad contexto

In [466]:
dataset_s8['Ciutat'].unique()

<ArrowStringArray>
[                'Valladolid',                    'Alacant',
                      'Palma',                  'Barcelona',
 'Las Palmas de Gran Canaria',                  'Stuttgart',
                  'Tarragona',                     'Bergen',
                     'Bilbao',                     'Milano',
                      'Paris',                   'Zaragoza',
                   'A Coruña',                     'Murcia',
                    'Venezia',                    'Sevilla',
                     'Madrid',                     'Berlin',
                       'Nice',                       'Roma',
                    'Leipzig',                     'Girona',
                    'München',                   'Bordeaux',
                     'Torino',                    'Firenze',
                     'Màlaga',                   'València',
                     'Genova',                   'Toulouse',
                  'Trondheim',                       'Köln',
                     'Napoli',                      'Lille',
                     'Nantes',                       'Oslo',
                  'Marseille',                     'Tromsø',
                    'Hamburg',                  'Frankfurt']
Length: 40, dtype: str

In [475]:
dataset_s8 = pd.merge(dataset_s8,ciutat_context,on='Ciutat',how='left')

In [476]:
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       307 non-null    int64
 1   Nom                         307 non-null    str
 2   Cognoms                     307 non-null    str
 3   DNI                         307 non-null    str
 4   País d'origen               307 non-null    str
 5   Ciutat                      307 non-null    str
 6   Gènere                      282 non-null    str
 7   Salari mensual €            307 non-null    float64
 8   Grup Professional           307 non-null    str
 9   Càrrec                      307 non-null    str
 10  Nombre fills                210 non-null    Int64
 11  Km anuals                   307 non-null    float64
 12  Consum mitja L 100km        257 non-null    float64
 13  Temperatura mitjana ciutat  307 non-null    float64
 14  Data de Naixement           283 non-null    datetime64[us]
 15  Te cotxe calculat           307 non-null    bool
 16  Categoria càrrec            155 non-null    str
 17  Edat                        283 non-null    float64
 18  Grup edat                   283 non-null    str
 19  País                        280 non-null    str
 20  Cost_vida_index             280 non-null    float64
 21  Transport_public_score      280 non-null    float64
 22  Clima_tipus                 280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(7), int64(1), str(12)
memory usage: 79.8 KB

Las ciudades que no tienen datos y el número de trabajadores que están en ellas son:

In [478]:
dataset_s8[dataset_s8['Clima_tipus'].isna()].groupby(['Ciutat',dataset_s8['Clima_tipus'].fillna('No encontrat')]).size()

Ciutat     Clima_tipus
Köln       No encontrat     2
Màlaga     No encontrat    13
München    No encontrat     2
Nantes     No encontrat     3
Nice       No encontrat     2
Toulouse   No encontrat     3
Tromsø     No encontrat     1
Trondheim  No encontrat     1
dtype: int64

#### Politica de salarios

El archivo JSON tiene una estructura de codicion->porcentaje de aumento. Cada trabajador puede cumplir una o varias condiciones de aumento de salario, por lo que se opta por ir sumando el incremento de cada condición a medida que el usuario va cumpliendo condiciones. Tener en cuenta que el máximo de incremento es del 15% y el salario mínimo son 800.

Combinado con la información que aporta ciutat_context al dataser_s8 se obtiene un valor por el cual se incrementará el salario. Se creará una columna indicando el incremento y otra con el salario incrementado.

In [491]:
for key,value in politica_salarial.items():
    print(key,value)

base_increment_by_group {'Grup A': 5.0, 'Grup B': 3.5, 'Grup C': 2.0, 'Grup D': 8.0}
children_adjustment {'has_children': 1.5, 'no_children': 0.0}
age_adjustment {'18-29': 0.0, '30-44': 1.0, '45-59': 2.0, '60+': 1.5}
cost_of_living_adjustment {'low': 0.0, 'medium': 1.0, 'high': 2.0}
transport_adjustment {'low': 0.5, 'medium': 0.0, 'high': -0.5}
rules {'max_total_increment_percent': 15, 'min_salary_threshold': 800}

In [517]:
dataset_s8.iloc[0]['Nombre fills']

np.int64(3)

In [ ]:
def calcular_incremento_salarial(fila):
    incremento = 0
    # grupo professional
    if fila['Grup Professional'] in politica_salarial['base_increment_by_group']:
        incremento += politica_salarial['base_increment_by_group'][fila['Grup Professional']]

    # nombre de hijos
    if fila['Nombre fills'] > 0:
        incremento += politica_salarial['children_adjustment']['has_children']

    # edad
    if 30 <= fila['Edat'] <= 44:
        incremento += politica_salarial['age_adjustment']['30-44']
    elif 45 <= fila['Edat'] <= 59:
        incremento += politica_salarial['age_adjustment']['45-59']
    elif fila['Edat'] <= 60:
        incremento += politica_salarial['age_adjustment']['60+']

    #coste de vida
    if fila['Cost_vida_index']
    
    return incremento

prueba_dataset = dataset_s8.loc[1:10]
prueba_dataset['incremento'] = prueba_dataset.apply(calcular_incremento_salarial, axis=1)
prueba_dataset

,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual €,Grup Professional,Càrrec,...,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat,País,Cost_vida_index,Transport_public_score,Clima_tipus,incremento
1,4,Marc,Muñoz,48840994W,Espanya,Alacant,Home,2718.0,Grup C,Analista,...,1960-11-08,True,Analista senior,66.0,56 +,Espanya,68.0,7.0,Mediterrani,2.0
2,9,David,Gómez Vila,36998038E,Espanya,Palma,Dona,2349.0,Grup B,Cap de projecte,...,1971-09-25,True,NaN,55.0,46-55,Espanya,73.0,7.2,Mediterrani,3.5
3,10,Carmen,López,47376585K,Espanya,Barcelona,Home,2855.0,Grup C,Responsable de vendes,...,1962-09-08,True,NaN,64.0,56 +,Espanya,78.0,8.5,Mediterrani,2.0
4,13,Joana,Torres Díaz,82772208R,Espanya,Valladolid,Dona,982.0,Grup A,Administratiu,...,1961-10-24,True,NaN,65.0,56 +,Espanya,64.0,6.7,Continental,5.0
5,15,Aina,Pérez,31172421Z,Espanya,Las Palmas de Gran Canaria,Home,3672.0,Grup D,Cap de projecte,...,1973-06-10,True,NaN,53.0,46-55,Espanya,62.0,6.8,Subtropical,8.0
6,16,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,Dona,1003.0,Grup A,Cap de projecte,...,1961-02-21,True,NaN,65.0,56 +,Alemanya,79.0,7.9,Continental,5.0
7,17,Xavier,Casals,43491314K,Espanya,Alacant,Home,1800.0,Grup A,Analista,...,1980-04-22,True,Analista junior,46.0,46-55,Espanya,68.0,7.0,Mediterrani,5.0
8,18,Carmen,Hernández Serra,36786211Z,Espanya,Tarragona,Home,1336.0,Grup B,Administratiu,...,1960-08-08,True,NaN,66.0,56 +,Espanya,67.0,6.9,Mediterrani,3.5
9,20,Sigrid,Olsen,70604045C,Noruega,Bergen,Dona,1385.0,Grup A,Administratiu,...,1964-06-19,True,NaN,62.0,56 +,Noruega,85.0,8.8,Oceànic,5.0
10,21,Nil,Fernández Vidal,69345683K,Espanya,Bilbao,Home,1751.0,Grup B,Analista,...,1978-08-15,True,Analista senior,48.0,46-55,Espanya,72.0,7.8,Oceànic,3.5

In [ ]:
def calcular_incremento_salarial(valor):
    incremento = 0

    # grupo professional
    if valor in politica_salarial['base_increment_by_group']:
        incremento += politica_salarial['base_increment_by_group'][valor]

    return incremento

prueba_dataset = dataset_s8.loc[1:10]
prueba_dataset['incremento'] = prueba_dataset.iloc[:].apply(calcular_incremento_salarial)
prueba_dataset

TypeError: unhashable type: 'Series'