# NIVEL 1: 'EDA' ESTRUCTURADO Y LIMPIEZA DE DATOS

## EJERCICIO 1: EXPLORACIÓN INICIAL DEL DATASET

#### OBJETIVOS:
Con "sprint8_complex.xlsx" responder a las preguntas:

- Cuantas filas y columnas tiene el dataset
- Tipos de datos tiene cada columna
- Hay duplicados?
- Datos coherentes a simple vista?
- Posibles problemas o inconvenientes evidentes

Para responderlas hay que:

- Analizar la dimension del dataset
- Monstrar una muestra representativa de filas
- Revisar los tipos de variables
- Detectar duplicados
- Coherencia de datos
- Identificar y describir posibles problemas iniciales (sin solucionarlos)

Primero de todo instalo openpyxl para poder abrir el archivo xlsx. Pandas tiene la función de abrir un arhivo xlsx, pero necesita las instrucciones de openyxl para hacerlo.

pip install openpyxl

Importación de librerias necesarias para el analisis, limpieza y gestión del dataset

In [795]:
import pandas as pd
import datetime as dt

In [796]:
dataset_s8 = pd.read_excel('sprint8_complex.xlsx')
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Dades de l'enquesta de treballadors 2025  1008 non-null   object
 1   Unnamed: 1                                1007 non-null   str
 2   Unnamed: 2                                1007 non-null   str
 3   Unnamed: 3                                1007 non-null   str
 4   Unnamed: 4                                1007 non-null   str
 5   Unnamed: 5                                1007 non-null   str
 6   Unnamed: 6                                1007 non-null   str
 7   Unnamed: 7                                1007 non-null   str
 8   Unnamed: 8                                1007 non-null   str
 9   Unnamed: 9                                967 non-null    str
 10  Unnamed: 10                               1007 non-null   str
 11  Unnamed: 11                               420 non-null    str
 12  Unnamed: 12                               586 non-null    str
 13  Unnamed: 13                               1006 non-null   str
 14  Unnamed: 14                               1006 non-null   str
 15  Unnamed: 15                               710 non-null    object
 16  Unnamed: 16                               659 non-null    str
 17  Unnamed: 17                               316 non-null    object
 18  Unnamed: 18                               262 non-null    str
 19  Unnamed: 19                               937 non-null    str
dtypes: object(3), str(17)
memory usage: 255.9+ KB

##### Muestra del dataset (20 primeros)

In [797]:
dataset_s8.head(20)

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,6,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,7,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,10,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,11,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,12,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,13,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,14,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,15,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,16,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

##### Número de filas y columnas

In [798]:
print(f"Hay {dataset_s8.shape[0]} filas y {dataset_s8.shape[1]} columnas")

Hay 1010 filas y 20 columnas

##### Tipo de datos y cantidad

In [799]:
dataset_s8.dtypes.value_counts()

str       17
object     3
Name: count, dtype: int64

Hay 17 columnas de tipo str y 3 tipo object

##### Duplicados

El número de duplicados será 0 al tener en cuenta la primera columna. Se ha generado aleatoriamente un número, por lo que no contará como duplicado aún habiendo realmente duplicados.

In [800]:
dataset_s8.duplicated().sum()

np.int64(0)

En cambio, si quitamos la primera columna, si existen 6 filas repetidas. Por lo que aprovechamos para eliminarla, ya que funciona como un indice, pero ya hay un indice en la tabla.

In [801]:
dataset_s8.iloc[:,1:].duplicated().sum()

np.int64(6)

In [802]:
dataset_s8 = dataset_s8.drop(["Dades de l'enquesta de treballadors 2025"], axis=True)

In [803]:
dataset_s8.head(20)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
13,Joana,Torres DÃ­az,82772208R,Espanya,Valladolid,24.0,10.0,1961.0,F,982 â‚¬,NaN,True,Grup A,Administratiu,0.0,True,14178.0,7.7,38.0
14,Guillem,Vidal,52169044F,Espanya,Zaragoza,22.0,4.0,1974.0,H,"2,419 â‚¬",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,38.0
15,Aina,PÃ©rez,31172421Z,Espanya,Las Palmas de Gran Canaria,10.0,6.0,1973.0,H,"3,672 â‚¬",NaN,True,Grup D,Cap de projecte,NaN,True,10800.0,12.9,22.0
16,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,21.0,2.0,1961.0,D,"1,003 â‚¬",NaN,True,Grup A,Project lead,NaN,True,6931.0,12.2,12.4
17,Xavier,Casals,43491314K,Espanya,Alacant,22.0,4.0,1980.0,H,mil vuit-cents,NaN,True,Grup A,Analista junior,0.0,True,38248.0,0.5,19.7
18,Carmen,HernÃ¡ndez Serra,36786211Z,Espanya,Tarragona,8.0,8.0,1960.0,H,"1,336 â‚¬",True,NaN,Grup B,Administratiu,3.0,True,65950,NaN,NaN
19,Sara,HernÃ¡ndez Costa,91363974Q,Espanya,ValÃ¨ncia,14.0,6.0,2004.0,Home,982 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,15.8

##### Datos coherentes a simple vista?

Viendo la muestra, se detectan que hay columnas que se pueden juntar (Fills, No_Fills y Nombre_fills). Por el resto, está "bien" estructurado y solamente hay que pulir datos.

##### Futuros problemas

Existen columnas que se pueden juntar (fills, no_fills y nombre_fills)
Codificación de las variables es erronea y las palabras con acentos o signos especiales se ven afectadas.
Estandarización: el salario mensual hay usuarios que lo han puesto en numeros y otros en texto. La columna "dona" deberia ser genero y las variables H/M, pero hay "Dona".
En varias columnas hay números decimales cuando podrían ser enteros (n hijos)

## EJERCICIO 2: VALIDACIÓN BÀSICA DE DATOS Y DECISIONES DE ELIMINACIÓN 

Aspectos a validar:

- ¿Existen identificadores únicos (DNI) para cada persona?
- ¿Qué vas a hacer con las filas duplicadas o registros repetidos?
- ¿Existen valores obligatorios que faltan o información incoherente?
- ¿Detectos formatos incorrectos, errores de codificación o valores imposibles?

Concretamente, tendrás que:

- Corregir posibles problemas de codificación y acentuación en los nombres de las columnas y en los valores de texto, si procede.
- Detectar y eliminar filas duplicadas exactas, indicando cuántos registros se han eliminado.
- Comprobar la unicidad del DNI. En caso de detectar DNIs duplicados, deberás analizar la coherencia de la información asociada y descartar o anular los registros que no sean fiables, justificando claramente la decisión tomada.
- Identificar los campos clave que no deberían contener valores nulos, detectar registros con información insuficiente y eliminar únicamente aquellas filas completamente vacías o con información irrecuperable o no sustituible, explicando por qué no es posible ni razonable imputarlas.

##### DNI como identificadores

Para validar si existen DNIs y demás, es útil renombrar las columnas por su nombre correcto. En el dataframe se encuentran en la fila 3 (indice 2).

In [804]:
dataset_s8.columns = dataset_s8.iloc[2]
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8

Borro las 3 primeras filas porque no tienen datos

In [805]:
dataset_s8 = dataset_s8.drop(dataset_s8.index[0:3])
dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Si existen DNIs como identificadores. Ahora compruebo si son únicos o repetidos y los muestro.

In [806]:
dni_duplicado = dataset_s8[dataset_s8.duplicated(['DNI'])]
dni_duplicado.sort_values(by='DNI')

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
607,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 â‚¬",True,False,Grup A,Analista,1,True,50.0,NaN,14.2
757,Oriol,GÃ³mez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 â‚¬,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
761,Oriol,GÃ³mez,16618423V,Espanya,MÃ laga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
762,Oriol,GÃ³mez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 â‚¬",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
695,Alexia,PÃ©rez DÃ­az,49529438G,Espanya,MÃ laga,12.0,10.0,1981.0,Dona,1663â‚¬,NaN,True,Grup C,Cap de projecte,NaN,True,80000,10.7,16.9
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
145,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 â‚¬",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1006,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
107,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
117,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 â‚¬",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
284,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,TÃ¨cnic IT,0.0,True,63574.0,6.0,16.8
916,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1003,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1005,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7

Existen varios DNIs repetidos. En algunos casos solo 2 veces (los que se ven solo una vez en la tabla de arriba), pero otros tienen varias repeticiones y con distinto nombre de usuario.

La eliminación de los DNis repetidos lo haré en el siguiente paso. También los DNIs nulos

##### Registros duplicados y repetidos

Primero, corrijo la codificación por si existen registros duplicados, pero que tengan elementos bien codificados y otros mal. Si existiesen ese tipo de casos, no contarían como duplicados. Se aplica una corrección a todas las columnas.

Se crea una función para obtener un valor. Si el valor no es str lo devuelve.

Mientras hayan correcciones en valor (todo el codigo dentro de While) seguirá funcionando. Cuando no haya más cambios, parará (corregido = True/False)

Se han intrucido cp1252 y latin1 por si alguno no corrige correctamente el valor.

Se le agrega un replace para quitar los "_" de los titulos de las columnas.

Ejecuto un apply para que recorra las columnas y aplique con map la funcion a cada valor.

Solamente haciendo el cp1252 dejaba algún elemento sin corregir.

In [807]:
def corregir_texto(valor):
    if not isinstance(valor, str):
        return valor

    while True:
        corregido = False

        for encoding in ('cp1252', 'latin1'):
            try:
                nuevo = valor.encode(encoding).decode('utf-8')

                if nuevo != valor:
                    valor = nuevo
                    corregido = True
                    break

            except (UnicodeEncodeError, UnicodeDecodeError):
                pass

        if not corregido:
            break

    return valor.replace("_", ' ')

dataset_s8 = dataset_s8.apply(lambda col: col.map(corregir_texto))
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
660,Alessandro,Colombo Bianchi,18052256Q,Itàlia,Roma,12.0,1.0,1983.0,F,896 €,True,NaN,Grup A,Analista,2.0,True,62991.0,11.7,14.2
779,Lucas,Robert Martin,30960858T,França,Lille,25.0,12.0,1962.0,H,"1,348 €",NaN,True,Grup B,Data Analyst,NaN,False,NaN,NaN,12.4
708,Oriol,Álvarez Torres,41463449C,Espanya,Murcia,25.0,1.0,1966.0,H,3437€,True,NaN,Grup D,Responsable de vendes,3.0,NaN,NaN,NaN,19.0
131,Pau,Ramos,62443094H,Espanya,Bilbao,32.0,99.0,1940.0,D,1.636 €,NaN,True,Grup B,Analista junior,2.0,False,NaN,NaN,15.1
529,Carmen,Muñoz,88446018D,Espanya,Alacant,32.0,13.0,2019.0,NaN,"1,497 €",NaN,NaN,Grup B,Administratiu,0.0,True,80000,12.1,19.4
698,Alexia,Torres,36724504R,Espanya,Alacant,12.0,11.0,1978.0,H,"1,192 €",NaN,True,Grup B,Analista,NaN,False,NaN,NaN,17.0
952,Guillem,Torres Navarro,87466401Z,Espanya,València,18.0,11.0,1995.0,D,"1,073 €",NaN,True,Grup A,Analista,0.0,NaN,NaN,NaN,14.7
193,Jonas,Becker Wagner,71021210R,Alemanya,Frankfurt,16.0,7.0,1981.0,D,1363€,NaN,True,Grup B,Analista,NaN,False,NaN,NaN,11.5
600,Antoine,Laurent Durand,28051318X,França,Bordeaux,23.0,2.0,1980.0,A,"1,227 €",NaN,True,Grup A,Senior analyst,NaN,True,80657.0,6.6,13.0
679,Marie,Richter,57617011Q,Alemanya,Stuttgart,10.0,10.0,1962.0,Dona,"1,306 €",True,NaN,Grup B,Responsable de vendes,1,True,80000,25.0,13.1

Como la codificación se ha hecho después de definir el nombre de las columnas, "Càrrec" está mal escrita por lo que se lanza la función que se ha hecho antes a las columnas

In [808]:
dataset_s8.columns = dataset_s8.columns.map(corregir_texto)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
781,Marta,Puig,51373866L,Espanya,A Coruña,32.0,13.0,3000.0,H,1833€,True,NaN,Grup B,Data analyst,3.0,True,-50.0,NaN,13.8
869,Pau,Vidal,70513308V,Espanya,Valladolid,11.0,10.0,1971.0,D,816 €,True,True,Grup A,Responsable de vendes,2.0,True,30481.0,0.5,9.8
804,Sara,Navarro,77970791L,Espanya,Barcelona,7.0,4.0,1978.0,M,"1,497 €",NaN,True,Grup B,Analista,NaN,NaN,NaN,NaN,14.2
312,Ilaria,Rizzo,50513220Q,Itàlia,Milano,27.0,11.0,1962.0,D,"2,094 €",True,NaN,Grup B,Cap de projecte,1,NaN,NaN,NaN,15.1
809,Simone,Conti,67611249P,Itàlia,Napoli,2.0,1.0,1975.0,D,"1,849 €",NaN,True,Grup B,Cap de projecte,0.0,True,53342.0,0.5,19.0
234,Jordi,Álvarez,18067834D,Espanya,Valladolid,6.0,5.0,1960.0,D,"2,184 €",NaN,NaN,Grup B,Senior analyst,0.0,NaN,NaN,NaN,15.0
761,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
695,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000,10.7,16.9
771,Sergio,Ruiz,25101251Y,Espanya,Barcelona,24.0,8.0,1991.0,A,"1,255 €",NaN,True,Grup A,Responsable de vendes,0.0,True,80000,6.2,14.5
333,Núria,Costa,20498581L,Espanya,Valladolid,6.0,4.0,1969.0,NC,"1,577 €",True,True,Grup B,Cap de projecte,1.0,NaN,NaN,NaN,11.7

Ahora compruebo los registros duplicados y los borro.

In [809]:
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
43,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1005,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1006,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1007,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

Borramos los 4 registros duplicados.
Volvemos a comprobar los duplicados y ya no hay.

In [810]:
dataset_s8 = dataset_s8.drop_duplicates()
registros_duplicados = dataset_s8[dataset_s8.duplicated()]
registros_duplicados

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

Tomaré la columna DNI como dato identificador y único de los usuarios. Como se ha comprobado antes, existen DNIs repetidos. Antes de borrarlos, compruebo si hay DNI con mayusculas/minusculas, con espacios y guiones. De esta manera nos aseguramos borrar los adecuados.

In [811]:
dni_espacio = dataset_s8[dataset_s8['DNI'].str.contains(' ')]
dni_espacio

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

In [812]:
dni_guion = dataset_s8[dataset_s8['DNI'].str.contains('-')]
dni_guion

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

No hay DNIs con espacios ni con guiones, por lo que omito la acción de borrarlos DNIs.

Ahora pongo todas las letras de los DNIs en mayuscula y elimino los duplicados.

In [813]:
dataset_s8['DNI'] = dataset_s8['DNI'].str.upper()
dni_num_duplicados = dataset_s8.duplicated(subset=['DNI']).sum()
print(f"Se han eliminado {dni_num_duplicados} DNIs duplicados")
dataset_s8 = dataset_s8.drop_duplicates(subset=['DNI'])
dataset_s8.head(10)

Se han eliminado 11 DNIs duplicados

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
6,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,David,Gómez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 €",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
10,Carmen,López,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4.0,True,20000,5.9,15.4
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 €",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 €",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

Borrados los DNI duplicados, compruebo la longitud de estos. Un DNI español tiene 9 caracteres. En caso de que sean extranjeros con un NIE también son 9 caracteres.

Primero cuento los DNIs que no tienen esa longitud

In [814]:
dni_longitud_mal = dataset_s8[dataset_s8['DNI'].str.len() != 9]
dni_longitud_mal

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
1008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

Sabiendo que hay 2 filas con DNIs con una longitud diferente a 9. Los borro

In [815]:
def longitud_dni(valor):
    return isinstance(valor, str) and len(valor) == 9

dataset_s8 = dataset_s8[dataset_s8['DNI'].apply(longitud_dni)]
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
629,Alessandro,Barbieri,82745798H,Itàlia,Torino,19.0,5.0,2001.0,NC,"3,600 €",True,NaN,Grup D,Senior analyst,3.0,True,NaN,NaN,15.2
961,Ida,Johansen Kristiansen,41407343V,Noruega,Bergen,32.0,99.0,2019.0,D,"2,759 €",NaN,True,Grup C,Senior analyst,NaN,False,NaN,NaN,9.1
807,Marc,López Costa,11828041P,Espanya,Sevilla,30.0,8.0,1980.0,M,2406 euros,NaN,NaN,Grup C,Responsable de vendes,NaN,NaN,NaN,NaN,16.5
173,Nil,Ribera,55748676B,Espanya,Valladolid,31.0,8.0,2000.0,D,"1,156 €",NaN,True,Grup A,Analista,NaN,False,NaN,NaN,12.9
551,Aina,Ferrer,91151067N,Espanya,Zaragoza,2.0,11.0,1990.0,D,"1,450 €",True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,12.8
465,Núria,Vidal,48066060L,Espanya,Sevilla,13.0,2.0,1993.0,H,"1,047 €",NaN,True,Grup A,Senior analyst,0.0,NaN,NaN,NaN,17.6
251,Jordi,Moreno,62286700M,Espanya,Murcia,20.0,10.0,1968.0,H,2516€,True,NaN,Grup C,Analista junior,1.0,True,80000,13.8,20.0
981,Giulia,Conti Russo,72192924S,Itàlia,Bologna,29.0,10.0,1990.0,H,1931 euros,NaN,True,Grup C,Administratiu,0.0,NaN,NaN,NaN,15.0
158,Víctor,Díaz,60529679B,Espanya,A Coruña,29.0,7.0,1975.0,Dona,"1,654 €",True,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,-5.0
699,Alba,Sánchez,73542673S,Espanya,València,5.0,10.0,1965.0,H,"2,401 €",NaN,True,Grup C,Administratiu,NaN,True,74348.0,13.2,18.0

##### Valores nulos

Ante la existencia de los valores nulos, borro las filas que tengan TODAS las columnas con nulos. En este caso solo 1 fila tiene todo nulos.

In [816]:
num_nulos = dataset_s8.isna().all(axis=1).sum()
nulos = dataset_s8.isna().all(axis=1)
dataset_s8 = dataset_s8.dropna(how="all")
print(nulos)
num_nulos

3       False
4       False
5       False
6       False
7       False
        ...
999     False
1000    False
1001    False
1002    False
1004    False
Length: 990, dtype: bool

np.int64(0)

También compruebo si en DNI hay nulos. En este caso no hay.

In [817]:
dni_nulos = dataset_s8[dataset_s8['DNI'].isna()]
dni_nulos

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat]
Index: []

##### Formatos incorrectos

In [818]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat
291,Chiara,Lombardi,70187134V,Itàlia,Torino,12.0,3.0,1980.0,H,795 €,NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,-5.0
923,Adrià,Hernández,88629743T,Espanya,Tarragona,19.0,10.0,1997.0,F,"1,054 €",True,NaN,Grup A,Analista,1.0,True,24307.0,0.5,17.4
136,Adrià,Torres,22485824R,Espanya,Sevilla,32.0,99.0,1940.0,D,2093€,True,NaN,Grup B,Senior analyst,1.0,NaN,NaN,NaN,16.9
106,Víctor,Puig Pérez,57572279P,Espanya,Zaragoza,9.0,9.0,1997.0,Dona,"1,100 €",NaN,True,Grup A,Tècnic IT,NaN,True,20000,6.1,16.8
175,Adrià,Martínez,70465703Z,Espanya,Tarragona,25.0,2.0,1995.0,Dona,833€,NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,15.2
613,Laia,Domènech López,92586963B,Espanya,Sevilla,14.0,4.0,1962.0,D,1098€,NaN,True,Grup A,Responsable de vendes,0.0,NaN,NaN,NaN,19.1
964,Simone,Bianchi,51167664F,Itàlia,Milano,8.0,7.0,2000.0,H,"1,118 €",NaN,True,Grup A,Administratiu,0.0,NaN,NaN,NaN,12.8
906,Marie,Roux,76770443M,França,Lille,22.0,6.0,1977.0,NC,"1,353 €",True,NaN,Grup B,Analista,4.0,True,25193.0,NaN,9.4
351,Marie,Moreau,93041052V,França,Paris,7.0,2.0,1993.0,D,2180€,NaN,True,Grup C,Analyst,0.0,NaN,NaN,NaN,14.0
87,Carlos,Gil Soler,71694994V,Espanya,Las Palmas de Gran Canaria,6.0,6.0,1982.0,NC,1163 euros,NaN,True,Grup A,Administratiu,NaN,True,NaN,NaN,21.0

Corregido la codificación con el "cp1252" y "latin1", el formato que falla es el número de hijos, dia, mes y año de nacimiento. Estos parámetros deberían ser números enteros y no decimales (aunque realmente es un texto).

A continuación, busco todos los valores únicos de cada categoria para buscar valores imposibles, si son todos "decimales" u otra opción.

In [819]:
dataset_s8['Nombre fills'].unique()

array(['3.0', '0.0', '4.0', '2.0', nan, '1.0', 0, 1], dtype=object)

In [820]:
dataset_s8['Dia de Naixement'].unique()

<ArrowStringArray>
['23.0',  '8.0', '27.0', '13.0', '29.0',  '1.0', '25.0', '32.0', '24.0',
 '22.0', '10.0', '21.0', '14.0', '19.0', '15.0', '16.0', '11.0', '18.0',
 '28.0',  '9.0',  '3.0',  '2.0',  '0.0', '20.0',  '4.0', '-5.0', '26.0',
 '30.0', '17.0',  '5.0', '12.0',  '6.0',  '7.0', '31.0']
Length: 34, dtype: str

In [821]:
dataset_s8['Mes de Naixement'].unique()

<ArrowStringArray>
[ '3.0', '11.0',  '4.0', '10.0',  '8.0',  '9.0',  '0.0',  '6.0',  '2.0',
  '7.0',  '5.0', '12.0',  '1.0', '99.0', '13.0']
Length: 15, dtype: str

In [822]:
dataset_s8['Any de Naixement'].unique()

<ArrowStringArray>
['1958.0', '1960.0', '1961.0', '1985.0', '1965.0', '1978.0', '1971.0',
 '1962.0', '1963.0', '1940.0', '1974.0', '1973.0', '1980.0', '2004.0',
 '1964.0', '2002.0', '1993.0', '1972.0', '1982.0', '1987.0', '1992.0',
 '1994.0', '1967.0', '1990.0', '3000.0', '2019.0', '1976.0', '2001.0',
 '1997.0', '1984.0', '1977.0', '1988.0', '1995.0', '1981.0', '1983.0',
 '2003.0', '1991.0', '2000.0', '1989.0', '2026.0', '1966.0', '1959.0',
 '1969.0', '1975.0', '1986.0', '1999.0', '1979.0', '1996.0', '1998.0',
 '1970.0', '1968.0']
Length: 51, dtype: str

También las columnas Fills, No Fills y Te_cotxe deberian ser boleanas. Incluso Gènere si consideramos que solamente hay 2 generos. Fills y No Fills se fusionarán con Nombre fills y Te cotxe se modificará en el ejercicio 3.

Visto los datos únicos de cada columna se procede a cambiarlos de formato. Primero a float al tener escritura con decimales y despues a int64 (evita errores si hay nulos). Modifico las 4 columnas

In [823]:
columnas = ['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Nombre fills']
dataset_s8[columnas] = dataset_s8[columnas].astype(float).astype('Int64')
print(dataset_s8['Dia de Naixement'].unique())
dataset_s8.info()

<IntegerArray>
[23,  8, 27, 13, 29,  1, 25, 32, 24, 22, 10, 21, 14, 19, 15, 16, 11, 18, 28,
  9,  3,  2,  0, 20,  4, -5, 26, 30, 17,  5, 12,  6,  7, 31]
Length: 34, dtype: Int64
<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Dia de Naixement            990 non-null    Int64
 6   Mes de Naixement            990 non-null    Int64
 7   Any de Naixement            990 non-null    Int64
 8   Gènere                      951 non-null    str
 9   Salari mensual              990 non-null    str
 10  Fills                       414 non-null    str
 11  No Fills                    575 non-null    str
 12  Grup Professional           990 non-null    str
 13  Càrrec                      990 non-null    str
 14  Nombre fills                696 non-null    Int64
 15  Te cotxe                    647 non-null    str
 16  Km anuals                   310 non-null    object
 17  Consum mitja L 100km        257 non-null    str
 18  Temperatura mitjana ciutat  923 non-null    str
dtypes: Int64(4), object(1), str(14)
memory usage: 236.7+ KB

El siguiente paso es crear columna de fecha. Hay que unificarlas en una misma columna.

Pandas tiene una función de convertir a fecha y trabajar con ellas. errors='coerce' hace que si hay una fecha imposible (31 de febrero) sea un NA.

Igualmente se comprueba que no existan fechas superiores a la fecha de hoy. En valores únicos de 'Any de Naixement' usuarios han puesto que han nacido en el 3000 (dificil sin viaje en el tiempo) o en el 2019 (bastante ilegal en el 2026 trabajar a esa edad en España).

En la función es posible definir la edad mínima por la que queremos invalidar una fecha. En España la edad legal para trabajar son 16 años.

Con errors='coerce' se declaran nulas las fechas que en:
- 'Dia de Naixement' tenian un 32 o -5
- 'Mes de Naixement' tenian 99 y 13
- 'Any de Naixement' como tal no tenian años imposibles, pero si no se han declarado nulas las fechas con años 3000 o 2019 con el errors se han declarado al ser superiores a la fecha actual.

In [824]:
def crear_fecha(dia, mes, año, edad_minima=16):
    fecha = pd.to_datetime(
        {
            'year': año,
            'month': mes,
            'day': dia
        },
        errors='coerce'
    )

    if edad_minima is not None:
        limite = pd.Timestamp.today() - pd.DateOffset(years=edad_minima)
        fecha[fecha > limite] = pd.NaT

    return fecha

In [825]:
dataset_s8['Data de Naixement'] = crear_fecha(
    dataset_s8['Dia de Naixement'],
    dataset_s8['Mes de Naixement'],
    dataset_s8['Any de Naixement']
)

dataset_s8.head(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
3,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23,3,1958,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3,True,32108.0,25.0,10.1,1958-03-23
4,Marc,Muñoz,48840994W,Espanya,Alacant,8,11,1960,H,"2,718 €",NaN,True,Grup C,Senior analyst,0,True,19496.0,10.4,18.7,1960-11-08
5,Noa,Serra,14308421X,Espanya,Alacant,27,4,1961,D,1358 euros,True,NaN,Grup A,Tècnic IT,4,NaN,NaN,NaN,16.7,1961-04-27
6,Pol,Gil,58586340F,Espanya,Sevilla,13,10,1985,H,"1,478 €",True,NaN,Grup B,Data Analyst,2,False,NaN,NaN,18.3,1985-10-13
7,David,Vila,82070937P,Espanya,Bilbao,29,11,1965,Dona,"1,284 €",NaN,True,Grup B,Administratiu,<NA>,True,NaN,11.8,13.1,1965-11-29
8,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1,8,1978,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0,NaN,NaN,NaN,19.9,1978-08-01
9,David,Gómez Vila,36998038E,Espanya,Palma,25,9,1971,D,"2,349 €",NaN,True,Grup B,Cap de projecte,<NA>,True,6196.0,10.6,17.8,1971-09-25
10,Carmen,López,47376585K,Espanya,Barcelona,8,9,1962,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4,True,20000,5.9,15.4,1962-09-08
11,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8,3,1963,D,"1,338 €",NaN,True,Grup B,Analista junior,0,False,NaN,NaN,7.6,1963-03-08
12,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32,0,1940,H,"1,450 €",True,NaN,Grup A,Senior analyst,4,False,NaN,NaN,20.1,NaT

In [826]:
fechas_invalidas = dataset_s8[dataset_s8['Data de Naixement'] > pd.Timestamp.today()]
fechas_invalidas

Empty DataFrame
Columns: [Nom, Cognoms, DNI, País d'origen, Ciutat, Dia de Naixement, Mes de Naixement, Any de Naixement, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Càrrec, Nombre fills, Te cotxe, Km anuals, Consum mitja L 100km, Temperatura mitjana ciutat, Data de Naixement]
Index: []

Elimino las columnas de dia, mes y año ya que puedo obtener los mismos datos validos en la columna de fecha de aniversario.

In [827]:
dataset_s8 = dataset_s8.drop(['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement'], axis=1)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
797,Thomas,Fournier,24490208F,França,Toulouse,D,"1,843 €",NaN,True,Grup B,Senior analyst,0,False,NaN,NaN,13.5,1971-12-14
349,Anna,Díaz Domènech,56794869W,Espanya,Bilbao,NC,"2,285 €",NaN,True,Grup C,Analista,<NA>,NaN,NaN,NaN,14.9,1958-02-18
544,Núria,Serra Puig,27921592N,Espanya,Murcia,D,1199€,NaN,True,Grup A,Administratiu,<NA>,False,NaN,NaN,16.4,1966-06-25
448,Davide,Ferrari,93297363C,Itàlia,Firenze,D,1435 euros,True,NaN,Grup B,Analista,1,True,44565.0,6.1,16.1,1974-11-02
863,Thomas,David,27341287F,França,Bordeaux,Dona,n/d,True,NaN,Grup A,Tècnic IT,1,False,NaN,NaN,16.2,1972-06-08
786,Noa,Vidal López,75183333K,Espanya,Màlaga,Dona,723€,True,NaN,Grup A,Responsable de vendes,2,NaN,NaN,NaN,19.1,1961-08-19
430,David,Pujol Costa,86758847Y,Espanya,Zaragoza,D,"1,644 €",NaN,True,Grup B,Analista,<NA>,True,21422.0,9.8,16.7,1969-01-06
562,Irene,Torres,88803982Q,Espanya,Las Palmas de Gran Canaria,H,956€,NaN,True,Grup A,Administratiu,<NA>,False,NaN,NaN,21.2,1980-11-05
758,Jordi,Roca,12098146L,Espanya,Màlaga,H,1825 euros,True,NaN,Grup B,Administratiu,2,NaN,NaN,NaN,18.5,1982-09-11
479,Marina,Romero,11118688S,Espanya,A Coruña,NC,922 €,NaN,True,Grup A,Data Analyst,0,False,NaN,NaN,13.3,1980-05-04

## EJERCICIO 3: TRANSFORMACIONES NECESARIAS Y PREPARACIÓN DEL DATASET

Aspectos a revisar y transformar:

- ¿Los valores categóricos están normalizados y son consistentes?
- ¿Los valores nulos son coherentes con la información disponible?
- ¿Existe redundancia de variables que pueda generar problemas analíticos?
- ¿Las variables contextuales (como temperatura, salario) están completas y preparadas para el análisis?

Concretamente, tendrás que:

- Normalizar los valores categóricos para evitar ambigüedades (por ejemplo, valores que representan el mismo concepto pero están escritos de forma diferente).
- Revisar la coherencia de los valores nulos, asegurando que:
Las personas con kilometraje anual y consumo medio asociados disponen de coche. En los casos en que conste consumo medio pero no kilometraje anual, será necesario decidir cómo resolver esta incoherencia de forma justificada.
Las personas que tienen un valor en el número de hijos tienen efectivamente hijos.
- Unificar la información sobre hijos en una única columna, ya que mantener varias columnas con información complementaria no es óptimo y puede generar problemas analíticos (redundancia o multicolinealidad).
- Validar la temperatura media. En caso de que esa información falte, deberás imputarla utilizando un criterio razonable (por ciudad o por un nivel superior justificado).
- Revisar e imputar los salarios faltantes, aplicando criterios analíticos coherentes (como cargo, grupo profesional, ciudad, género o franja de edad).

In [828]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
600,Antoine,Laurent Durand,28051318X,França,Bordeaux,A,"1,227 €",NaN,True,Grup A,Senior analyst,<NA>,True,80657.0,6.6,13.0,1980-02-23
429,Xavier,Ramos,27305260D,Espanya,Las Palmas de Gran Canaria,H,845 €,NaN,True,Grup A,Analista,<NA>,NaN,NaN,NaN,NaN,1975-12-31
637,Alexia,Fernández,17921698S,Espanya,Zaragoza,D,1110 euros,NaN,True,Grup A,Senior analyst,0,False,NaN,NaN,17.3,1967-06-28
405,David,Vila,71174364G,Espanya,Barcelona,F,"1,511 €",NaN,True,Grup B,Cap de projecte,0,NaN,NaN,NaN,17.7,1976-04-16
988,Pol,García,76459478B,Espanya,Palma,H,"1,244 €",True,NaN,Grup B,Project lead,1,True,56745.0,NaN,NaN,1977-01-14
359,Alexia,Casals,35902794Z,Espanya,Murcia,D,1068€,NaN,NaN,Grup A,Analista,0,NaN,NaN,NaN,18.6,1987-06-30
322,Aina,Pérez Muñoz,80576741J,Espanya,A Coruña,F,"1,007 €",True,NaN,Grup A,Responsable de vendes,3,False,NaN,NaN,13.2,1994-02-01
930,Anna,Pérez Serra,81260169S,Espanya,Barcelona,H,1.927 €,True,NaN,Grup B,Senior analyst,3,NaN,NaN,NaN,16.6,1983-02-11
922,Nil,Hernández,60855083M,Espanya,Sevilla,H,"1,331 €",NaN,True,Grup B,Tècnic IT,0,NaN,NaN,NaN,17.6,1988-08-24
508,David,Ruiz,91274963P,Espanya,Alacant,M,931 €,NaN,True,Grup A,Cap de projecte,0,NaN,NaN,NaN,NaN,1995-11-05

##### Valores categóricos

Tomo como valores categóricos "Gènere", "Te_cotxe", "Grup Professional" y "Càrrec". Compruebo los valores únicos de cada uno.

Gènere tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo. Después cambiar formato a boolean

In [829]:
dataset_s8['Gènere'].unique()

<ArrowStringArray>
['Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A']
Length: 9, dtype: str

Te cotxe es correcto. Solo hay que cambiar formato a boolean

In [830]:
dataset_s8["Te cotxe"].unique()

<ArrowStringArray>
['True', nan, 'False']
Length: 3, dtype: str

Grup Professional se deja así tal cual. Las categorias están bien escritas.

In [831]:
dataset_s8['Grup Professional'].unique()

<ArrowStringArray>
['Grup B', 'Grup C', 'Grup A', 'Grup D']
Length: 4, dtype: str

Càrrec tiene varias opciones, por lo que se creará un diccionario con las diferentes opciones para estandarizarlo.

Una vez estandarizado se comparará vs Grup Professional si todas coinciden o hay discrepancias

In [832]:
dataset_s8['Càrrec'].unique()

<ArrowStringArray>
[      'Cap de projecte',        'Senior analyst',             'Tècnic IT',
          'Data Analyst',         'Administratiu', 'Responsable de vendes',
       'Analista junior',          'Project lead',                'Admin.',
               'Analyst',              'Analista',          'Data analyst',
       'Cap de Projecte']
Length: 13, dtype: str

##### Valores categóricos: Gènere

Antes de comenzar la estandarización de la columba Gènere, cuento cuantas filas hay nulas en la columna y cuantos registros hay por cada género especificado por el usuario. De este modo puedo comprobar después que se haya completado la estandarización completamente.

In [833]:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')
dataset_s8.groupby('Gènere').size()

Hay: 39 filas de género nulas y 951 no nulas

Gènere
A        24
D       320
Dona    118
F       107
H       274
Home     51
M        34
NC       23
dtype: int64

Creo un diccionario para estandarizar los valores de 'Gènere'. De 'Dona', 'H', 'D', 'F', 'Home', 'NC', 'M', nan, 'A' no se modificarán los nan, 'NC' y 'A'. Al hacer la transformación se borrarán. Los demás se asigna a 'Dona' o 'Home'.

No nulos hay 951 que se le restarán las 47 de 'A' y 'NC'. Quedarán 904 no nulos y 86 nulos si no falla la calculadora.

In [834]:
dicc_genere = {
    'Dona':'Dona', 
    'H': 'Home', 
    'D': 'Dona', 
    'F': 'Dona', 
    'Home': 'Home', 
    'M': 'Home', 
}

def estandarizar(elemento, diccionario):
    for categoria in diccionario:
        if elemento == categoria:
            return diccionario[categoria]

dataset_s8['Gènere'] = dataset_s8['Gènere'].apply(lambda x: estandarizar(x, dicc_genere))

#Aprovecho el mismo código de antes:
genero_no_nulo = dataset_s8['Gènere'].notna().sum()
genero_nulo = dataset_s8['Gènere'].isna().sum()
print(f'Hay: {genero_nulo} filas de género nulas y {genero_no_nulo} no nulas')


dataset_s8.groupby('Gènere').size()

Hay: 86 filas de género nulas y 904 no nulas

Gènere
Dona    545
Home    359
dtype: int64

##### Valores categóricos: Té cotxe

In [835]:
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement
464,Hugo,Bernard,96583583Q,França,Nice,Home,1207 euros,NaN,True,Grup B,Project lead,0,True,80000,4.8,14.6,1984-05-20
51,Víctor,Gómez Vila,41934639H,Espanya,Bilbao,Home,1739€,NaN,True,Grup C,Administratiu,0,False,NaN,NaN,12.1,1958-06-26
25,Valentina,Rossi,83300637L,Itàlia,Genova,Dona,"1,094 €",True,NaN,Grup A,Senior analyst,4,False,NaN,NaN,42.0,1982-07-18
753,Pau,Roca Muñoz,14804924E,Espanya,Valladolid,Dona,967 €,True,NaN,Grup A,Responsable de vendes,2,NaN,NaN,NaN,12.0,1992-09-15
305,Pau,Muñoz,41255233J,Espanya,València,Dona,"1,278 €",NaN,True,Grup A,Responsable de vendes,<NA>,NaN,NaN,NaN,17.1,1996-07-04
740,Elias,Hagen,81192277J,Noruega,Bergen,Home,"1,944 €",NaN,True,Grup C,Data Analyst,<NA>,False,NaN,NaN,-5.0,1966-02-11
49,Joana,Gil Ferrer,75679047L,Espanya,Girona,Dona,2130€,True,NaN,Grup C,Tècnic IT,4,False,NaN,NaN,13.1,1984-11-04
482,Sara,Puig,28603902Q,Espanya,Bilbao,Dona,1155€,NaN,True,Grup A,Responsable de vendes,<NA>,False,NaN,NaN,NaN,1982-07-04
322,Aina,Pérez Muñoz,80576741J,Espanya,A Coruña,Dona,"1,007 €",True,NaN,Grup A,Responsable de vendes,3,False,NaN,NaN,13.2,1994-02-01
588,David,Ruiz,23440304K,Espanya,Màlaga,Dona,1899 euros,NaN,True,Grup B,Data Analyst,0,NaN,NaN,NaN,19.1,NaT

Para la columna 'Té cotxe' el objetivo es convertirla en tipo boolean para que 0 = no coche (False) y 1 = si coche (True).

Igualmente se comprobará si hay valor en Km anuals o Consum mitja L 100km. Si tiene registro en alguna de las columnas se pondrá como True.

In [836]:
dataset_s8['Te cotxe'] = dataset_s8['Te cotxe'].astype(bool)
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Gènere                      904 non-null    str
 6   Salari mensual              990 non-null    str
 7   Fills                       414 non-null    str
 8   No Fills                    575 non-null    str
 9   Grup Professional           990 non-null    str
 10  Càrrec                      990 non-null    str
 11  Nombre fills                696 non-null    Int64
 12  Te cotxe                    990 non-null    bool
 13  Km anuals                   310 non-null    object
 14  Consum mitja L 100km        257 non-null    str
 15  Temperatura mitjana ciutat  923 non-null    str
 16  Data de Naixement           913 non-null    datetime64[us]
dtypes: Int64(1), bool(1), datetime64[us](1), object(1), str(13)
memory usage: 210.7+ KB

Comprobamos valores únicos de Km anual y Consum mitja L 100km para echar un ojo a los datos. A simple vista son numeros en formato str, por lo que después del proceso de 'Té cotxe' se transformarán en enteros o decimales.

In [837]:
dataset_s8['Consum mitja L 100km'].unique()

<ArrowStringArray>
['25.0', '10.4',    nan, '11.8', '10.6',  '5.9',  '7.7', '12.9', '12.2',
  '0.5',  '7.4', '12.0', '11.0',  '7.3',  '7.0', '11.7',  '7.6', '11.5',
  '6.1', '12.7', '10.1', '10.2',  '6.7',  '7.1', '13.6',  '9.6', '13.9',
  '8.0',  '4.7',  '5.0', '10.5',  '7.8', '13.4',  '6.2', '13.8', '11.6',
 '11.4',  '8.8',  '8.7',  '5.8',  '5.4',  '5.7',  '6.8', '10.8', '13.3',
  '4.9', '12.1', '11.2', '13.0',  '9.8',  '4.6', '14.0',  '4.8',  '9.2',
 '13.5', '12.5',  '8.2',  '4.5', '13.2',  '6.6',  '5.1',  '9.0',  '4.1',
 '13.7', '10.3', '12.8',  '8.4', '10.7', '10.0', '12.4', '13.1',  '6.4',
  '6.5',  '8.6',  '8.3', '12.6',  '4.4',  '5.6',  '5.5',  '8.9',  '6.9',
  '5.3',  '9.1',  '9.4']
Length: 84, dtype: str

In [838]:
dataset_s8['Km anuals'].unique()

array(['32108.0', '19496.0', nan, '6196.0', 20000, '14178.0', '10800.0',
       '6931.0', '38248.0', 65950, 80000, '64444.0', '22384.0',
       '116927.0', 50000, '78064.0', '114730.0', '60856.0', '29300.0',
       '113964.0', '39561.0', 65983, '29386.0', '42398.0', '76180.0',
       '106611.0', '35142.0', '19232.0', '23728.0', '3920.0', '23206.0',
       '5776.0', '13870.0', '104603.0', '37506.0', '99990.0', '67841.0',
       '59507.0', '48621.0', '27526.0', '62723.0', '26866.0', 70000,
       1000000, '5252.0', '81945.0', 30000, '6283.0', '113059.0', '0.0',
       '4103.0', '100054.0', '56135.0', '30452.0', '9639.0', '14109.0',
       '49000.0', '87108.0', '13833.0', '27752.0', '54025.0', '15579.0',
       '12947.0', '43566.0', '42512.0', '72237.0', '40723.0', '6140.0',
       '118147.0', '60652.0', 40000, '21069.0', '94969.0', '11362.0',
       '31309.0', '86060.0', '95003.0', '57089.0', '115098.0', '21422.0',
       '71500.0', '54623.0', '53463.0', '11346.0', '44565.0', '23129.0',
       '3936.0', '14527.0', '42899.0', '16390.0', '8516.0', '14892.0',
       '5584.0', '12431.0', '13407.0', '29278.0', '18378.0', '21062.0',
       '74741.0', '28115.0', '26936.0', '113145.0', '2938.0', '93114.0',
       '111435.0', '8460.0', '67158.0', '80657.0', '44563.0', '107311.0',
       '33895.0', '84895.0', '22880.0', '11090.0', '11169.0', '29434.0',
       '62991.0', '114489.0', '32431.0', '18402.0', '74348.0', '96645.0',
       '99638.0', '28988.0', '60905.0', '29952.0', '107127.0', '28726.0',
       '-50.0', '6377.0', '45301.0', '99431.0', '77960.0', '81381.0',
       '56365.0', '116654.0', '52646.0', '16998.0', '29847.0', '53342.0',
       '52327.0', '4934.0', '43088.0', '13608.0', '22166.0', '29464.0',
       '113111.0', '32672.0', '6369.0', '30481.0', '115076.0', '36221.0',
       '82014.0', '32217.0', '25193.0', '109099.0', '81219.0', '24307.0',
       '110775.0', '17246.0', '50370.0', '9017.0', '7861.0', '97162.0',
       '56745.0', '116027.0', '50453.0', '27921.0', '35591.0'],
      dtype=object)

Creo una nueva columna de coche calculado a partir de una condificon de si km anuals o consumo tienen valor generará True o False.

Utilizo fillna("") para substituir las filas sin datos para que no de un falso positivo.
ne("") es un not equal o != pero en metodo para pandas. Busca una celca vacía "".

In [839]:
dataset_s8['Te cotxe calculat'] = dataset_s8['Km anuals'].fillna("").ne("") | dataset_s8['Consum mitja L 100km'].fillna("").ne("")
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Te cotxe,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat
472,Aina,Romero Díaz,24384568A,Espanya,Madrid,Home,"2,456 €",NaN,True,Grup C,Project lead,<NA>,True,50000,0.5,16.1,NaT,True
935,Sergio,Casals García,76477652N,Espanya,A Coruña,Home,1578 euros,NaN,True,Grup A,Cap de projecte,0,True,-50.0,NaN,12.1,1994-01-14,True
588,David,Ruiz,23440304K,Espanya,Màlaga,Dona,1899 euros,NaN,True,Grup B,Data Analyst,0,True,NaN,NaN,19.1,NaT,False
794,Paolo,Lombardi De Luca,98399977K,Itàlia,Bologna,Home,2.870 €,NaN,True,Grup D,Tècnic IT,<NA>,True,NaN,NaN,12.0,1987-10-26,False
674,Giorgio,Lombardi,36224131L,Itàlia,Torino,Dona,947 €,True,NaN,Grup A,Analista junior,4,True,NaN,NaN,10.1,1968-04-01,False
219,Jordi,Sánchez,14497675Y,Espanya,Murcia,Dona,1379€,True,NaN,Grup B,Responsable de vendes,4,True,NaN,NaN,19.7,1982-08-08,False
864,Elias,Pettersen Karlsen,48272885X,Noruega,Oslo,NaN,1.237 €,NaN,True,Grup A,Data Analyst,0,True,80000,10.4,10.3,1984-01-01,True
412,Francesca,Esposito,98336655T,Itàlia,Roma,Dona,1.552 €,True,NaN,Grup A,Senior analyst,1,True,NaN,NaN,13.4,1992-03-14,False
734,Irene,Ribera,71153456W,Espanya,Zaragoza,Home,2.613 €,NaN,True,Grup D,Administratiu,<NA>,True,NaN,NaN,17.2,1959-07-05,False
763,Laia,Martínez Díaz,41150534W,Espanya,Alacant,Dona,1409 euros,True,NaN,Grup A,Senior analyst,1,True,NaN,NaN,17.4,1972-10-21,False

Compruebo si hay alguna incongruencia con Te cotxe vs la columna calculada

In [840]:
coche_falso = dataset_s8['Te cotxe'] != dataset_s8['Te cotxe calculat']
coche_falso.value_counts()

True     678
False    312
Name: count, dtype: int64

Hay 312 que son iguales y 678 que la columna Te cotxe y la calculada son diferentes. Compruebo la cantidad de nulos que hay en Km anuals y Consum mitja L 100km.

In [841]:
dataset_s8.isna().sum()

2
Nom                             0
Cognoms                         0
DNI                             0
País d'origen                   0
Ciutat                          0
Gènere                         86
Salari mensual                  0
Fills                         576
No Fills                      415
Grup Professional               0
Càrrec                          0
Nombre fills                  294
Te cotxe                        0
Km anuals                     680
Consum mitja L 100km          733
Temperatura mitjana ciutat     67
Data de Naixement              77
Te cotxe calculat               0
dtype: int64

Al tener una cantidad importante de nulos en ambas columnas (más de la mitad) opto por dar como correcta la columna de 'Te cotxe calculat'. Por lo tanto, borro la columna 'Te cotxe' y mantengo la otra

In [842]:
dataset_s8.drop(columns='Te cotxe',inplace=True)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat
897,Charlotte,Klein,88228686A,Alemanya,Düsseldorf,Dona,"1,166 €",True,NaN,Grup B,Administratiu,2,NaN,NaN,8.2,NaT,False
869,Pau,Vidal,70513308V,Espanya,Valladolid,Dona,816 €,True,True,Grup A,Responsable de vendes,2,30481.0,0.5,9.8,1971-10-11,True
670,Lucas,Michel,41162770A,França,Toulouse,Home,"1,619 €",True,True,Grup B,Analista junior,0,NaN,NaN,14.0,1982-08-07,False
144,Marta,López Soler,53299069G,Espanya,Murcia,Dona,1.106 €,NaN,True,Grup A,Data Analyst,0,NaN,NaN,17.4,1964-06-10,False
87,Carlos,Gil Soler,71694994V,Espanya,Las Palmas de Gran Canaria,NaN,1163 euros,NaN,True,Grup A,Administratiu,<NA>,NaN,NaN,21.0,1982-06-06,False
496,Marina,Ribera,68589370R,Espanya,Palma,Dona,"1,385 €",NaN,True,Grup B,Senior analyst,0,18378.0,NaN,18.6,1980-04-11,True
399,Alexia,Hernández,55171003B,Espanya,Las Palmas de Gran Canaria,NaN,1.099 €,NaN,True,Grup A,Cap de Projecte,<NA>,NaN,NaN,19.8,1979-10-14,False
171,Marc,Moreno,98813650F,Espanya,Valladolid,Home,"1,281 €",True,True,Grup A,Responsable de vendes,0,99990.0,11.8,11.2,1997-02-14,True
794,Paolo,Lombardi De Luca,98399977K,Itàlia,Bologna,Home,2.870 €,NaN,True,Grup D,Tècnic IT,<NA>,NaN,NaN,12.0,1987-10-26,False
710,Aina,Serra,90741671H,Espanya,Zaragoza,Dona,979 euros,True,NaN,Grup A,Administratiu,3,99638.0,6.4,16.0,1998-07-22,True

El siguiente paso es convertir a decimales km anuals y consum mitja L 100km.

In [843]:
dataset_s8['Km anuals'] = dataset_s8['Km anuals'].astype(float)
dataset_s8['Consum mitja L 100km'] = dataset_s8['Consum mitja L 100km'].astype(float)
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 990 entries, 3 to 1004
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         990 non-null    str
 1   Cognoms                     990 non-null    str
 2   DNI                         990 non-null    str
 3   País d'origen               990 non-null    str
 4   Ciutat                      990 non-null    str
 5   Gènere                      904 non-null    str
 6   Salari mensual              990 non-null    str
 7   Fills                       414 non-null    str
 8   No Fills                    575 non-null    str
 9   Grup Professional           990 non-null    str
 10  Càrrec                      990 non-null    str
 11  Nombre fills                696 non-null    Int64
 12  Km anuals                   310 non-null    float64
 13  Consum mitja L 100km        257 non-null    float64
 14  Temperatura mitjana ciutat  923 non-null    str
 15  Data de Naixement           913 non-null    datetime64[us]
 16  Te cotxe calculat           990 non-null    bool
dtypes: Int64(1), bool(1), datetime64[us](1), float64(2), str(12)
memory usage: 209.7 KB

Ahora compruebo la distribución de km y consumo. Si ambos estan informados o si uno de los dos falla.

In [844]:
print("Ambos informados:",
      ((dataset_s8['Km anuals'].notna()) &
       (dataset_s8['Consum mitja L 100km'].notna())).sum())

print("Km si, consumo no:",
      ((dataset_s8['Km anuals'].notna()) &
       (dataset_s8['Consum mitja L 100km'].isna())).sum())

print("Km no, consumo si:",
      ((dataset_s8['Km anuals'].isna()) &
       (dataset_s8['Consum mitja L 100km'].notna())).sum())

Ambos informados: 255
Km si, consumo no: 55
Km no, consumo si: 2

Obtengo la desviación estandar, media, mediana, modo, maximo y minimo para las columnas Km anuals y Consum mitja L 100km

In [845]:
km_desviacion = dataset_s8['Km anuals'].std()
km_media = dataset_s8['Km anuals'].mean()
km_mediana = dataset_s8['Km anuals'].median()
km_mode = dataset_s8['Km anuals'].mode()
km_max = dataset_s8['Km anuals'].max()
km_min = dataset_s8['Km anuals'].min()
print(f"""Km anuals:
km desviacion = {km_desviacion}
km media = {km_media}
km mediana = {km_mediana}
km_mode = {km_mode}
km_max = {km_max}
km_min = {km_min}""")

Km anuals:
km desviacion = 62464.19789379955
km media = 56031.04516129032
km mediana = 55379.0
km_mode = 0    80000.0
Name: Km anuals, dtype: float64
km_max = 1000000.0
km_min = -50.0

In [846]:
consum_desviacion = dataset_s8['Consum mitja L 100km'].std()
consum_media = dataset_s8['Consum mitja L 100km'].mean()
consum_mediana = dataset_s8['Consum mitja L 100km'].median()
consum_mode = dataset_s8['Consum mitja L 100km'].mode()
consum_max = dataset_s8['Consum mitja L 100km'].max()
consum_min = dataset_s8['Consum mitja L 100km'].min()
print(f"""consum data:
consum desviacion = {consum_desviacion}
consum media = {consum_media}
consum mediana = {consum_mediana}
consum mode = {consum_mode}
consum max = {consum_max}
consum min = {consum_min}""")

consum data:
consum desviacion = 8.832870803940532
consum media = 11.070038910505836
consum mediana = 9.8
consum mode = 0    25.0
Name: Consum mitja L 100km, dtype: float64
consum max = 25.0
consum min = 0.5

Hay una gran desviación en ambas columnas (casi más que el valor del promedio/media).

Los maximos y mínimos en ambas columnas son demasiado extremos. Incluso hay negativos.

Primero calculo la correlación.

In [847]:
dataset_s8[['Km anuals', 'Consum mitja L 100km']].corr()

2                     Km anuals  Consum mitja L 100km
2
Km anuals               1.00000               0.13008
Consum mitja L 100km    0.13008               1.00000

Al tener una asociación pequeña, averiguo la media, mediana y correlacion de consum por cada quartil de km anuals.

In [848]:
dataset_s8.groupby(pd.qcut(dataset_s8['Km anuals'], q=4))['Consum mitja L 100km'].agg(['mean','median','std'])

                           mean  median       std
Km anuals
(-50.001, 22508.0]     8.947170    8.20  5.986318
(22508.0, 55379.0]    11.059701   10.20  9.850182
(55379.0, 80000.0]    12.065686   11.45  9.220054
(80000.0, 1000000.0]  10.978788    9.40  8.987935

In [849]:
dataset_s8.groupby(pd.qcut(dataset_s8['Consum mitja L 100km'], q=4))['Km anuals'].agg(['mean','median','std'])

                              mean   median            std
Consum mitja L 100km
(0.499, 4.6]          56512.276923  53342.0   27854.640887
(4.6, 9.8]            50127.359375  41256.0   32011.173308
(9.8, 13.7]           56468.873016  65983.0   33683.085908
(13.7, 25.0]          77844.253968  80000.0  121121.637917

La desviación es bastante grande, por lo que muestra una gran variabilidad de dados. Una posibilidad es rellenar a partir de media, desviación u otros, pero empujaría la estadística hacia lo standard. Los km anuales son muy variables debido a que un usuario puede vivir a 10km o 100km de su trabajo. El consumo es igual de variable dependiendo de las características del vehículo y el estílo de conducción del usuario.

Teniendo en cuenta estos datos, opto solamente por borrar los valores negativos de km anual. Las filas sin datos no las modifico.

In [850]:
dataset_s8 = dataset_s8[dataset_s8['Km anuals']>=0]
dataset_s8['Km anuals'].min()

np.float64(0.0)

##### Valores categóricos: Càrrec

En Càrrec hay que estandarizar los nombres de los cargos. Al estandarizarlo, es posible que cada grupo profesional esté relacionado con un cargo (o no). Ya dependerá de la organización de la empresa.

In [851]:
dataset_s8.groupby(['Càrrec','Grup Professional']).size()

Càrrec                 Grup Professional
Admin.                 Grup A                1
                       Grup B                3
Administratiu          Grup A                9
                       Grup B               13
                       Grup C                7
                       Grup D                2
Analista               Grup A               16
                       Grup B               16
                       Grup C                6
Analista junior        Grup A               21
                       Grup B                8
                       Grup C                7
                       Grup D                2
Analyst                Grup B                2
Cap de Projecte        Grup A                1
                       Grup B                1
Cap de projecte        Grup A               10
                       Grup B               13
                       Grup C                6
                       Grup D                3
Data Analyst           Grup A               22
                       Grup B               15
                       Grup C                1
                       Grup D                1
Data analyst           Grup A                1
                       Grup B                1
                       Grup C                1
Project lead           Grup A                4
                       Grup B                2
                       Grup C                1
Responsable de vendes  Grup A               17
                       Grup B               14
                       Grup C                4
                       Grup D                1
Senior analyst         Grup A               15
                       Grup B               15
                       Grup C                3
                       Grup D                2
Tècnic IT              Grup A               22
                       Grup B               11
                       Grup C                2
                       Grup D                2
dtype: int64

Visto que muchos puestos son lo mismo pero escritos de distinta forma o idiomas, primero estandarizo. Para ello necesito los valores únicos de Càrrec y aprovecho la función que he creado antes (estandarizar)

In [852]:
dataset_s8.groupby('Càrrec').size()

Càrrec
Admin.                    4
Administratiu            31
Analista                 38
Analista junior          38
Analyst                   2
Cap de Projecte           2
Cap de projecte          32
Data Analyst             39
Data analyst              3
Project lead              7
Responsable de vendes    36
Senior analyst           35
Tècnic IT                37
dtype: int64

Se igualan:
- Cap de projecte, Cap de Projecte y Project lead como Cap de projecte
- Admin. y Administratiu como Administratiu
- Data Analyst, Data analyst, Analista, Senior analyst y Analista jr como Analista. Al final, independientemente del grado de especialización o conocimientos todos son analistas.

Se mantienen:
- Tècnic IT
- Responsable de vendes

Para no perder datos, se crea una columna "Categoria càrrec" donde se indique jr y senior o data analyst.

In [853]:
diccionario_carrec = {
    'Cap de projecte': 'Cap de projecte',
    'Senior analyst':'Analista',
    'Responsable de vendes':'Responsable de vendes',
    'Administratiu':'Administratiu',
    'Project lead':'Cap de projecte',
    'Analista junior':'Analista',
    'Admin.':'Administratiu',
    'Tècnic IT':'Tècnic IT',
    'Analista':'Analista',
    'Data Analyst':'Analista',
    'Analyst':'Analista',
    'Data analyst':'Analista',
    'Cap de Projecte':'Cap de projecte'
}

diccionario_categoria = {
    'Senior analyst': 'Analista senior',
    'Analista junior': 'Analista junior',
    'Data analyst': 'Analista de dades',
    'Data Analyst': 'Analista de dades',
    'Analista': 'Analista'
}

# 2 maneras diferentes de agregar datos con un diccionario.
dataset_s8['Categoria càrrec'] = dataset_s8['Càrrec'].apply(lambda x: estandarizar(x, diccionario_categoria))
dataset_s8['Càrrec'] = dataset_s8['Càrrec'].map(diccionario_carrec)

In [854]:
dataset_s8.groupby(['Categoria càrrec','Càrrec']).size()

Categoria càrrec   Càrrec
Analista           Analista    38
Analista de dades  Analista    42
Analista junior    Analista    38
Analista senior    Analista    35
dtype: int64

In [855]:
dataset_s8.groupby('Càrrec').size()

Càrrec
Administratiu             35
Analista                 155
Cap de projecte           41
Responsable de vendes     36
Tècnic IT                 37
dtype: int64

Estandarizado el nombre del càrrec, lo volvemos a confrontar con el grup profesional.

In [856]:
dataset_s8.groupby(['Càrrec','Grup Professional']).size()

Càrrec                 Grup Professional
Administratiu          Grup A               10
                       Grup B               16
                       Grup C                7
                       Grup D                2
Analista               Grup A               75
                       Grup B               57
                       Grup C               18
                       Grup D                5
Cap de projecte        Grup A               15
                       Grup B               16
                       Grup C                7
                       Grup D                3
Responsable de vendes  Grup A               17
                       Grup B               14
                       Grup C                4
                       Grup D                1
Tècnic IT              Grup A               22
                       Grup B               11
                       Grup C                2
                       Grup D                2
dtype: int64

Aún existen variedad de Grup Professional para un mismo cargo, pero se observa que la mayoría están en el grupo professional A-B. Dependerá del rango de edad la permanencia a cada uno. Para averiguarlo creo un rango de edad a partir de la edad

In [857]:
dataset_s8['Edat'] =  (pd.Timestamp.today().year - dataset_s8['Data de Naixement'].dt.year )
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat
834,Alba,Torres Navarro,83919680R,Espanya,Barcelona,Dona,"1,778 €",True,NaN,Grup B,Administratiu,2,65983.0,12.6,38.0,1966-08-20,True,NaN,60.0
381,Anna,Puig,92279159M,Espanya,Valladolid,Dona,"1,222 €",NaN,True,Grup A,Tècnic IT,0,40723.0,25.0,9.8,2003-05-13,True,NaN,23.0
823,Thomas,Leroy,49412831B,França,Bordeaux,Dona,803 €,NaN,True,Grup A,Responsable de vendes,0,20000.0,8.6,NaN,1993-06-22,True,NaN,33.0
89,Aina,Ferrer,85432781E,Espanya,Valladolid,Dona,"1,436 €",True,NaN,Grup A,Cap de projecte,1,65983.0,11.7,15.9,1992-05-30,True,NaN,34.0
783,Guillem,Muñoz Pérez,18160765Z,Espanya,Girona,Dona,935 €,True,NaN,Grup A,Analista,2,80000.0,0.5,8.1,2004-02-11,True,Analista junior,22.0
16,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,Dona,"1,003 €",NaN,True,Grup A,Cap de projecte,<NA>,6931.0,12.2,12.4,1961-02-21,True,NaN,65.0
15,Aina,Pérez,31172421Z,Espanya,Las Palmas de Gran Canaria,Home,"3,672 €",NaN,True,Grup D,Cap de projecte,<NA>,10800.0,12.9,22.0,1973-06-10,True,NaN,53.0
390,Paolo,Russo,39855935L,Itàlia,Napoli,Dona,1459€,NaN,True,Grup B,Tècnic IT,4,118147.0,10.2,17.4,1973-11-23,True,NaN,53.0
832,Sergio,Casals Navarro,33776348M,Espanya,València,Dona,1.021 €,True,NaN,Grup A,Analista,3,13608.0,NaN,21.3,1961-11-23,True,Analista,65.0
385,Marina,Álvarez,60653170Y,Espanya,Alacant,Home,"1,725 €",NaN,True,Grup B,Administratiu,0,6140.0,13.3,18.9,1996-01-02,True,NaN,30.0

In [858]:
def rango_edad(edad):
    if 16 <= edad <= 24:
        return '16-24'
    elif 25 <= edad <= 35:
        return '25-35'
    elif 36 <= edad <= 45:
        return '36-45'
    elif 46 <= edad <= 55:
        return '46-55'
    elif edad >= 56:
        return '56 +'

In [859]:
dataset_s8['Grup edat'] = dataset_s8['Edat'].apply(rango_edad)
dataset_s8.sample(10)

2,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
978,Alba,Díaz,61448694R,Espanya,Madrid,Dona,950€,True,NaN,Grup A,Cap de projecte,1,80000.0,0.5,19.0,1987-11-06,True,NaN,39.0,36-45
837,Aina,Martínez,26818338E,Espanya,Palma,NaN,"2,147 €",NaN,True,Grup B,Analista,<NA>,30000.0,12.9,19.4,1988-09-09,True,NaN,38.0,36-45
360,Noah,Schröder,91339562Y,Alemanya,Köln,Dona,842 euros,NaN,True,Grup A,Analista,<NA>,43566.0,25.0,-5.0,1989-12-23,True,Analista,37.0,36-45
668,Marta,Pujol,83617175V,Espanya,Madrid,Dona,1595€,NaN,NaN,Grup A,Cap de projecte,<NA>,80000.0,10.7,15.9,1962-05-04,True,NaN,64.0,56 +
419,Nicolas,David,92716588Y,França,Marseille,Dona,1104€,True,NaN,Grup A,Analista,1,57089.0,11.2,13.6,NaT,True,Analista,NaN,NaN
809,Simone,Conti,67611249P,Itàlia,Napoli,Dona,"1,849 €",NaN,True,Grup B,Cap de projecte,0,53342.0,0.5,19.0,1975-01-02,True,NaN,51.0,46-55
337,Núria,Ruiz,90812511E,Espanya,Màlaga,Dona,"1,287 €",True,NaN,Grup A,Responsable de vendes,3,15579.0,10.2,18.3,2001-06-30,True,NaN,25.0,25-35
240,Laia,Romero,37223861Y,Espanya,Sevilla,Dona,1758€,NaN,True,Grup B,Analista,0,80000.0,25.0,19.0,1975-07-08,True,Analista junior,51.0,46-55
446,Núria,Casals Díaz,62027391F,Espanya,Màlaga,Dona,2.121 €,NaN,True,Grup B,Analista,<NA>,11346.0,11.6,NaN,1985-01-29,True,Analista senior,41.0,36-45
747,Nil,Martínez Fernández,81696670A,Espanya,Bilbao,Home,1280€,NaN,True,Grup A,Analista,2,99431.0,25.0,NaN,1964-07-16,True,Analista de dades,62.0,56 +

In [860]:
dataset_s8['Grup edat'].value_counts(dropna=False)

Grup edat
56 +     86
36-45    63
25-35    59
46-55    55
NaN      24
16-24    17
Name: count, dtype: int64

Para hacernos una idea aproximada, agrupamos los grupos profesionales con los grupos de edad que se han creado.

In [861]:
dataset_s8.groupby(['Grup Professional',dataset_s8['Grup edat'].fillna("")]).size()

Grup Professional  Grup edat
Grup A                          11
                   16-24        11
                   25-35        29
                   36-45        27
                   46-55        23
                   56 +         38
Grup B                           9
                   16-24         5
                   25-35        23
                   36-45        24
                   46-55        21
                   56 +         32
Grup C                           3
                   16-24         1
                   25-35         4
                   36-45         7
                   46-55        10
                   56 +         13
Grup D                           1
                   25-35         3
                   36-45         5
                   46-55         1
                   56 +          3
dtype: int64

##### Valores nulos

In [862]:
dataset_s8.info()

<class 'pandas.DataFrame'>
Index: 304 entries, 3 to 1004
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         304 non-null    str
 1   Cognoms                     304 non-null    str
 2   DNI                         304 non-null    str
 3   País d'origen               304 non-null    str
 4   Ciutat                      304 non-null    str
 5   Gènere                      279 non-null    str
 6   Salari mensual              304 non-null    str
 7   Fills                       121 non-null    str
 8   No Fills                    182 non-null    str
 9   Grup Professional           304 non-null    str
 10  Càrrec                      304 non-null    str
 11  Nombre fills                209 non-null    Int64
 12  Km anuals                   304 non-null    float64
 13  Consum mitja L 100km        255 non-null    float64
 14  Temperatura mitjana ciutat  285 non-null    str
 15  Data de Naixement           280 non-null    datetime64[us]
 16  Te cotxe calculat           304 non-null    bool
 17  Categoria càrrec            153 non-null    str
 18  Edat                        280 non-null    float64
 19  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(3), str(14)
memory usage: 74.3 KB

Las únicas columnas con nulos son las siguientes:

In [863]:
for col in dataset_s8.columns:
    if dataset_s8[col].isna().sum() > 0:
        print(col)

Gènere
Fills
No Fills
Nombre fills
Consum mitja L 100km
Temperatura mitjana ciutat
Data de Naixement
Categoria càrrec
Edat
Grup edat

Fills/No Fills ahora se fusionarán con Nombre fills. El resto tienen un número relativamente bajo de nulos (no más de 30 nulos). Excepto Categoria càrrec porque solo engloba al cargo Analista.

Los datos importantes para identificar a los usuarios es DNI que no tiene nulos ni duplicados.

##### Valores redundantes

En este apartado es donde se juntarán Fills/No Fills con Nombre de Fills. Para contar cuantas veces aparece True/False en cada columna por valor único de Nombre fills hay que poner FIlls/No Fills boleanas.

In [864]:
dataset_s8['Fills'].unique()

<ArrowStringArray>
['True', nan]
Length: 2, dtype: str

In [865]:
dataset_s8['No Fills'].unique()

<ArrowStringArray>
[nan, 'True']
Length: 2, dtype: str

Necesitamos hacer un crosstab porque el agrupar por Nombre fills y contar cuantas veces sale Fills/No Fills no funciona correctamente.

In [866]:
pd.crosstab(
    dataset_s8['Nombre fills'],
    dataset_s8['No Fills'].isna()
)

No Fills      False  True
Nombre fills
0                90      2
1                 2     61
2                 3     17
3                 1     13
4                 1     19

In [867]:
pd.crosstab(
    dataset_s8['Nombre fills'],
    dataset_s8['Fills'].isna()
)

Fills         False  True
Nombre fills
0                 9     83
1                61      2
2                18      2
3                14      0
4                19      1

Teniendo en cuenta que la columna Nombre fills es la que tiene valor de referencia y es la verdad absoluta, Crosstab muestra que la mayoria de usuarios que pusieron que tenian 0 hijos, luego contestaron mal a Fills/No Fills.
El resto de personas con +1 hijos contestaron con sentido el formulario. 

Teniendo en cuenta que las personas que si tienen hijos pero han contestado 0 hijos (83 en la columna 'Fills' y 90 en 'No Fills') y la diferencia sería cambiar el total en +7 personas con hijos se opta por dejar la columna 'Nombre fills' tal y como está y borrar las columnas Fills y No Fills.

Aprovecho para darle un reset al indice

In [869]:
dataset_s8 = dataset_s8.drop(['Fills','No Fills'], axis=1).reset_index()
dataset_s8.sample(5)

2,index,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre fills,Km anuals,Consum mitja L 100km,Temperatura mitjana ciutat,Data de Naixement,Te cotxe calculat,Categoria càrrec,Edat,Grup edat
33,120,Irene,Romero Roca,32396311S,Espanya,A Coruña,Home,"2,901 €",Grup C,Cap de projecte,1,50000.0,0.5,19.3,1999-03-18,True,NaN,27.0,25-35
251,837,Aina,Martínez,26818338E,Espanya,Palma,NaN,"2,147 €",Grup B,Analista,<NA>,30000.0,12.9,19.4,1988-09-09,True,NaN,38.0,36-45
32,112,Katharina,Braun Fischer,93240786N,Alemanya,Leipzig,NaN,mil vuit-cents,Grup B,Administratiu,1,76180.0,NaN,9.1,1958-07-11,True,NaN,68.0,56 +
47,164,Alejandro,Sánchez Vidal,49034245Z,Espanya,Bilbao,Dona,"3,026 €",Grup D,Administratiu,<NA>,37506.0,13.9,13.5,1962-01-10,True,NaN,64.0,56 +
126,437,Xavier,Hernández,29950518C,Espanya,Màlaga,Dona,1031€,Grup A,Analista,<NA>,71500.0,14.0,19.8,1962-01-28,True,Analista de dades,64.0,56 +

In [870]:
dataset_s8.info()

<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       304 non-null    int64
 1   Nom                         304 non-null    str
 2   Cognoms                     304 non-null    str
 3   DNI                         304 non-null    str
 4   País d'origen               304 non-null    str
 5   Ciutat                      304 non-null    str
 6   Gènere                      279 non-null    str
 7   Salari mensual              304 non-null    str
 8   Grup Professional           304 non-null    str
 9   Càrrec                      304 non-null    str
 10  Nombre fills                209 non-null    Int64
 11  Km anuals                   304 non-null    float64
 12  Consum mitja L 100km        255 non-null    float64
 13  Temperatura mitjana ciutat  285 non-null    str
 14  Data de Naixement           280 non-null    datetime64[us]
 15  Te cotxe calculat           304 non-null    bool
 16  Categoria càrrec            153 non-null    str
 17  Edat                        280 non-null    float64
 18  Grup edat                   280 non-null    str
dtypes: Int64(1), bool(1), datetime64[us](1), float64(3), int64(1), str(12)
memory usage: 68.4 KB

##### Valores contextuales

##### Valores contextuales: Temperatura mitjana ciutat

In [871]:
dataset_s8['Temperatura mitjana ciutat'].unique()

<ArrowStringArray>
['10.1', '18.7', '17.8', '15.4', '38.0', '22.0', '12.4', '19.7',    nan,
  '8.8',
 ...
 '22.1', '10.4', '10.9',  '9.4', '10.5', '21.7', '13.3', '10.7', '10.6',
  '6.5']
Length: 129, dtype: str

In [876]:
temp_num = pd.to_numeric(
    dataset_s8['Temperatura mitjana ciutat'],
    errors='coerce'
)

dataset_s8.loc[
    temp_num.isna() &
    dataset_s8['Temperatura mitjana ciutat'].notna(),
    'Temperatura mitjana ciutat'
].unique()

<ArrowStringArray>
[]
Length: 0, dtype: str