# NIVEL 1: 'EDA' ESTRUCTURADO Y LIMPIEZA DE DATOS

## EJERCICIO 1: EXPLORACIÓN INICIAL DEL DATASET

#### OBJETIVOS:
Con "sprint8_complex.xlsx" responder a las preguntas:

- Cuantas filas y columnas tiene el dataset
- Tipos de datos tiene cada columna
- Hay duplicados?
- Datos coherentes a simple vista?
- Posibles problemas o inconvenientes evidentes

Para responderlas hay que:

- Analizar la dimension del dataset
- Monstrar una muestra representativa de filas
- Revisar los tipos de variables
- Detectar duplicados
- Coherencia de datos
- Identificar y describir posibles problemas iniciales (sin solucionarlos)

Primero de todo instalo openpyxl para poder abrir el archivo xlsx. Pandas tiene la función de abrir un arhivo xlsx, pero necesita las instrucciones de openyxl para hacerlo.

pip install openpyxl

Completado la instalación, importo pandas y abro el archivo, dando el nombre de dataset_s8. Hago una visualización de los datos.

In [18]:
import pandas as pd
dataset_s8 = pd.read_excel('sprint8_complex.xlsx')
dataset_s8

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1006,1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1007,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1008,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

Cuantas filas y columnas tiene el dataset
- filas: 1010
- columnas: 20

Tipos de datos tiene cada columna
- La 4ª columna de "print(dataset_s8.info())" indica el tipo de dato. La mayoria son string, excepto la columna 1, 15 y 17 que son tipo object.

Hay duplicados?
- Si. Por ejemplo, en la columna Unnamed: 3 que debería ser DNI (valores únicos) tiene 993 valores únicos de 1007 no nulos que tiene.

Datos coherentes a simple vista?
- Se puede intuir los datos que corresponden a cada columna gracias a la muestra de 20 filas de la tabla superior. Hay algunas columnas que no tienen relación con otras (P.Ej: columna 1 sería nombre de persona y columna 19 es temperatura media de la ciudad)

Posibles problemas o inconvenientes evidentes
- Valores nules; encoding no definido; titulos de columna desordenados;

In [20]:
print("Información general tabla:")
print(dataset_s8.info())
dataset_s8.describe()

Información general tabla:
<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Dades de l'enquesta de treballadors 2025  1008 non-null   object
 1   Unnamed: 1                                1007 non-null   str
 2   Unnamed: 2                                1007 non-null   str
 3   Unnamed: 3                                1007 non-null   str
 4   Unnamed: 4                                1007 non-null   str
 5   Unnamed: 5                                1007 non-null   str
 6   Unnamed: 6                                1007 non-null   str
 7   Unnamed: 7                                1007 non-null   str
 8   Unnamed: 8                                1007 non-null   str
 9   Unnamed: 9                                967 non-null    str
 10  Unnamed: 10                               1007 non-null   str
 11  Unnamed: 11                               420 non-null    str
 12  Unnamed: 12                               586 non-null    str
 13  Unnamed: 13                               1006 non-null   str
 14  Unnamed: 14                               1006 non-null   str
 15  Unnamed: 15                               710 non-null    object
 16  Unnamed: 16                               659 non-null    str
 17  Unnamed: 17                               316 non-null    object
 18  Unnamed: 18                               262 non-null    str
 19  Unnamed: 19                               937 non-null    str
dtypes: object(3), str(17)
memory usage: 157.9+ KB
None

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
count,1008,1007,1007,1007,1007,1007,1007,1007,1007,967,1007,420,586,1006,1006,710,659,316,262,937
unique,1008,104,469,992,7,46,36,16,52,10,856,2,3,6,15,9,3,171,85,187
top,Generades aleatòriament per seguretat,AdriÃ,Ferrer,90585882A,Espanya,Palma,25.0,9.0,1982.0,D,n/d,True,True,Grup A,Data Analyst,0.0,False,80000,25.0,-5.0
freq,1,34,22,6,719,58,38,90,32,325,14,419,584,466,142,292,330,74,61,21

## EJERCICIO 2: VALIDACIÓN BÁSICA DE LOS DATOS Y DECISIONES DE ELIMINACIÓN

Existeixen identificadors únics (DNI) per a cada persona?
- Si. Columna "Unnamed: 3"

Què faràs amb les files duplicades o registres repetits?
- En caso de toda la fila esté duplicada solamente se almacena una y el resto se borra.
- En caso de que solamente un elemento de la fila esté repetido dependerá de la columna. Si es DNI (campo identificador) se borrarán ambos, ya que no se puede tener 2 DNIs repetidos y una modificación de uno de los registros aleatoriamente alteraría los datos.
- Hay 3 filas que son "Hijos" "No hijos" y "Nº hijos" donde se repite información. 

Hi ha valors obligatoris que falten o informació incoherent?
- Existe información incoherente. Hay datos que no tienen que ver con información personal.

Detectes formats incorrectes, errors de codificació o valors impossibles?
- Si. Los acentos están mal codificados